### ISSUE TITLE
Mention whats new in Wiki

### ISSUE THREAD

**Issue by IbnSaeed** [conformal/spectrwm#100]
Hello

Please mention "Whats new" in each new release. I checked the Wiki, and it lists 2.5.0 changes.

There has been many releases since than

* 2.5.1
* 2.6.0
* 2.6.1
* 2.6.2
* 2.7.0

Whats news in each new release, atleast add Whats new changes for 2.7.0, the latest release.

**Comment by marcopeereboom** [comment]
Fished out of git:

2.7.1+2.7.0:
Andreas Eriksson (1):
     Change libswmhack.so to use RTLD_NEXT functionality when _GNU_SOURCE is defined, and add some error handling.
 
Campbell Barton (3):
     Mouse button mapping config option, by levaidaniel
     Resolve memory leaks on exit.
     Resolve memory leaks on exit
 
Jonathan Armani (2):
     Add a new visible_noswap option that allow to not swap two visible workspace
     Document visible_noswap and at it in spectrwm.conf
 
Marco Peereboom (4):
     adjust copyright dates
     ad yuri to copyrights
     add queue.h to OSX
     Prepare for release 2.7.0.
 
Reginald Kennedy (14):
     Fix autorun.
     Change rg_move_(prev|next) and stack_balance to be unbound by default.
     Revert "Mouse button mapping config option, by levaidaniel"
     Add missing binds to keymapping files.
     Add new option: warp_focus
     Fix segfault when attempting to switch workspace during startup.
     Keep function prototypes in alphabetical order.
     Fix MINIMALBORDER on region focus cycling.
     Additional shutdown cleanup.
     Sort quirks in man page.
     Tweak the urgency indicator default padding for urgent_collapse = 1.
     Cleanup libswmhack.so.
     Pacify -Wconditional-uninitialized warnings.
     Improve the bind[] option to accept pointer buttons.
     Cleanup osx/queue.h whitespace.
 
Yuri D'Elia (6):
     Implement stack_balance and assign it to M-S-<h,l>
     Implement quirk NOFOCUSCYCLE to remove a window from the normal focus cycle.
     Add 'maximize_hide_bar' to also hide the bar when maximing a window.
     Implement rg_move_prev/rg_move_next to move workspaces across regions/screens.
     Strip trailing padding with urgent_collapse
     Add 'MINIMALBORDER' quirk to remove borders from floating/unfocused windows.

2.6.2:
David Hill (1):
     Use poll(2) instead of select(2).

Marco Peereboom (4):
     pull latest tag + commit digest
     osx also likes to see the extended build version
     Add Mod5 to support some more weird keyboards.
     Prepare for release 2.6.2.

Reginald Kennedy (1):
     Prevent possible focus change on release of a pointer grab.

shobute (1):
     Fixed bug in man page.

2.6.0+2.6.1:
Andrea Bolognani (2):
     Improve English man page.
     Improve Linux Makefile.

Jean-Philippe Ouellet (2):
     fix typo s/fallowing/following/
     Fix bug in baraction.sh that causes bar text to flicker every 20s.

Marco Peereboom (2):
     Revert "cleanup baraction.sh"
     Prepare for release 2.6.0.

Reginald Kennedy (8):
     Fix man page to use escape codes for aring å and pi π.
     Add new quirk IGNOREPID.
     Add new quirk IGNORESPAWNWS.
     Fix stacking issue at (re)start when spawn_position = first or prev.
     Convert all booleans to stdbool.h bool.
     Add new option: warp_pointer.
     Add new quirk: WS[n]
     Add new option: urgent_collapse

Varun B Patil (1):
     cleanup baraction.sh

2.5.1:
Marco Peereboom (1):
     Prepare for release 2.5.1.

Reginald Kennedy (6):
     Add clarification for the 'name' option to man page.
     Add default maximize_toggle binding to man page.
     Fix segfault in fullscreen layout when a window with transient(s) unmap.
     Set stacking order when setting up a new status bar.
     Improve stacking for windows with multiple transients.
     Fix segfault when loading "layout" with non-zero parameters.
