### ISSUE TITLE
Configuration issues - unbinding and custom bindings

### ISSUE THREAD

**Issue by ianhoolihan** [conformal/spectrwm#105]
I've just upgraded to v2.7.2 (on arch linux) and all of a sudden my config is giving 11 exceptions, all of them "invalid data for bind". They seem to be associated with:

 1. unbinding e.g. bind[] = MOD+Shift+Enter
 2. custom bindings e.g. bind[cycle_layout] = MOD+Space

Is this a known issue? Is there an available fix?

**Comment by caveman-** [comment]
You might want to replace "Enter" by "Return", that fixed it for me. It is rather inconvenient, that also the examples in the spectre.conf do this differently and should be corrected(by time I will do so and provide a PR)

**Comment by LordReg** [comment]
If you have 'invalid data for bind' errors, its likely you have a wrong key name (it's case sensitive).  Make sure you check the key name by running xev as explained in the man page (end of the BINDINGS section.)

'Enter' should be 'Return',  'Space' should be 'space'.

Example fixed on master.
