### ISSUE TITLE
removing external monitor eats windows

### ISSUE THREAD

**Issue by mischief** [conformal/spectrwm#108]
steps to reproduce:

* `exec spectrwm` from `startx`
* spawn windows (workspace 1, 2)
* setup external monitor: `xrandr --output eDP1 --auto --output DP2 --auto --above eDP1`
* unplug external monitor
* remove external monitor with `xrandr --auto`
* windows are eaten.

in my case, windows get eaten from workspace 1. the processes are still running, but the windows are gone and unaccessible (not in m-S-w)

**Comment by mischief** [comment]
spectrwm 2.7.2 built from gentoo portage ebuild.

**Comment by LordReg** [comment]
If you toggle the bar (MOD-b) do the windows reappear?

Also, what GPU and video driver?

**Comment by mischief** [comment]
@LordReg no toggling bar does not make the windows appear.

lspci -nn:
```
00:02.0 VGA compatible controller [0300]: Intel Corporation Broadwell-U Integrated Graphics [8086:1616] (rev 09)
```
lshw -c video:
```
  *-display               
       description: VGA compatible controller
       product: Broadwell-U Integrated Graphics
       vendor: Intel Corporation
       physical id: 2
       bus info: pci@0000:00:02.0
       version: 09
       width: 64 bits
       clock: 33MHz
       capabilities: msi pm vga_controller bus_master cap_list rom
       configuration: driver=i915 latency=0
       resources: irq:42 memory:f0000000-f0ffffff memory:e0000000-efffffff ioport:3000(size=64)
```

**Comment by mischief** [comment]
ping @LordReg. is there any additional info that i can provide? can you reproduce this?

**Comment by LordReg** [comment]
Is this still an issue on master branch?

**Comment by mischief** [comment]
i haven't hit this in a long time, and i've still been using 2.7.2 from gentoo. could be that an underlying X library changed and fixed this mysterious problem. looking forward to a new release though :-)
