### ISSUE TITLE
 new windows on current desktop

### ISSUE THREAD

**Issue by ghost** [conformal/spectrwm#11]
Please see http://opensource.conformal.com/fluxbb/viewtopic.php?id=6 for full discussion. In summary, new windows spawned from the same process open in the original workspace instead of the current one. For single-process terminals, browsers, and other programs this can be annoying.

@br recommended commenting out the setenv call in spawn(), which seems to work for both of us, but it is unclear what side effects this has.

**Comment by jblomo** [comment]
Thank you for adding this quirks mode, working beautifully.

**Comment by adriangrigore** [comment]
Any way that IGNORESPAWNWS obeys the autorun setting so that the initial window that is ran by autorun goes to its configured workspace and the other ones open in current ws? Currently IGNORESPAWNWS ignores the ws specified in autorun and just opens the window in the first ws.

**Comment by JJK96** [comment]
I was actually looking for the opposite problem. I would like my windows to spawn in the workspace they were created, now, I start a game in one workspace, then I switch back to my browser or something, and then suddenly the game window opens there, which is very annoying. What is the benefit of this change?

**Comment by marcopeereboom** [comment]
So you mean the default behavior...

**Comment by JJK96** [comment]
As I understand it, this was the default behaviour until the above mentioned patch was included. Because I have a pretty default i3 installation, and windows do spawn in other workspaces than the previous windows of the programs.

**Comment by JJK96** [comment]
Please excuse my question, I was somehow under the impression that this was an i3 thread, I must have been half sleeping...
