### ISSUE TITLE
Follow mouse dual monitors focus

### ISSUE THREAD

**Issue by avesus** [conformal/spectrwm#110]
When I move mouse pointer between windows on different windows, focus activated wonderfully.

When one monitor is empty (no windows on it), after moving mouse pointer over it and returning the pointer back _after about 1500 ms_, all works fine (but I note a strange delay of focus de-activating on the window).

When I move the pointer on the empty monitor and return it back into the window which was active _within 1500 ms_, the window _DOESN'T GET FOCUS WITH FOLLOW MOUSE FEATURE_. It activated only after mouse click.

Also, focus lost only in xterm. Chrome doesn't lose it.

**Comment by LordReg** [comment]
Does this still occur?

**Comment by avesus** [comment]
You have a new version after Septemper 2015?

**Comment by akamch** [comment]
Still a problem with spectrwm 3.0.2 on a Debian/testing system. xterm, Firefox, emacs lose focus in the described way while Chrome doesn't.

**Comment by quite** [comment]
I don't have this issue.

**Comment by LordReg** [comment]
I am unable to reproduce this issue with the latest version.  Please reopen if you still experience the problem.
