### ISSUE TITLE
Moving terminal to new workspace causing launching to open in previous workspace

### ISSUE THREAD

**Issue by ocdb** [conformal/spectrwm#112]
When opening a terminal in a workspace, followed by moving it to another, anything launched from said terminal will open in the previous workspace.
#### Example:

Open **urxvt** in **ws1**
Move to **ws2**
Run **sxiv** from **urxvt** that was moved to **ws2**
**sxiv** opens in the previous workspace, **ws1**

It's occurring on Arch Linux x86_64.

**Comment by marcopeereboom** [comment]
This is known behavior.  It is a side-effect of starting something and moving to another workspace and have the app load in the spawned workspace.  No one has found a fix for that although there are quirks to disable this behavior.
