### ISSUE TITLE
error while loading shared libraries: libxcb-util.so.1

### ISSUE THREAD

**Issue by sdoubleyou** [conformal/spectrwm#116]
try spectrwm with void linux. Each Terminal give me
error while loading shared libraries: libxcb-util.so.1: cannot open shared object file: No such file or directory
or
ERROR: ld.so: object ';' from LD_PRELOAD cannot preloaded (cannot open shared object file): ignored
ERROR: ld.so: object 'clear' from LD_PRELOAD cannot preloaded (cannot open shared object file): ignored
all dependencies are installed

**Comment by LordReg** [comment]
This sounds like an issue to take up with the package maintainer or you need to recompile on your system.
