### ISSUE TITLE
execvp: No such file or directory

### ISSUE THREAD

**Issue by mvhulten** [conformal/spectrwm#117]
When I press M-s (screenshot_all), no screenshot appears to be saved, and I get the message `spectrwm: spawn: execvp: No such file or directory`.

The problem occurs in spectrwm V2.7.2, both on Fedora 22 and on OpenBSD 5.8-STABLE.

**Comment by marcopeereboom** [comment]
You don’t have the script to take the screenshot setup, in the right spot, or not +x.

Something along those lines.
