### ISSUE TITLE
regression: iconified windows enter buggy state when plugging a new screen

### ISSUE THREAD

**Issue by wavexx** [conformal/spectrwm#120]
I noticed something new after switching from 2.6.2. Start with one screen (laptop), create a window of sorts (terminal) and iconify it. Plug a new monitor. The iconified window gets de-iconified and starts to flicker like mad, as if the state of the window gets somehow scrambled when a new screen/region is added.

**Comment by LordReg** [comment]
I haven't been able to reproduce this issue.  Does it still happen on master?

**Comment by wavexx** [comment]
On Mon, May 02 2016, LordReg <notifications@github.com> wrote:
> I haven't been able to reproduce this issue.  Does it still happen on master?

Yes, it's with master.

Although I noticed today it doesn't always do that (as usual..).
I don't know if it could happen due to a sequence of xrandr changes.

For instance, I have a script that calls xrandr --auto and sets the
primary to the external screen. I didn't try to disable the second step.

I'll also try to see if that's due to some setting I have.
Excluding quirks, fonts and colors I have currently:

modkey = Mod4
border_width = 3
tile_gap = -3
workspace_clamp = 1
urgent_collapse = 1
bar_at_bottom = 1
disable_border = 1
maximize_hide_bar = 1

**Comment by LordReg** [comment]
This should be fixed, please reopen if it isn't.
