### ISSUE TITLE
exrc + dir-locals

### ISSUE THREAD

**Issue by wavexx** [conformal/spectrwm#122]
What would you say to include an `.exrc` and `.dir-locals.el` file at the root of the project with the current preferences for indentation?

I have nothing against the current style, it's just that it's quite different than what I generally handle and sometimes just forget to set it correctly in the editor.

It would be nice just to preset them and be done. I can provide both files if needed (I use both vim and emacs interchangeably). I generally prefer external files as opposed to cluttering each source file with a modeline, but I can also do that if preferred.

**Comment by marcopeereboom** [comment]
> On May 1, 2016, at 11:32 AM, wavexx <notifications@github.com> wrote:
> 
> What would you say to include an .exrc and .dir-locals.el file at the root of the project with the current preferences for indentation?

As long as it doesn’t screw the style up I don’t care too much.  The thing to note is that some of the tables are not 100% within style because it would make it less readable.

> I have nothing against the current style, it's just that it's quite different that what I generally handle and sometimes just forget to set it correctly in the editor.

It is called KNF and it is C as $DEITY created it.  Now we call all disagree on what the ideal style is (unfortunately!) but this is what old C farts use and will continue to use.

> It would be nice just to preset them and be done. I can provide both files if needed (I use both vim and emacs interchangeably). I generally prefer external files as opposed to cluttering each source file with a modeline, but I can also do that if preferred.

What about all the other editors?

**Comment by wavexx** [comment]
On Mon, May 02 2016, Marco Peereboom <notifications@github.com> wrote:
>> On May 1, 2016, at 11:32 AM, wavexx <notifications@github.com> wrote:
>>
>> What would you say to include an .exrc and .dir-locals.el file at the
>> root of the project with the current preferences for indentation?
>
> As long as it doesn’t screw the style up I don’t care too much. The
> thing to note is that some of the tables are not 100% within style
> because it would make it less readable.

These presets don't do miracles, of course. They are just hints.

I mean, in vi it's mostly about setting shiftwidth, expandtab (or not)
and tabwidth correctly, so that pressing tab is ok and the block
indentation is mostly what you expect.

In emacs you can actually set some style parameters more tightly.

> It is called KNF and it is C as $DEITY created it. Now we call all
> disagree on what the ideal style is (unfortunately!) but this is what
> old C farts use and will continue to use.

No problem with that. I just want to make sure that when I submit a
patch it is consistent with the rest of the code.

> What about all the other editors?

I'm aware of vi/emacs modelines, but have no idea if other editors have
something similar.
