### ISSUE TITLE
LD_PRELOAD is set for all processes launched by spectrwm

### ISSUE THREAD

**Issue by ideasman42** [conformal/spectrwm#124]
I noticed when building my own software I had the error:

```
==27821==ASan runtime does not come first in initial library list; you should either link runtime to your application or manually preload it with LD_PRELOAD.
/bin/sh: line 1: 27821 Aborted                 (core dumped) 
```

This was caused by spectrwm setting the `LD_PRELOAD` for all sub-processes, including the terminal launched.

**Comment by marcopeereboom** [comment]
We use LD_PRELOAD to force windows onto their intended workspace.  Not sure what to do here.

**Comment by ideasman42** [comment]
I never use this feature, could it be an option to disable it?
