### ISSUE TITLE
resize tiles

### ISSUE THREAD

**Issue by Digit** [conformal/spectrwm#13]
since:

mod h = decrease main pane.
mod l = increase main pane

then i think there aught also be:

shift mod h = decrease selected window space.
shift mod l = increase selected window space.

i hope that's clear.
where " mod h/l " resizes along the " shift mod ,/. axis ", " shift mod h/l " resizes on the opposite axis to main pane. so that not all tiles in a collumn/row need be the same size anymore.

obviously the keybind would be configurable, i just thought that would be the easiest & clearest way to depict the idea.

**Comment by marcopeereboom** [comment]
I don't know how you could resize over the Y axis.  That is calculated based on available screen size.

**Comment by orbea** [comment]
It would not be possible in certain situational settings?  Like adjusting the height of tiled windows when you have two or more stacked on top of each other?

**Comment by Chadehoc** [comment]
I found this closed issue as I wanted to start a new feature request.
> I don't know how you could resize over the Y axis. That is calculated based on available screen size.

Xmonad has the ResizableTile extension
http://xmonad.org/xmonad-docs/xmonad-contrib/XMonad-Layout-ResizableTile.html
which lets the user resize the first window in the stacking area.

It uses a parameter "fraction to multiply the window height that would be given when divided equally". mod H (mod shift h) and mod L just decrease or increase this value, as it seems. So the stacking area sizes are still calculated automatically, only with an added parameter.

**Comment by marcopeereboom** [comment]
This is hard to visualize.  Send us a patch for evaluation.

**Comment by Chadehoc** [comment]
> This is hard to visualize. Send us a patch for evaluation.

I can try.

Can you just please tell me where I can find in the code the stacking
area sizing algorithm? I mean, where the available screen size is
divided and the sizes assigned to the individual stacked windows?

Thanks.
Eric

**Comment by avesus** [comment]
+1
An example is the following:
```
+-------------+-----------------------------------+
|             | (I want small height window here) |
|             +-----------------------------------+
|             |                                   |
|  Main area  |                                   |
|             +-----------------------------------+
|             |                                   |
|             |                                   |
+-------------+-----------------------------------+
```
