### ISSUE TITLE
regression: iconified windows enter buggy state when plugging a new screen

### ISSUE THREAD

**Issue by wavexx** [conformal/spectrwm#130]
So, it seems that #120 didn't fix the issue completely indeed.

With linux  + xorg + intel driver, when I plug a new screen, the iconified windows still enter a buggy state.
They don't flicker anymore (the fix for #127 seems to have resolved this), but they still show up uniconified (and unmanaged - they don't have a border and/or respond to focus cycling).

Indeed, I can "uniconify" the window to fix the window state.

Of note is the fact that when I plug the new screen I also set it as the new primary. I cannot *always* reproduce the issue, unfortunately.

**Comment by LordReg** [comment]
Please try the latest commit: 96a9efc6dd64855273b924a419aa2ccd334ad428.

**Comment by marcopeereboom** [comment]
What's the word?

**Comment by wavexx** [comment]
On Thu, May 19 2016, Marco Peereboom <notifications@github.com> wrote:
> What's the word?

I cannot say yet, I didn't switch monitors around in the last couple of
days. The fix looks sensible though ;)

**Comment by wavexx** [comment]
Tested right now. Couldn't reproduce the problem anymore, so let's close this!
