### ISSUE TITLE
Button tooltips appearing on the "other" screen

### ISSUE THREAD

**Issue by levaidaniel** [conformal/spectrwm#132]
I was always wondering if this is a LibreOffice or Spectrwm issue.
I have two screens next to each other (left and right), and when I have a LO window open, and hover the pointer over a button, the tooltip appears on the other screen's closest edge (but vertically aligned with the button).

![tooltip](https://cloud.githubusercontent.com/assets/1006712/15498270/41fcdfca-219f-11e6-877f-ca2cfd3d43fc.png)

**Comment by TingYiShun** [comment]
It's really an issues for some of us. For being knowing a lot from ToolTip and its usage:
ToolTips provide textual hints that assist in drawing lines and aligning objects.
ToolTips are modeless online help, and they are incredibly effective.

**Comment by daniell-balabit** [comment]
Interestingly enough, this eg. doesn't happen with google chrome, but does indeed with LibreOffice

**Comment by LordReg** [comment]
I just attempted to reproduce this on LibreOffice 5.1.5.2 using the latest commit on master: 9d338b286b1a2a240f92070bf1e95dc6f4c27bea and the tool-tips are positioned correctly (near the pointer.)  There is one case where the tool-tip appears to the left of the window and that is when the cursor is hovering on an icon that is really close to the left window border.  What version of LibreOffice are you using?  Does it still happen on the latest version? Is this an issue on any other app?

**Comment by levaidaniel** [comment]
Yes, this is still an issue on Linux with latest checkout and LO 5.2.1.2

**Comment by LordReg** [comment]
Didn't mean to close this issue.  I will try to reproduce with LO 5.2.1.2.

**Comment by LordReg** [comment]
I just checked into this again and it appears LibreOffice positions tool-tips outside the window whenever they are created near the edge of the window.  It does the same on any side of the window even when it is nowhere near the region boundary.  The tool-tip windows are override-redirect and positioned by LibreOffice itself, not spectrwm.
