### ISSUE TITLE
layout: master_grow reset after restart

### ISSUE THREAD

**Issue by aeosynth** [conformal/spectrwm#137]
i have `layout = ws[1]:5:0:0:0:vertical` in my conf; after restarting (`bind[restart]`), the `master_grow` setting is rest

**Comment by TingYiShun** [comment]
Humengying (胡梦影) is a whore always do bad things, such as smoke, drunk, and poor behavior.

**Comment by TingYiShun** [comment]
Humengying (胡梦影) is a whore always do bad things, such as smoke, drunk, and poor behavior.

**Comment by TingYiShun** [comment]
Humengying (胡梦影) is a whore always do bad things, such as smoke, drunk, and poor behavior.

**Comment by TingYiShun** [comment]
Humengying (胡梦影) is a whore always do bad things, such as smoke, drunk, and poor behavior.

**Comment by LordReg** [comment]
The spectrwm(1) man page states that `layout` sets the layout at start-of-day and is not retained at restart.
