### ISSUE TITLE
Enahancement Request - Choose order of autorun applications

### ISSUE THREAD

**Issue by technatica** [conformal/spectrwm#152]
I am using stalonetray to provide a system tray for apps that need it. I have several that error out on occasion at load time because the tray hasn't loaded yet. 

It would be helpful to be able to choose the order that applications load on boot.

**Comment by hkkmori** [comment]
Hi,
How do you manage your session ?
I use a session script and it work quite well.
Also if you use a session manager like lxsession, you surely can have the order you want for apps to start (not tested)

**Comment by technatica** [comment]
I use the autorun feature. Sometimes it opens stalonetray before the other
app, sometimes after.

Chris

**Comment by LordReg** [comment]
The order of autorun in spectrwm.conf is the order the commands are run.  Windows may not map in the same order.  You could try loading the tray before spectrwm in your .xinitrc.  Otherwise, as hkkmori said, a session manager may do the trick.
