### ISSUE TITLE
MOD+z and MOD+slash bindings won't work

### ISSUE THREAD

**Issue by seschwar** [conformal/spectrwm#156]
If I bind any function to MOD+z or MOD+slash it won't trigger on key press. Binding the function to any other key makes it trigger just fine.

I've tried this with both `modkey = Mod1` and `modkey = Mod4`. Neither works. X11 applications just receive a regular `alt+z` or `super+z`.

I use the following to set my keyboard layout:

    setxkbmap \
        -layout us,de \
        -option caps:super,compose:menu,grp:sclk_toggle,grp_led:scroll,terminate:ctrl_alt_bksp

This is with spectrwm 3.0.2 on xorg-server 1.18.4.

**Comment by seschwar** [comment]
Today I managed to reproduced this on Debian. The above was on Arch Linux.

In addition to MOD+z and MOD+slash I also found that MOD+bracketleft, MOD+bracketright and MOD+backslash bindings were not working on both distributions either.

**Comment by LordReg** [comment]
What does xev report for KeyPress when you press those key combinations?

**Comment by seschwar** [comment]
Here's the output of xev:

    KeyPress event, serial 40, synthetic NO, window 0x1c00001,
        root 0x30f, subw 0x0, time 10584745, (485,140), root:(486,159),
        state 0x10, keycode 66 (keysym 0xffeb, Super_L), same_screen YES,
        XLookupString gives 0 bytes: 
        XmbLookupString gives 0 bytes: 
        XFilterEvent returns: False

    KeyPress event, serial 40, synthetic NO, window 0x1c00001,
        root 0x30f, subw 0x0, time 10585432, (485,140), root:(486,159),
        state 0x50, keycode 52 (keysym 0x7a, z), same_screen YES,
        XLookupString gives 1 bytes: (7a) "z"
        XmbLookupString gives 1 bytes: (7a) "z"
        XFilterEvent returns: False

    KeyRelease event, serial 40, synthetic NO, window 0x1c00001,
        root 0x30f, subw 0x0, time 10585588, (485,140), root:(486,159),
        state 0x50, keycode 52 (keysym 0x7a, z), same_screen YES,
        XLookupString gives 1 bytes: (7a) "z"
        XFilterEvent returns: False

    KeyRelease event, serial 40, synthetic NO, window 0x1c00001,
        root 0x30f, subw 0x0, time 10585627, (485,140), root:(486,159),
        state 0x50, keycode 66 (keysym 0xffeb, Super_L), same_screen YES,
        XLookupString gives 0 bytes: 
        XFilterEvent returns: False

    KeyPress event, serial 40, synthetic NO, window 0x1c00001,
        root 0x30f, subw 0x0, time 10589816, (485,140), root:(486,159),
        state 0x10, keycode 66 (keysym 0xffeb, Super_L), same_screen YES,
        XLookupString gives 0 bytes: 
        XmbLookupString gives 0 bytes: 
        XFilterEvent returns: False

    KeyPress event, serial 40, synthetic NO, window 0x1c00001,
        root 0x30f, subw 0x0, time 10590199, (485,140), root:(486,159),
        state 0x50, keycode 34 (keysym 0x5b, bracketleft), same_screen YES,
        XLookupString gives 1 bytes: (5b) "["
        XmbLookupString gives 1 bytes: (5b) "["
        XFilterEvent returns: False

    KeyRelease event, serial 40, synthetic NO, window 0x1c00001,
        root 0x30f, subw 0x0, time 10590287, (485,140), root:(486,159),
        state 0x50, keycode 34 (keysym 0x5b, bracketleft), same_screen YES,
        XLookupString gives 1 bytes: (5b) "["
        XFilterEvent returns: False

    KeyRelease event, serial 40, synthetic NO, window 0x1c00001,
        root 0x30f, subw 0x0, time 10590369, (485,140), root:(486,159),
        state 0x50, keycode 66 (keysym 0xffeb, Super_L), same_screen YES,
        XLookupString gives 0 bytes: 
        XFilterEvent returns: False

    KeyPress event, serial 40, synthetic NO, window 0x1c00001,
        root 0x30f, subw 0x0, time 10590956, (485,140), root:(486,159),
        state 0x10, keycode 66 (keysym 0xffeb, Super_L), same_screen YES,
        XLookupString gives 0 bytes: 
        XmbLookupString gives 0 bytes: 
        XFilterEvent returns: False

    KeyPress event, serial 40, synthetic NO, window 0x1c00001,
        root 0x30f, subw 0x0, time 10591276, (485,140), root:(486,159),
        state 0x50, keycode 35 (keysym 0x5d, bracketright), same_screen YES,
        XLookupString gives 1 bytes: (5d) "]"
        XmbLookupString gives 1 bytes: (5d) "]"
        XFilterEvent returns: False

    KeyRelease event, serial 40, synthetic NO, window 0x1c00001,
        root 0x30f, subw 0x0, time 10591413, (485,140), root:(486,159),
        state 0x50, keycode 35 (keysym 0x5d, bracketright), same_screen YES,
        XLookupString gives 1 bytes: (5d) "]"
        XFilterEvent returns: False

    KeyRelease event, serial 40, synthetic NO, window 0x1c00001,
        root 0x30f, subw 0x0, time 10591522, (485,140), root:(486,159),
        state 0x50, keycode 66 (keysym 0xffeb, Super_L), same_screen YES,
        XLookupString gives 0 bytes: 
        XFilterEvent returns: False

    KeyPress event, serial 40, synthetic NO, window 0x1c00001,
        root 0x30f, subw 0x0, time 10592133, (485,140), root:(486,159),
        state 0x10, keycode 66 (keysym 0xffeb, Super_L), same_screen YES,
        XLookupString gives 0 bytes: 
        XmbLookupString gives 0 bytes: 
        XFilterEvent returns: False

    KeyPress event, serial 40, synthetic NO, window 0x1c00001,
        root 0x30f, subw 0x0, time 10592769, (485,140), root:(486,159),
        state 0x50, keycode 61 (keysym 0x2f, slash), same_screen YES,
        XLookupString gives 1 bytes: (2f) "/"
        XmbLookupString gives 1 bytes: (2f) "/"
        XFilterEvent returns: False

    KeyRelease event, serial 40, synthetic NO, window 0x1c00001,
        root 0x30f, subw 0x0, time 10592861, (485,140), root:(486,159),
        state 0x50, keycode 61 (keysym 0x2f, slash), same_screen YES,
        XLookupString gives 1 bytes: (2f) "/"
        XFilterEvent returns: False

    KeyRelease event, serial 40, synthetic NO, window 0x1c00001,
        root 0x30f, subw 0x0, time 10593314, (485,140), root:(486,159),
        state 0x50, keycode 66 (keysym 0xffeb, Super_L), same_screen YES,
        XLookupString gives 0 bytes: 
        XFilterEvent returns: False

    KeyPress event, serial 40, synthetic NO, window 0x1c00001,
        root 0x30f, subw 0x0, time 10599119, (485,140), root:(486,159),
        state 0x10, keycode 134 (keysym 0xffec, Super_R), same_screen YES,
        XLookupString gives 0 bytes: 
        XmbLookupString gives 0 bytes: 
        XFilterEvent returns: False

    KeyPress event, serial 40, synthetic NO, window 0x1c00001,
        root 0x30f, subw 0x0, time 10600032, (485,140), root:(486,159),
        state 0x50, keycode 52 (keysym 0x7a, z), same_screen YES,
        XLookupString gives 1 bytes: (7a) "z"
        XmbLookupString gives 1 bytes: (7a) "z"
        XFilterEvent returns: False

    KeyRelease event, serial 40, synthetic NO, window 0x1c00001,
        root 0x30f, subw 0x0, time 10600134, (485,140), root:(486,159),
        state 0x50, keycode 52 (keysym 0x7a, z), same_screen YES,
        XLookupString gives 1 bytes: (7a) "z"
        XFilterEvent returns: False

    KeyRelease event, serial 40, synthetic NO, window 0x1c00001,
        root 0x30f, subw 0x0, time 10600295, (485,140), root:(486,159),
        state 0x50, keycode 134 (keysym 0xffec, Super_R), same_screen YES,
        XLookupString gives 0 bytes: 
        XFilterEvent returns: False

    KeyPress event, serial 40, synthetic NO, window 0x1c00001,
        root 0x30f, subw 0x0, time 10601423, (485,140), root:(486,159),
        state 0x10, keycode 134 (keysym 0xffec, Super_R), same_screen YES,
        XLookupString gives 0 bytes: 
        XmbLookupString gives 0 bytes: 
        XFilterEvent returns: False

    KeyPress event, serial 40, synthetic NO, window 0x1c00001,
        root 0x30f, subw 0x0, time 10602073, (485,140), root:(486,159),
        state 0x50, keycode 34 (keysym 0x5b, bracketleft), same_screen YES,
        XLookupString gives 1 bytes: (5b) "["
        XmbLookupString gives 1 bytes: (5b) "["
        XFilterEvent returns: False

    KeyRelease event, serial 40, synthetic NO, window 0x1c00001,
        root 0x30f, subw 0x0, time 10602158, (485,140), root:(486,159),
        state 0x50, keycode 34 (keysym 0x5b, bracketleft), same_screen YES,
        XLookupString gives 1 bytes: (5b) "["
        XFilterEvent returns: False

    KeyRelease event, serial 40, synthetic NO, window 0x1c00001,
        root 0x30f, subw 0x0, time 10602317, (485,140), root:(486,159),
        state 0x50, keycode 134 (keysym 0xffec, Super_R), same_screen YES,
        XLookupString gives 0 bytes: 
        XFilterEvent returns: False

    KeyPress event, serial 40, synthetic NO, window 0x1c00001,
        root 0x30f, subw 0x0, time 10602630, (485,140), root:(486,159),
        state 0x10, keycode 134 (keysym 0xffec, Super_R), same_screen YES,
        XLookupString gives 0 bytes: 
        XmbLookupString gives 0 bytes: 
        XFilterEvent returns: False

    KeyPress event, serial 40, synthetic NO, window 0x1c00001,
        root 0x30f, subw 0x0, time 10603165, (485,140), root:(486,159),
        state 0x50, keycode 35 (keysym 0x5d, bracketright), same_screen YES,
        XLookupString gives 1 bytes: (5d) "]"
        XmbLookupString gives 1 bytes: (5d) "]"
        XFilterEvent returns: False

    KeyRelease event, serial 40, synthetic NO, window 0x1c00001,
        root 0x30f, subw 0x0, time 10603253, (485,140), root:(486,159),
        state 0x50, keycode 35 (keysym 0x5d, bracketright), same_screen YES,
        XLookupString gives 1 bytes: (5d) "]"
        XFilterEvent returns: False

    KeyRelease event, serial 40, synthetic NO, window 0x1c00001,
        root 0x30f, subw 0x0, time 10603384, (485,140), root:(486,159),
        state 0x50, keycode 134 (keysym 0xffec, Super_R), same_screen YES,
        XLookupString gives 0 bytes: 
        XFilterEvent returns: False

    KeyPress event, serial 40, synthetic NO, window 0x1c00001,
        root 0x30f, subw 0x0, time 10603690, (485,140), root:(486,159),
        state 0x10, keycode 134 (keysym 0xffec, Super_R), same_screen YES,
        XLookupString gives 0 bytes: 
        XmbLookupString gives 0 bytes: 
        XFilterEvent returns: False

    KeyPress event, serial 40, synthetic NO, window 0x1c00001,
        root 0x30f, subw 0x0, time 10604577, (485,140), root:(486,159),
        state 0x50, keycode 61 (keysym 0x2f, slash), same_screen YES,
        XLookupString gives 1 bytes: (2f) "/"
        XmbLookupString gives 1 bytes: (2f) "/"
        XFilterEvent returns: False

    KeyRelease event, serial 40, synthetic NO, window 0x1c00001,
        root 0x30f, subw 0x0, time 10604666, (485,140), root:(486,159),
        state 0x50, keycode 61 (keysym 0x2f, slash), same_screen YES,
        XLookupString gives 1 bytes: (2f) "/"
        XFilterEvent returns: False

    KeyRelease event, serial 40, synthetic NO, window 0x1c00001,
        root 0x30f, subw 0x0, time 10604780, (485,140), root:(486,159),
        state 0x50, keycode 134 (keysym 0xffec, Super_R), same_screen YES,
        XLookupString gives 0 bytes: 
        XFilterEvent returns: False

    KeyPress event, serial 40, synthetic NO, window 0x1c00001,
        root 0x30f, subw 0x0, time 10605091, (485,140), root:(486,159),
        state 0x10, keycode 134 (keysym 0xffec, Super_R), same_screen YES,
        XLookupString gives 0 bytes: 
        XmbLookupString gives 0 bytes: 
        XFilterEvent returns: False

    KeyPress event, serial 40, synthetic NO, window 0x1c00001,
        root 0x30f, subw 0x0, time 10605968, (485,140), root:(486,159),
        state 0x50, keycode 51 (keysym 0x5c, backslash), same_screen YES,
        XLookupString gives 1 bytes: (5c) "\"
        XmbLookupString gives 1 bytes: (5c) "\"
        XFilterEvent returns: False

    KeyRelease event, serial 40, synthetic NO, window 0x1c00001,
        root 0x30f, subw 0x0, time 10606041, (485,140), root:(486,159),
        state 0x50, keycode 51 (keysym 0x5c, backslash), same_screen YES,
        XLookupString gives 1 bytes: (5c) "\"
        XFilterEvent returns: False

    KeyRelease event, serial 40, synthetic NO, window 0x1c00001,
        root 0x30f, subw 0x0, time 10606356, (485,140), root:(486,159),
        state 0x50, keycode 134 (keysym 0xffec, Super_R), same_screen YES,
        XLookupString gives 0 bytes: 
        XFilterEvent returns: False

    KeyPress event, serial 40, synthetic NO, window 0x1c00001,
        root 0x30f, subw 0x0, time 10611378, (485,140), root:(486,159),
        state 0x10, keycode 66 (keysym 0xffeb, Super_L), same_screen YES,
        XLookupString gives 0 bytes: 
        XmbLookupString gives 0 bytes: 
        XFilterEvent returns: False

    KeyPress event, serial 40, synthetic NO, window 0x1c00001,
        root 0x30f, subw 0x0, time 10611806, (485,140), root:(486,159),
        state 0x50, keycode 51 (keysym 0x5c, backslash), same_screen YES,
        XLookupString gives 1 bytes: (5c) "\"
        XmbLookupString gives 1 bytes: (5c) "\"
        XFilterEvent returns: False

    KeyRelease event, serial 40, synthetic NO, window 0x1c00001,
        root 0x30f, subw 0x0, time 10611878, (485,140), root:(486,159),
        state 0x50, keycode 51 (keysym 0x5c, backslash), same_screen YES,
        XLookupString gives 1 bytes: (5c) "\"
        XFilterEvent returns: False

    KeyRelease event, serial 40, synthetic NO, window 0x1c00001,
        root 0x30f, subw 0x0, time 10612072, (485,140), root:(486,159),
        state 0x50, keycode 66 (keysym 0xffeb, Super_L), same_screen YES,
        XLookupString gives 0 bytes: 
        XFilterEvent returns: False

**Comment by LordReg** [comment]
What is the keyboard mapping at the time spectrwm starts?  spectrwm resolves keysyms to keycodes when it starts and binds all actions to the resulting keycodes.  If you start spectrwm with the de layout active and then switch to the us layout after it starts, spectrwm would still be using the de key map.

**Comment by seschwar** [comment]
On 2016-11-24, LordReg wrote:
> What is the keyboard mapping at the time spectrwm starts?

I use the above `setxkbmap` command well before i start
`spectrwm` in my `~/.xinitrc`.  I usually don't switch layouts.
I just use `us` all the time.  The `de` one is only there as a
fallback in case a coworker needs to quickly type something on
my machine.

**Comment by seschwar** [comment]
Also all the keys mentioned above work fine as keybindings in
for example `awesome` or `i3`.

**Comment by seschwar** [comment]
I've just found out something rather curious.

Here's an excerpt from my configuration:

    modkey = Mod4
    program[searcher] = rofi -show window
    bind[searcher] = MOD+slash
    bind[ws_9] = MOD+z
    bind[ws_10] = MOD+x

As is reported above pressing and releasing MOD+z or MOD+slash
does nothing.  However lets take a look at what happens in the
following sequence:

1. Pressing and holding MOD+x takes me to workspace 9.
2. Pressing and releasing MOD+z now takes me to workspace 10!
3. Finally releasing MOD+x does nothing.

Instead of MOD+x any other working key binding can be held.  And
instead of MOD+z any other key binding I reported as not working
above except MOD+slash can be made to work like this.

For MOD+slash things behave a bit differently:

1. Pressing and holding MOD+x takes me to workspace 9.
2. Press and releasing MOD+slash does nothing.
3. Releasing MOD+x now launches `rofi`!

I don't really know what to make of this, but maybe you do.

**Comment by seschwar** [comment]
All of this also happens on FreeBSD:

- FreeBSD 11.0-RELEASE-p5
- xorg-server-1.17.4,1
- xf86-input-keyboard-1.8.1
- spectrwm-3.0.2

**Comment by mnl** [comment]
I'm having the same issue. I'd like to map the keys **Super + <** and **Super + §**. 
`MOD+less` does nothing, as mentioned above. `MOD+§` returns an error - even though that's the name `xev` reports.

**Comment by seschwar** [comment]
@mnl, try `MOD+paragraph` instead of `MOD+§`. That should be the correct X11 name for that key.

I haven't made any progress on the original issue though.

**Comment by LordReg** [comment]
https://github.com/conformal/spectrwm/tree/grabfix should fix this issue, can you verify?

**Comment by qirex-rd** [comment]
That link no longer works, but I assume the commit in question is c1479cfd78f3305becaacb62546062e7ad4c9bd6. That particular commit causes spectrwm to go into an infinite loop. But after having fixed that (see #237) it indeed solves my initial problem. Thanks!

**Comment by seschwar** [comment]
That link no longer works, but I assume the commit in question is c1479cf. That particular commit causes spectrwm to go into an infinite loop. But after having fixed that (see #238) it indeed solves my initial problem. Thanks!

**Comment by marcopeereboom** [comment]
Can you try latest?

**Comment by seschwar** [comment]
My problem was fully fixed with 84c356dfe607691924a84e05537e853c045b19c1. The latest version (f3d7a4d5e8a349908604ea98fd28addf6f6d1c57) works just fine now.
