### ISSUE TITLE
interaction between focus_mode manual and ws_next_move -- client gets confused

### ISSUE THREAD

**Issue by quite** [conformal/spectrwm#159]
When `focus_mode` is `manual`, the client which is brought along to the target workspace with `ws_next_move` seems to get confused, is flickering and behaving very strangely indeed. I have to restart spectrwm to put things right. Going back to `default`, and `ws_next_move` then properly brings along the current client.

**Comment by ahjstone** [comment]
Indeed, still persisting. Selecting another workspace [ ws_⟨1-22⟩ ] then selecting the target workspace stops the flickering. Moving to the target workspace with mvws_⟨1-22⟩ works though.
