### ISSUE TITLE
spectrwm stuck after doing mvws on a window with floating modal dialog

### ISSUE THREAD

**Issue by nicolaisingh** [conformal/spectrwm#163]
Arch Linux, spectrwm v3.0.2

I have an app open with a floating modal dialog (e.g. pcmanfm with Preferences dialog open, or Leafpad with Font dialog open).  When I transfer it to another workspace, focus seems to be stuck on the modal, and all keyboard hotkeys do not work.

In order to regain control, I have to focus (using the mouse) another window in my current workspace. But if I don't have another window open, then spectrwm is stuck. I have to kill the process and restart.

If I focus first on the parent window while the modal is open, the issue does not occur. It seems spectrwm gets stuck only when a focused modal dialog is moved to another workspace.

![modal](https://cloud.githubusercontent.com/assets/25273924/22179336/7cd48c3c-e08b-11e6-9c36-7b9011836ae6.jpg)

**Comment by LordReg** [comment]
This should be fixed as of a485f9a628767cae146d38f71d500907c05046f8 .
