### ISSUE TITLE
mvrg break external screen rendering

### ISSUE THREAD

**Issue by 0x041E** [conformal/spectrwm#167]
I'm using laptop with external VGA screen set on the left of laptop screen and i have few windows running on external screen using default keybindings and when i pressed MOD+Shift+Down (bind[mvrg_2]        = MOD+Shift+KP_Down) my external screen rendering completely breaks. It seems like there is problem in the workspace wrapping
Here is link to video of it i recorded with my phone: https://youtu.be/UBFt8HgCbKI

**Comment by LordReg** [comment]
Do you still experience this issue with the latest version?  Might be related to #159 . Do you have `focus_mode = manual` set?

**Comment by marcopeereboom** [comment]
Timeout. Please reopen if still an issue.
