### ISSUE TITLE
Failure to focus thunderbirds new message window

### ISSUE THREAD

**Issue by Hafting** [conformal/spectrwm#169]
When I write a message in Thunderbird, Thunderbird opens a new window for writing the message. This works fine if Thunderbird is the last application started. 

But I usually leave thunderbird running, and starts other programs in the meantime. (Xterms, Openoffice, Lyx, Evince)  Then I come back to Thunderbird to write some message. Thunderbird is running on my second screen which is the biggest. (with a smaller screen on either side). The message window appear in the stack on the second screen, but it cannot be focused. Not even by clicking on it! Instead, whatever is running on the third monitor gets focus. (Red border and receives keystrokes.) Everything else on monitor 2 can be focused, but not the "new message" window. As it cannot be focussed, I cannot maximize it or move it to another screen either - such actions apply to the focused program.

This makes it impossible to write email - unless I use workarounds such as restarting thunderbird. Closing every program on the third screen also works - spectrwm gives up its crazy attempt to focus the third screen when nothing is displayed on it.

I use arch linux, 64bit. spectrvm V3.0.2
xrandr reports this for my displays:
eDP1 connected primary 1920x1080+0+0 (small laptop screen, left display 1)
DP1-1 connected 1920x1080+1920+0 (big center display 2)
DP1-2 connected 1024x1280+3840+0 (small right display 3, rotated to portrait orientation)

.spectrwm.conf:
disable_border		= 1
bar_enabled		= 1
bar_justify		= center
bar_at_bottom		= 1
clock_enabled		= 1
clock_format		= %A %e. %B %Y (uke %V)  %k:%M

#Oddity, the second works and not the first?
autorun		=	ws[1]:urxvt	-fn	"xft:Bitstream Vera Sans Mono:pixelsize=32"
autorun   = ws[2]:urxvt

autorun		=	ws[1]:xclock -g 200x200+1720+880
autorun		=	ws[1]:xscreensaver -nosplash

layout		= ws[1]:0:0:0:0:horizontal
layout		= ws[2]:4:0:0:0:vertical
layout		= ws[3]:0:0:0:0:horizontal

modkey = Mod4
# Validated default programs:
program[lock]		= xscreensaver-command -lock
program[term]		= urxvt -fn 9x15
quirk[XClock:xclock]	= FLOAT + ANYWHERE
quirk[Gkrellm:gkrellm] = FLOAT + ANYWHERE

**Comment by LordReg** [comment]
is this still an issue on master?

**Comment by marcopeereboom** [comment]
timeout
