### ISSUE TITLE
Layout gets thrown away on restart

### ISSUE THREAD

**Issue by mwm** [conformal/spectrwm#172]
it's sort of obnoxious that the layout I went out of my way to set up with the layout command in my config is tossed when I restart spectrwm. I can understand not saving the current layouts (I've done that before, but it's not quite trivial), but going back to my preferred default seems to be a better option than going to the global default.

The fix for this is easy, since setlayout goes out of it's way to not run on restarts. So just remove the lines that check that:

```
index 653f349..82de527 100644
--- a/spectrwm.c
+++ b/spectrwm.c
@@ -9310,9 +9310,6 @@ setlayout(const char *selector, const char *value, int flags)
        (void)selector;
        (void)flags;
 
-       if (getenv("SWM_STARTED"))
-               return (0);
-
        bzero(s, sizeof s);
        if (sscanf(value, "ws[%d]:%d:%d:%d:%d:%1023c",
            &ws_id, &mg, &ma, &si, &ar, s) != 6)
```

**Comment by marcopeereboom** [comment]
I can live with this if we add a new restart command.

**Comment by mwm** [comment]
Which command should be the new one? The one that resets layout to start-of-day for compatibility? Or should the one that effectively does a stack_reset on all workspaces be given the new name, say "reset"?

**Comment by LordReg** [comment]
As I recall, `layout` was designed to only apply on first start to leave room for layout preservation between restarts.  It seems layout preservation is forgotten intended behavior.  It should be relatively painless to implement using a root window property with a custom atom (e.g. _SWM_LAYOUT).  It can work similar to `name` and _NET_DESKTOP_NAMES.

**Comment by marcopeereboom** [comment]
The reason we decided not to apply the layout from the ini file was to be able to recover from bad layouts in the ini file.  I still think that was not a bad decision but I recognize that people may want to not have that behavior.  That said, I think we should reread and reapply the format from the ini if we add a special restart command.  People can then replace the key binding of the old restart command with the new one.  That way we preserve the old behavior while allowing said new behavior.
