### ISSUE TITLE
[Program] directive in config file not working

### ISSUE THREAD

**Issue by lwinch2006** [conformal/spectrwm#175]
Spectrwm: 3.0.2
OS: Archlinux 
Kernel: Linux 4.11.2-1-ARCH

Trying configuration:
program[test123] = xterm

Should be:
when typing test123 in the menu spectrwm should find it and launch xterm when pressed Enter.

Actually is: 
spectrwm does not find test123

**Comment by LordReg** [comment]
`program[test123]` defines a new `test123` action to be used by `bind`.  To use the `test123` action, you need to bind it.
Example:
```
program[test123] = xterm
bind[test123] = MOD+d
```
The menu is for running shell commands and it lists programs in your PATH.
