### ISSUE TITLE
Trailing whitespace in configuration option causes failure

### ISSUE THREAD

**Issue by ransom1509** [conformal/spectrwm#178]
Spectrwm version 3.0.2 build 3.0.2
OS: Slackware 14.2
Editor: Vim

Trailing whitespace in configuration option causes option to fail.

Example 1
program[foo] = foo
bind[foo] = MOD+<key>r<whitespace>
Exception when restarting spectrwm

Without whitespace
program[foo] = foo
bind[foo] = MOD+<key>
Works.

Example 2
quirk[Foo:foo]    = FLOAT<whitespace>
Window is mapped to a tile.

quirk[Foo:foo]    = FLOAT
Window is floating.

Probably it should be mentioned in the man pages, that trailing whitespace has to be avoided. Better trailing whitespace is removed prior to processing the options. 
I apologize if the issue is known or if I missed something in the docs, but I did not find any matching issue. I only recently discovered spectrwm and I love it. Thank you for a great wm.

**Comment by ransom1509** [comment]
The editor fsck up my text: It should be

Example 1 
bind[foo] = MOD+anykey[whitespace]
Exception when restarting spectrwm

Without whitespace
program[foo] = foo
bind[foo] = MOD+anykey

quirk[Foo:foo] = FLOAT[whitespace]
Window is mapped to a tile.

**Comment by LordReg** [comment]
Hi ransom1509, this was reported as a pull request (#150) and is already merged to master, thanks for the report.
