### ISSUE TITLE
Polybar or Yabar not correctly managed

### ISSUE THREAD

**Issue by quiniouben** [conformal/spectrwm#180]
Hi,
User of archlinux, I just moved to spectrwm and wanted to use a fancy status bar like polybar or yabar.
It seems that this does not work properly, as for both, the bar is in the focus chain and bound to a workspace.
Removing it from focus chain with quirk NOFOCUSCYCLE does work, with side-effect that the bar places itself in screen center...
I tried out with default spectrwm and polybar configurations, with or without region definition, with or without the spectrwm bar enabled, with same result.
Is there something specific to do to make it work ?
As a side note, using conky + dzen2 works well.
Anyway, thank you for spectrwm, it fullfills my needs perfectly for every other aspect.

**Comment by helvetie** [comment]
[Lemonbar](https://github.com/LemonBoy/bar) does not work either (tested on latest spectrwm version).

**Comment by mnl** [comment]
Try @delxg 's branch. I have used several tray bars/docks without problems using #147 & #149

**Comment by quiniouben** [comment]
Yep that works, thank you.
Waiting for potential merge in the conformal repo, I forked the delxg repo and merged the 2 branches in my own master branch, to be able to have an easy to use PKGBUILD :).
I may not be following the changes in delxg or conformal very regularly, but you can make use of my fork if you want, of course: https://github.com/quiniouben/spectrwm

**Comment by Manu-sh** [comment]
I can confirm, this solution work also for me, thx

**Comment by hackedWifi** [comment]
Polybar works perfectly fine. You have to set the region the bar should be occupied. like for me 
I have region = screen[1]:3840x2080+0+80 My monitor ix 3840X2160. So, I reserve 2080 for windows and 80 for the bar. Then to avoid the focus on polybar you have to have override-redirect = true.
I use Archlinux on Dell XPS9550 HighDPI

**Comment by qsmodo** [comment]
@hackedWifi In my experience, if you go that way the panel is occluded by maximized/fullscreen windows. On the other hand, if you reserve a region for the bar (it woud be region = screen[1]:3840x80+0+0 in your example), then the bar is never occluded even if you want a fullscreen window, and in addition the region reserves a workspace.
