### ISSUE TITLE
New Chrome instance opens on last workspace

### ISSUE THREAD

**Issue by joshuakraemer** [conformal/spectrwm#190]
If I close Chrome and afterwards start Chrome again on another workspace, the new Chrome instance opens on the workspace where the previous instance was closed, but it should open on the current workspace.

Steps to reproduce:

1. start Chrome
2. close Chrome
3. switch to another workspace
4. start Chrome again

I have the following in spectrwm.conf (as mentioned in #11), but it doesn't help:
`quirk[.*] = IGNORESPAWNWS + IGNOREPID`

After closing Chrome, I have confirmed with the following command that it is not running anymore:
`ps -e | grep chrome`

I'm using the current Git master with last commit ea3e6da62247572e92c4ba00f70eab73f6254adf on openSUSE Tumbleweed.

**Comment by LordReg** [comment]
The process should be `chromium` not `chrome`, so it might still be running.  Also, do you have any other quirk[] entries?  That quirk statement will not apply if there is another matching quirk following that entry.

Also, this may not affect this issue, but make sure to enable "use system title bar and borders" in chromium settings to have it let the window manager manage.

**Comment by joshuakraemer** [comment]
Thank you for your comment. I'm using Chrome from Google's repository, that's why the process name is "chrome". I have no other quirk entries. "Use system title bar and borders" is already enabled.

**Comment by lpanebr** [comment]
I'm using spectrwm from the Ubuntu repository and have the same problem behavior with Google chrome.
Any ideas as how to force new chrome windows to open on the current workspace?

**Comment by lpanebr** [comment]
Actually the quirks setting [mentioned here](https://github.com/conformal/spectrwm/issues/11#issuecomment-42643673 ) DID WORK for me!
`quirk[.*] = IGNORESPAWNWS + IGNOREPID`

excellent!

**Comment by LordReg** [comment]
@lpanebr Alternatively, you can use the following entry to have the workaround apply only to chrome windows:
```
quirk[Google-chrome] = IGNORESPAWNWS + IGNOREPID
```
Full details of quirks are in the QUIRKS section of the man page.

**Comment by lpanebr** [comment]
Thanks you!
Perhaps adding that sample line in the `default .spectrwm.conf` along with
a comment "Workaround for additional windows not being opened in the
current workspace." would make users try this before opening an issue.

**Comment by lpanebr** [comment]
maybe a "Know quirks" section in the readme and/or FAQs would be even
better! ;-)


Atenciosamente,

*Luciano Panepucci*
Cofundador e Diretor de Tecnologia

*+55 (16) 3307-2068 r. 22*
+55 (16) 991 728 681
skype: lpanebr


soluções para o universo acadêmico

Rua Marechal Deodoro 2709
13560-201 São Carlos - SP
www.editoracubo.com.br

--------
Q: Why is this email five sentences or less?
A: http://five.sentenc.es

--------
Notes to myself:
Falta de tempo é desculpa daqueles que perdem tempo por falta de métodos.
[Albert Einstein]


Em seg., 20 de abr. de 2020 às 09:44, Luciano Panepucci <
luciano@editoracubo.com.br> escreveu:

> Thanks you!
> Perhaps adding that sample line in the `default .spectrwm.conf` along with
> a comment "Workaround for additional windows not being opened in the
> current workspace." would make users try this before opening an issue.
>
