### ISSUE TITLE
Once in a while, spectrwm hangs

### ISSUE THREAD

**Issue by rohshall** [conformal/spectrwm#192]
It happens rarely, maybe once in 2-3 days. But, it does not respond to keys.
Here are the .xsession-errors, which may, or may not have anything to do with it:
`
spectrwm: Welcome to spectrwm V3.1.0 Build: 3.1.0

#####!!! [Parent][MessageChannel] Error: (msgtype=0x100037,name=PBackground::Msg_DispatchLocalStorageChange) Channel closing: too late to send/recv, messages will be lost

[Parent 1055, Gecko_IOThread] WARNING: pipe error (120): Connection reset by peer: file /builds/worker/workspace/build/src/ipc/chromium/src/chrome/common/ipc_channel_posix.cc, line 353

`

I am on Arch Linux. But, I have seen it happening on Ubuntu 17.10 with NVidia drivers as well.

**Comment by LordReg** [comment]
It might be related to the the program you are using.  In particular, it may happen when you click and drag a tab/toolbar in a program, etc.  Do you recall what program you were using when it hangs?  You may be able to unfreeze by killing the program.

**Comment by orbea** [comment]
qjackctl used to do this with spectrwm and some other window managers, but at least for spectrwm it was fixed somewhere, possibly the fix was in neither qjackctl or spectrwm...

**Comment by orbea** [comment]
I'm not sure about qjackctl, but this is a common occurance on high load, especially if I am compiling in workspace 1 and then switch to firefox in workspace 3. Sometimes the mouse never comes back until after I press `mod+q`.

**Comment by marcopeereboom** [comment]
Can you try latest?

**Comment by orbea** [comment]
I built the current master (https://github.com/conformal/spectrwm/commit/f3d7a4d5e8a349908604ea98fd28addf6f6d1c57), but it might take a bit before I realize if my issue still occurs or not.

**Comment by orbea** [comment]
I have a good feeling about my issue being fixed, I have since experienced several momentary hangs from high CPU/RAM usage where my mouse cursor has always worked correctly afterwards.

**Comment by marcopeereboom** [comment]
Awesome. Please reopen if not fixed.
