### ISSUE TITLE
load charset

### ISSUE THREAD

**Issue by szorfein** [conformal/spectrwm#193]
Hi, i come back to spectrwm after several years :)

but when i try to launch it on gentoo, i get theses errors:

```
spectrwm: Welcome to spectrwm V3.1.0 Build: 3.1.0
spectrwm: ignoring region 1366x768+0+37 - not within screen boundaries (1366x768)
which: no exec in (/home/izsha/node_modules/cordova/bin:/home/izsha/bin:/usr/lib64/node_modules:/home/izsha/AndroidStudioProjects/Android-meteor/tools:/home/izsha/AndroidStudioProjects/Android-meteor/platform-tools:/opt/oracle-jdk-bin-1.8.0.112:/usr/x86_64-pc-linux-gnu/gcc-bin/7.1.0:/usr/local/bin:/usr/bin:/bin:/opt/bin:/home/izsha/.gems/bin)
spectrwm: Unable to load charset(s):
spectrwm: ISO8859-1
spectrwm: ISO8859-1
spectrwm: ISO8859-2
spectrwm: ISO8859-3
spectrwm: ISO8859-4
spectrwm: ISO8859-5
spectrwm: KOI8-R
spectrwm: ISO8859-7
spectrwm: ISO8859-9
spectrwm: ISO8859-13
spectrwm: ISO8859-14
spectrwm: ISO8859-15
spectrwm: JISX0208.1983-0
spectrwm: KSC5601.1987-0
spectrwm: GB2312.1980-0
spectrwm: JISX0201.1976-0
spectrwm: ISO10646-1
```
And minimal `~/.spectrwm.conf`, i improved it when i could start:

```
bar_enabled		= 0
region		= screen[1]:1366x768+0+37
modkey = Mod4
keyboard_mapping = ~/.config/spectrwm/spectrwm_fr.conf
program[lock]		= i3lock
program[term]		= termite
program[menu]		= exec /usr/bin/rofi -show run
```

thx

**Comment by LordReg** [comment]
Hi szorfein,
The default XLFD bar_font has been problematic for some users recently.  Try changing bar_font to an Xft font. e.g.:
`bar_font = Terminus:pixelsize=14:antialias=true`

For a display resolution of 1366x768 where you want to reserve 37px on top, `region` should be:
`region = screen[1]:1366x731+0+37`

You don't need `exec` when defining a spawn program:
`program[menu]		= /usr/bin/rofi -show run`

**Comment by szorfein** [comment]
good, it works !  i did well to post an issue.  

Just have to set polybar and i'll gone :), thx !

**Comment by LordReg** [comment]
> Is there any setup that definately should work (on Archlinux) that I can test?

For Arch Linux, this works for me:
`bar_font = xos4 Terminus:pixelsize=14:antialias=true`

Just make sure it is `~/.spectrwm.conf` you are editing.

**Comment by szorfein** [comment]
i post the config file to my [repo](https://github.com/szorfein/dotfiles/blob/master/.spectrwm.conf).  
Terminus has work but i've change with iosevka,  
to find the good name, you have fc-list : `$ fc-list | grep -i terminus`, try with other font, it should work :)

**Comment by MarcusE1W** [comment]
Hi both.
Thanks for the quick answer. I can confirm it works now for me.
Having a working example really helped.
