### ISSUE TITLE
Urgency not being cleared

### ISSUE THREAD

**Issue by subsetpark** [conformal/spectrwm#194]
The `+U` urgency indicators are not being cleared on my status bar. I'm not 100% on what triggers them, though certain things are apparent, like activity in WeeChat. However, simply activating those windows or using MOD+u doesn't clear the urgency indicator. I have to close the window to clear the number. This is on Arch Linux, version:

`spectrwm: Welcome to spectrwm V3.1.0 Build: 3.1.0`

**Comment by LordReg** [comment]
Is the UrgencyHint flag actually being cleared on the window?  You can check using `xprop`, WM_HINTS property.  It is up to the program to clear the flag.  What terminal do you use?  rxvt-unicode, for example, will clear the flag when focus is changed.

**Comment by subsetpark** [comment]
@LordReg - thanks for clearing up my confusion. I had assumed, wrongly, that the urgency flag was the same as the activity highlighting in i3. Indeed, I see strange behavior with Sakura and the urgency hint. In my WeeChat, it clears urgency after returning to the terminal. However, in my shell (es-shell) it doesn't seem to. I'll dig in on my side.
