### ISSUE TITLE
Comment symbol interpreted as data

### ISSUE THREAD

**Issue by junkdeck** [conformal/spectrwm#197]
Just installed spectrwm from the antiX package repository - spectrwm 3.0.2 according to the -v

When binding a key combo, putting `#` anywhere in the line will result in an "invalid data for bind" error.

**Comment by junkdeck** [comment]
Okay, just checked to see if it was just unbinding that caused this, and apparently it's any kind of whitespace in the binding declaration.

**Comment by LordReg** [comment]
This was fixed in 3.1.0
