### ISSUE TITLE
how to iconify/minimize/unmap windows and no resizing of other windows?

### ISSUE THREAD

**Issue by ahjstone** [conformal/spectrwm#201]
When iconifying/minimizing/unmapping (keybinding: M-w) a window, how to:
- prevent resizing of the other window(s) in a/all workspace(s)?
- optionally resize/unresize the other window(s) with a keybinding?

EDIT: added "in a/all workspace(s)".

**Comment by marcopeereboom** [comment]
I am not following this but I do see multiple requests. Please reopen with clear description and one thing per issue. Patches are also welcome.
