### ISSUE TITLE
focus_mode = follow + layout = fullscreen causes flickering

### ISSUE THREAD

**Issue by subsetpark** [conformal/spectrwm#204]
With `focus_mode = follow` on, fullscreen layouts don't seem to work well. With two windows, the screen flickers repeatedly between the two and the window name in the status bar flickers between the two names.

It seems like the `follow` is based on window screen coordinates, which will not overlap in vertical layouts but will in fullscreen.

Then again, if I have a floating window, focus works perfectly.

So maybe focus mode should just be disabled entirely while the layout is fullscreen?

**Comment by Filip62** [comment]
Same issue here in year 2020. Great job devs.

**Comment by marcopeereboom** [comment]
Dup #333
