### ISSUE TITLE
Empty workspace's screen not get redrawn/refreshed

### ISSUE THREAD

**Issue by tsunghanlin** [conformal/spectrwm#205]
Linux distro: Ubuntu
Spectrwm works perfectly on my Ubuntu 16.04.
However, after upgrading to 17.10(even the latest 18.04), I found that every time I switch to an new empty 
workspace, that workspace's screen is not getting refreshed or redrawn.

For example, I have a browser opened in workspace 1 but when I try to do some other works on a new workspace, after switching to a workspace, I found that workspace's screen is still showing previous workspace's screenshot, that is, an opened browser.
Though those kinds of non-refreshed screenshot get replaced when I open something in that new workspace, but it is still quite annoying.

I've tried compiled the latest spectrwm from github and replaced the binary in my system, but that didn't help at all. 

Anyone having this problem? Could it be the difference in Unity (used in 16.04) and Gnome(used after 17.x) that causes the problem?

Thanks.

**Comment by LordReg** [comment]
Sounds like the root background may need to be set.
try this in your spectrwm.conf:
```
autorun                 = ws[1]:xsetroot -solid black
```

**Comment by LordReg** [comment]
I'm unsure of the exact reason in this case, but it wouldn't surprise me if it was related to the use of a display manager and/or compositor.
