### ISSUE TITLE
Window re-positioning of UTILITY windows

### ISSUE THREAD

**Issue by wavexx** [conformal/spectrwm#206]
I have a program that seem to be mis-managed by spectrwm. This program is creating some _NET_WM_WINDOW_TYPE_UTILITY windows which are repositioned automatically during their lifetime.

The windows float correctly by default, but it looks like they are not repositioned as requested by the program (I'm using openbox as a reference). Setting the ANYWHERE quirk doesn't really help.

I noticed menus of some java programs behave in a similar way, and I suspect some move/resize requests are simply ignored by spectrwm.

Is this possible?

**Comment by LordReg** [comment]
Could you give an example of a program with the issue?

**Comment by wavexx** [comment]
On Wed, Jun 27 2018, LordReg wrote:
> Could you give an example of a program with the issue?

Unfortunately, the one that exhibits this is all the time is
proprietary. It's using GTK2 though underneath.

**Comment by LordReg** [comment]
> I noticed menus of some java programs behave in a similar way
I was referring to that.  Always nicer to have a program to test.

Does the proprietary program support _NET_WM_MOVERESIZE ?

**Comment by wavexx** [comment]
On Wed, Jun 27 2018, LordReg wrote:
>     I noticed menus of some java programs behave in a similar way
>     I was referring to that. Always nicer to have a program to test.

Ah yes, this one is "sqlworkbench" (beta), from:

http://www.sql-workbench.eu/

using the default "plastic" skin on jre-11. Sometimes you can click on
any popup menu (not only the _main_ menubar), and the menu pops in a
different location. Still, since the window has grab focus, you can see
that the items themselves highlight "as if" the menu was in the correct
spot, which is quite interesting.

> Does the proprietary program support _NET_WM_MOVERESIZE ?

Need to check on that. But given it's just gtk2 underneath, I suspect
so.

**Comment by marcopeereboom** [comment]
Timeout. Reopen if this is still an issue.
