### ISSUE TITLE
Setting Coordinate Transformation Matrix will break warp_pointer

### ISSUE THREAD

**Issue by zuglufttier** [conformal/spectrwm#208]
For some mysterious reason, warp_pointer does not work for me if I use my logitech trackball.

If I change to another work space or window, the mouse pointer is visible in the center of the new window (as it should) but if I move the trackball, the pointer is at the lower right corner of the window.

**Comment by zuglufttier** [comment]
I found the problem! It has nothing to do with the trackball at all, I can reproduce it with a normal mouse.

I'm using libinput and this command to change the mouse speed:
```
xinput set-prop "Logitech USB Trackball" "Coordinate Transformation Matrix" 2, 0, 0, 0,
2, 0, 0, 0, 1
```

If it's changed back to default, everything works as expected.

**Comment by zuglufttier** [comment]
The same problem exists if I use dwm as window manager with this patch: https://dwm.suckless.org/patches/warp/

So, maybe it's a general problem for tiling window managers?

**Comment by marcopeereboom** [comment]
10:25 <@LordReg> marco: yo, pinpointed issue #208.  made a patch that fixes it using 
                 xinput2 WarpPointer, but it depends on xcb >= 1.9 and xinput2 extension.  
                 Any thoughts on how dated of a system we should support?
10:29 < marco> how old is that?
10:32 < marco> xcb 1.9 seems oldish
10:33 < marco> Release 1.9 (2012-10-05) <-- libxcb 1.9
10:35 < marco> also 2012 for xinput 2
10:35 < marco> so i am ok with that
