### ISSUE TITLE
libswmhack breaks MATLAB R2018a/2019a

### ISSUE THREAD

**Issue by mattpusey** [conformal/spectrwm#209]
At least on my Debian Stretch system (meaning spectrwm 3.0.2), libswmhack prevents MATLAB R2018a from loading. The splash screen appears for a bit but then it bails out with "libswmhack.so: ERROR: /usr/lib/spectrwm/libswmhack.so.0.0: undefined symbol: XtAppNextEvent" plus some other stuff on stderr: [matlab_errors.txt](https://github.com/conformal/spectrwm/files/2228195/matlab_errors.txt)

No other applications seem affected, and if I run "LD_PRELOAD= matlab" then MATLAB works as normal.

**Comment by mattpusey** [comment]
I still have the same error message with MATLAB R2019a and spectrwm 3.2.0 on Debian Buster. Here's the new crash report: 
[matlab_errors_2.txt](https://github.com/conformal/spectrwm/files/3456172/matlab_errors_2.txt)

**Comment by KSPAtlas** [comment]
I had the same issue, but with a different program. spectrwm should really unset LD_PRELOAD

**Comment by LordReg** [comment]
#276 (included in 3.5.0) should have fixed this. Please reopen if it is still an issue.

**Comment by Randoragon** [comment]
This is still an issue for some applications, see #559.
