### ISSUE TITLE
Bind layouts directly

### ISSUE THREAD

**Issue by sgelb** [conformal/spectrwm#210]
Currently, you have to cycle through the layouts to change them on a workspace. I'd be nice if I there were bindings for each layout, so I could use a shortcut to eg maximized directly.

**Comment by sgelb** [comment]
Thanks you for your help. I know about this binding, but I want the change on the layout level, not for a single window.

**Comment by LordReg** [comment]
I've [got a branch](https://github.com/conformal/spectrwm/tree/bind_layouts) that adds the following new actions to directly switch to the desired layout:
```
layout_vertical
layout_horizontal
layout_max
```
All currently unbound by default.

Should be able to get this into the upcoming release.  Appreciate any feedback/testing.

**Comment by sgelb** [comment]
That sounds great, thanks a lot! I'll install that branch tomorrow and give it a try.

**Comment by sgelb** [comment]
@LordReg: so far, everything is working fine. This is exactly what I wanted, thanks a lot!
