### ISSUE TITLE
Emacs can't input wide character using SCIM

### ISSUE THREAD

**Issue by a4free** [conformal/spectrwm#211]
Thanks for invent spectrwm, it's excellent.
[SCIM](https://en.wikipedia.org/wiki/Smart_Common_Input_Method) is a common input choice for wide character user.
Question just as the tile, I changed the set mark command in escape to other shortcut to escape the conflict with SCIM's fireup key.
In spectrwm, still Emacs can't input wide character.
I test in XFCE wm, but it get work, so maybe it's not the wrong about configuration. Maybe something is wrong about spectrwm's configure, basically, I use the default spectrwm's configuration.
@davecgh @jcvernaleo @jrick Hope get help. thoundsand thanks.

**Comment by a4free** [comment]
`quirk[Emacs:emacs]                      = FLOAT + FULLSCREEN` is my Emacs configure in spectrwm.

**Comment by a4free** [comment]
ps. Firefox works well in spectrwm, input wide character is well.

**Comment by LordReg** [comment]
It looks like it is related to locale.
Running emacs like this works for me:
`LC_CTYPE=C emacs`

**Comment by a4free** [comment]
Thanks @LordReg for your response.
It seems not that reason, I try but failed again.

**Comment by a4free** [comment]
`spectrwm: unable to load charset(s)
spectrwm: GBK-0
spectrwm: Glyphs from these sets won't be drawn.`
I set LC_CTYPE=zh_CN.UTF-8

**Comment by marcopeereboom** [comment]
Timeout. Please reopen if it is still an issue.
