### ISSUE TITLE
Feature request: bar_action should be able to handle arguments

### ISSUE THREAD

**Issue by jpnance** [conformal/spectrwm#214]
At the moment (spectrwm 3.1.0), the following `spectrwm.conf` line works fine:

``bar_action = ~/bar.sh``

Adding a parameter to it, however, seems to result in the bar action not getting executed at all:

``bar_action = ~/bar.sh 15``

It'd be nice if `bar_action` had arguments parsed just like the other lines in `spectrwm.conf`.

**Comment by mewa** [comment]
`bar_action` is currently treated as a string which is then passed to `execvp` (https://github.com/conformal/spectrwm/blob/SPECTRWM_3_2_0/spectrwm.c#L2973), and there's obviously no program with such name.
The only thing that's happening is expansion of tilde into home directory. (https://github.com/conformal/spectrwm/blob/SPECTRWM_3_2_0/spectrwm.c#L1336). If you were to pass `$HOME/bar.sh` instead - that wouldn't have worked either.

I think it would make sense to delegate parameters and environment variables parsing to the shell, so we can avoid parsing these things.

**Comment by mewa** [comment]
@LordReg I just noticed there already is a [`spawn_expand`](https://github.com/conformal/spectrwm/blob/master/spectrwm.c#L7754-L7853) function. I guess it could be used instead (and probably preferred)?
Still, env vars expansion would have to be handled.

**Comment by marcopeereboom** [comment]
This is working as designed.
