### ISSUE TITLE
Deleted windows still on screen

### ISSUE THREAD

**Issue by donaldcallen** [conformal/spectrwm#216]
Intermittently, I delete a window, such as a terminal window, and the image of the window remains on screen. If I go to another workspace and then come back to the workspace where the window was, it is now gone, as it should be. dwm does not exhibit this behavior.

**Comment by jpnance** [comment]
I've noticed this type of behavior when I don't have a background set. If you do `xsetroot -solid darkblue`, do you still have this issue?

**Comment by donaldcallen** [comment]
You are right -- setting a background does seem to eliminate this problem. But that's a work-around for what seems to me to be a bug.

**Comment by LordReg** [comment]
Do you happen to use GDM to start spectrwm?  GDM starts X with the argument `-background none` which stops X from updating the root window background until it gets set by some program like xsetroot, feh etc.  spectrwm itself doesn't touch the root window background so you can workaround the `-background none` by setting the background in .xinitrc, .xprofile or autorun in spectrwm.conf.  Running a compositing manager also works.

**Comment by donaldcallen** [comment]
On Wed, 19 Sep 2018 at 06:37, LordReg <notifications@github.com> wrote:

> Do you happen to use GDM to start spectrwm? GDM starts X with the argument -background
> none which stops X from updating the root window background until it gets
> set by some program like xsetroot, feh etc. spectrwm itself doesn't touch
> the root window background so you can workaround the -background none by
> setting the background in .xinitrc, .xprofile or autorun in spectrwm.conf.
> Running a compositing manager also works.
>
I just use startx and a .xinitrc. I've worked around the problem by
xsetroot-ing the background in the .xinitrc.

**Comment by LordReg** [comment]
This issue occurs when the root window background is unset (e.g. X argument `-background none`) and it is unrelated to spectrwm.  spectrwm itself never touches the root window background.  The solution is to set the background with the X argument `-background <color>` or with a program such as `xsetroot`.

**Comment by donaldcallen** [comment]
On Wed, 5 Dec 2018 at 00:07, LordReg <notifications@github.com> wrote:

> This issue occurs when the root window background is unset (e.g. X
> argument -background none) and it is unrelated to spectrwm.
>
I have used other window managers, tiling and otherwise, and none of them
exhibit this problem.

> spectrwm itself never touches the root window background.
>
Then it should, if the user hasn't, to avoid having unsuspecting users
close windows and have them remain on the screen.

**Comment by mschilli87** [comment]
@donaldcallen:
> >  spectrwm itself never touches the root window background.
>
> Then it should

How about a warning or an entry in the FAQ or the like?
If I explicitely don't set a background, I wouldn't want my window manager to decide that I ment to get a black/white/pink one. To me, 'no background' being interpreted as 'transparent' makes sense and upstream (X11) seems to agree. And the argument that all other window managers do it differently might just be what make me (or someone else) choose spectrwm over all those alternatives. :wink:

**Comment by donaldcallen** [comment]
On Wed, 5 Dec 2018 at 09:15, Marcel Schilling <notifications@github.com>
wrote:

> @donaldcallen <https://github.com/donaldcallen>:
>
> spectrwm itself never touches the root window background.
>
> Then it should
>
> How about a warning or an entry in the FAQ or the like?
> If I explicitely don't set a background, I wouldn't want my window manager
> to decide that I ment to get a black/white/pink one. To me, 'no background'
> being interpreted as 'transparent' makes sense and upstream (X11) seems to
> agree. And the argument that all other window managers do it differently
> might just be what make me (or someone else) choose spectrwm over all those
> alternatives. 😉
>
That makes sense to me, especially a warning (I don't think the user should
be expected to dig this out of the documentation herself; it is bizarre
behavior for a deleted window to remain on the screen; first time it
happened to me, I thought the system was hung). Or perhaps a boolean option
to set the background if the user leaves it unset. If false, then issue the
warning. And perhaps the default should be false -- less intrusive, per the
reasons you gave.

**Comment by donaldcallen** [comment]
On Wed, 5 Dec 2018 at 09:15, Marcel Schilling <notifications@github.com>
wrote:

> @donaldcallen <https://github.com/donaldcallen>:
>
> spectrwm itself never touches the root window background.
>
> Then it should
>
> How about a warning or an entry in the FAQ or the like?
> If I explicitely don't set a background, I wouldn't want my window manager
> to decide that I ment to get a black/white/pink one. To me, 'no background'
> being interpreted as 'transparent' makes sense and upstream (X11) seems to
> agree. And the argument that all other window managers do it differently
> might just be what make me (or someone else) choose spectrwm over all those
> alternatives. 😉
>
And I would add that having a deleted window remain on the screen with no
warning from spectrwm as to the reason (and nothing in the documentation
that I have found) could make users choose alternatives over spectrwm. In
other words, I don't think failing to address this, as implied by the
message announcing the closing of this issue, is sensible.
