### ISSUE TITLE
HELP, how to configure spectrwm when using two different resolution monitor

### ISSUE THREAD

**Issue by a4free** [conformal/spectrwm#219]
spectrwm is very brilliant wm.
Here I run into a problem: I want to use two different resolution monitor, one is for reading news, emails and the other is used to do some common work.
Just configure `region` seems doesn't work:
I tried to plug the second monitor, but just copy the major monitor content and the window in major monitor shrink at the same time.

**Comment by mschilli87** [comment]
@a4free: I'm using a dual-monitor setup and the was no need tp adjust anything in sprectrwm to set it up. I guess your screens are set to mirror which you'll need to change on the OS level. Assuming you are on GNU/Linux, `xrandr` might be what you are looking for.

**Comment by a4free** [comment]
> @a4free: I'm using a dual-monitor setup and the was no need to adjust anything in sprectrwm to set it up. I guess your screens are set to mirror which you'll need to change on the OS level. Assuming you are on GNU/Linux, `xrandr` might be what you are looking for.

Many thx, Marcel. I'll have a try.

**Comment by LordReg** [comment]
this isn't an issue with spectrwm.  outputs need to be arranged via xrandr/xorg.conf otherwise they will simply display the same thing reduced to a resolution all the monitors support.
