### ISSUE TITLE
Use a terminal as a scratchpad

### ISSUE THREAD

**Issue by oregnier** [conformal/spectrwm#222]
Hi
I wish to have the possibility to use my terminal as a scratchpad. Is it possible?
Thanks

**Comment by LordReg** [comment]
Not sure how this relates to the window manager.  spectrwm manages program windows and allows you to start programs via bindings and/or autorun at startup.  If you want a scratchpad, you can install/run such a program.

**Comment by strange** [comment]
You could probably build something with `wmctrl`. (`wmctrl -r <name> -b toggle,hidden` for example).

**Comment by strange** [comment]
Maybe something like this (barely tested) for [kitty:](https://github.com/kovidgoyal/kitty) in a file name `scratchpad` somewhere on your path:

```
#/bin/sh
windowname="scratchpad-$1"
desk=`wmctrl -d | grep '*' | cut -d ' ' -f '1'`
scratch_desk=`wmctrl -l | grep $windowname | cut -d ' ' -f '3'`

xprop -name "$windowname"

if [ $? -eq 0 ]; then
    if [ $desk -eq $scratch_desk ]; then
        wmctrl -r $windowname -t $desk
        wmctrl -r $windowname -b toggle,hidden
    else
        wmctrl -R $windowname
        wmctrl -r $windowname -b remove,hidden
    fi
else
    kitty --title $windowname
fi
```

With bindings in your `.specrwm.conf`:

```
bind[scratchpad-1] = MOD+Page_Up
bind[scratchpad-2] = MOD+Page_Down

program[scratchpad-1] = scratchpad 1
program[scratchpad-2] = scratchpad 2
```

You can probably configure spectrwm to place the windows where you want them. Otherwise just show them once, reposition them, and hide them again.

**Comment by strange** [comment]
Also, you might want to use something other than title/name for terminal emulators that allow programs to change it (otherwise you won't be able to target the windows again). Or you could store the window ids in a tmp file or something. Good luck!
