### ISSUE TITLE
Mixed spec $bar_font breaks menu (dmenu_run)

### ISSUE THREAD

**Issue by ghost** [conformal/spectrwm#223]
Environment: Fedora 28
spectrwm-3.0.2-5.fc28.x86_64
dmenu-4.8-1.fc28.x86_64

Setting the bar_font configuration variable to an Xft font (`bar_font = Inconsolata:size=12`) breaks the menu command. Spectrwm passes to dmenu_run a string with both Xft and XLFD specs, a comma-separated string of the Xft font followed by the fallback XLFD fonts. A script intercepting the arguments passed to dmenu recorded this output:

```
args -b Inconsolata:size=12,-*-terminus-medium-*-*-*-12-*-*-*-*-*-*-*,-*-profont-*-*-*-*-12-*-*-*-*-*-*-*,-*-times-medium-r-*-*-12-*-*-*-*-*-*-*,-misc-fixed-medium-r-*-*-12-*-*-*-*-*-*-*,-*-*-*-r-*-*-*-*-*-*-*-*-*-* black rgb:a0/a0/a0 rgb:00/80/80 black
executing dmenu_run -b -fn Inconsolata:size=12,-*-terminus-medium-*-*-*-12-*-*-*-*-*-*-*,-*-profont-*-*-*-*-12-*-*-*-*-*-*-*,-*-times-medium-r-*-*-12-*-*-*-*-*-*-*,-misc-fixed-medium-r-*-*-12-*-*-*-*-*-*-*,-*-*-*-r-*-*-*-*-*-*-*-*-*-* -nb black -nf rgb:a0/a0/a0 -sb rgb:00/80/80 -sf black
error, cannot load font from name: 'Inconsolata:size=12,-*-terminus-medium-*-*-*-12-*-*-*-*-*-*-*,-*-profont-*-*-*-*-12-*-*-*-*-*-*-*,-*-times-medium-r-*-*-12-*-*-*-*-*-*-*,-misc-fixed-medium-r-*-*-12-*-*-*-*-*-*-*,-*-*-*-r-*-*-*-*-*-*-*-*-*-*'
no fonts could be loaded.
```

Executing `dmenu_run -b -fn "Inconsolata:size=12" -nb black -nf rgb:a0/a0/a0 -sb rgb:00/80/80 -sf black` works with dmenu-4.8.

Proposals:
- [ ] `spectrwm` doesn't fix font types in $bar_font.
- [ ] Update man page for Xft support in dmenu 4.6+.
- [ ] Handle mixed font spec example in man page.

**Comment by bradmwalker** [comment]
Reproduced with `spectrwm-3.2.0-1.fc28.x86_64`.

**Comment by LordReg** [comment]
If I understand correctly, you are proposing that spectrwm pass only what the user enters on `bar_font` without the fallbacks?  I think that makes sense for the sake of consistency with the other program[] args.

**Comment by bradmwalker** [comment]
Hi, LordReg. Excluding fallbacks in program[] args would suffice to fix the common case of specifying one Xft font for dmenu. Is the LCD for this value's type Xft xor XLFD font specifications? If so should there be input validation/documentation?

**Comment by vext01** [comment]
I was about to raise a similar bug.

If you have a one-line config file containing:
```
bar_font Liberation Mono:pixelsize=20
```

All is well. But if you have:

```
bar_font Liberation Mono:size=20
```

The bar has the correct font and size, but dmenu with CTRL+p no longer works.

I checked dmenu accepts this kind of font argument. i.e. this works:
```
dmenu_run -fn "Liberation Mono:size=20"
```

**Comment by vext01** [comment]
Seems like a dmenu bug/quirk:
```
$ echo "1" | dmenu -fn "Liberation Mono:style=Regular:pixelsize=20,-*-terminus-medium-*-*-*-12-*-*-*-*-*-*-*,-*-profont-*-*-*-*-12-*-*-*-*-*-*-*,-*-times-medium-r-*-*-12-*-*-*-*-*-*-*,-misc-fixed-medium-r-*-*-12-*-*-*-*-*-*-*,-*-*-*-r-*-*-*-*-*-*-*-*-*-*" -nb darkslategray -nf rgb:a0/a0/a0 -sb darkslategray -sf coral
```

Works.

Replacing `pixelsize` with `size` does not.

But I'm also OK with the proposal to NOT pass down fallback fonts.

**Comment by marcopeereboom** [comment]
@LordReg opinion?

**Comment by marcopeereboom** [comment]
Who is writing this patch?

**Comment by vext01** [comment]
Not me right now I'm afraid. I'm not currently using spectrwm.

**Comment by marcopeereboom** [comment]
Heresy.

**Comment by bradmwalker** [comment]
I started using xmonad again with Ubuntu.

**Comment by christianharke** [comment]
After upgrading spectrwm to 3.4.1 I had to change the line

```
bar_font = VictorMono Nerd Font:style=SemiBold:pixelsize=11:antialias=true
```

to 

```
bar_font = VictorMono Nerd Font:style=SemiBold:size=11:antialias=true
```

to get dmenu_run work again.

Something changed between 3.3.0 to 3.4.1 in this matter, I guess?

**Comment by connorhodes** [comment]
> After upgrading spectrwm to 3.4.1 I had to change the line
> 
> ```
> bar_font = VictorMono Nerd Font:style=SemiBold:pixelsize=11:antialias=true
> ```
> 
> to
> 
> ```
> bar_font = VictorMono Nerd Font:style=SemiBold:size=11:antialias=true
> ```
> 
> to get dmenu_run work again.
> 
> Something changed between 3.3.0 to 3.4.1 in this matter, I guess?

I just had a different experience. I had to change

```
bar_font	        	= HackNerdFont:size=11, JoyPixels:size=11
```
to
```
bar_font	        	= HackNerdFont:pixelsize=20, JoyPixels:pixelsize=20
```
(the opposite of you) to get dmenu_run working again. I'm also on 3.4.1
