### ISSUE TITLE
layout_max, floating window problem

### ISSUE THREAD

**Issue by donaldcallen** [conformal/spectrwm#228]
I have bound a little script to pop up an xclock for a few seconds
program[clk]=run_xclock
bind[clk]=Mod+c

I also request that xclock windows float:
quirk[XClock] = FLOAT

This works as I would expect, except if I cycle to layout_max with, say, a terminal window as the focused window and then press Mod+c. What happens is what appears to be a rapid alternation between the terminal window and a maximized xclock. It appears that the two windows are fighting for the focus.

Related, I think, is that if I am in layout_vertical in an empty ws and start an xclock, I get the appropriately sized floating window I expect. If I now cycle to layout_max, the xclock is maximized. It seems to me that the layouts should apply to tiled, not floating, windows, but this appears not to be the case with spectrwm. An error, in my opinion and I am guessing that the behavior I report above is related to this.

**Comment by donaldcallen** [comment]
I should have mentioned in my previous post that I am running spectrwm on an up-to-date Arch Linux system.

**Comment by marcopeereboom** [comment]
@LordReg opinion?

**Comment by sholland1** [comment]
I am running into the same problem. I am unable to float windows at all on the max layout.

**Comment by marcopeereboom** [comment]
@LordReg ?

**Comment by osimplex** [comment]
Same here, cannot get a floating window on max layout. Latest version of spectrwm on Arch Linux

**Comment by qsmodo** [comment]
I'm also interested in this issue.

**Comment by qsmodo** [comment]
I'm making some progress in this issue. I'd be glad to hear some opinions on the items below, especially from maintainers, @LordReg and/or @marcopeereboom.

0. Is changing this desired at all? Right now it is only tagged with "question", so I'm unsure.
1. If yes, my goal would be to mirror Dwm's behavior as far as possible. Is that the ideal goal?
2. In contrast to Dwm, Spectrwm also has a full-screen window state. Should floats stay above full-screened windows as well? For one, transient windows do.
    - Aside: I don't grasp the purpose of full-screened windows in Spectrwm. They seem to be basically a maximized window + bar disabled, but additionally complicating is that shifting focus from them behaves differently depending on the layout. Given this, I wonder if Spectrwm really needs full-screen.

**Comment by psiho** [comment]
I'm having a same problem. 
I have all kinds of quick "popup" windows I like to quickly open and close (Wiki, Taskwarior,...) while working in maximized layout in my Nvim. WOuld really like to see a way to fix this

**Comment by qsmodo** [comment]
I remember trying to fix this last year, but it was very difficult and I could only come up with a partially working patch.

If you are willing to consider alternatives: This and the wrong focus after closing a dialog window (#384) eventually drove me away to Dwm, where neither bugs exist. Though there is the difference that vanilla Dwm does not center floats when mapped, the [alwayscenter patch](https://dwm.suckless.org/patches/alwayscenter/) flawlessly adds that behavior. And, AFAICT, most features of Spectrwm are available as patches there (except minimizing windows but even that one can be handled with a little script with `xdotool windowunmap`). So I really recommend giving it a try if the present issues bugs you.

**Comment by donaldcallen** [comment]
It certainly appears that window managers are not easy to do well. I'm typing this on an Arch Linux system running dwm for the reasons the previous comment cites and more. I've tried all the tilers and have found problems I can't live with with many of them -- spectrwm, bspwm and i3 among them. 

I don't agree with dwm's cart-before-the-horse priority of staying within 2000 lines of code, which I think led to the crazy model of adding patches to get what I think most of us consider the minimum set of capabilities. But the damned thing works flawlessly in my setup.
