### ISSUE TITLE
no keybindings work after first installation and mere copy of /etc/spectrwm.conf into home directory.

### ISSUE THREAD

**Issue by evanescente-ondine** [conformal/spectrwm#229]
Hello.
First impression is pretty bad,  no keybindings will work with default config. No reaction.
Just the mouse is usable to change window/pane/whatyouwant.
I compiled the last git version.
How can one use a standalone keybindings manager like sxhkdrc ? I am used to its syntax, which is simpler than spectrwm syntax (not the most readable for a non-hacker non-programmer like me).

I have last version of debian.

**Comment by LordReg** [comment]
Hi, are you by chance using multiple keyboard layouts or a non-us layout?

**Comment by evanescente-ondine** [comment]
Yeah, French layout.

**Comment by LordReg** [comment]
Please give this branch a try and let me know if it solves your issue: https://github.com/conformal/spectrwm/tree/grabfix

**Comment by evanescente-ondine** [comment]
Well, ok, if I can ?
```
mehdi@debian ~/spectrwm> make
Makefile:1: *** missing separator. Arrêt.
mehdi@debian ~/spectrwm> ./configure
fish: Unknown command './configure'
mehdi@debian ~/spectrwm> make
Makefile:1: *** missing separator. Arrêt.
```

**Comment by LordReg** [comment]
You can build the the branch the same as you did with the latest git master.  Just remember that on Linux, you need to run `make` from the `linux/` dir.  The top-level Makefile is for OpenBSD.

**Comment by evanescente-ondine** [comment]
thanks.
I didn't compile it myself. Debian's version is buggy.
lots of package like xcb-randr, xcb-xtest aren't seen, while it is installed. I don't know what to do in these cases?
Not like I want to look down on your work, but the compilation, just the compilation, isn't the easiest I've done so far ;-) I can't even find the exact version needed of the libraries, not in the files, nor in github, nor in https://github.com/conformal/spectrwm/wiki/Installation

**Comment by evanescente-ondine** [comment]
/usr/include/X11/Xft/Xft.h:39:22: fatal error: ft2build.h: Aucun fichier ou dossier de ce type
 #include <ft2build.h>
                      ^
compilation terminated.
Makefile:35 : la recette pour la cible « spectrwm.o » a échouée
make: *** [spectrwm.o] Erreur 1

xft.h includes the line "#include <ft2buil.d>"
That file is present in /usr/include/freetype2/.

Somewhere someone had the same problem with the program systray.
"According to the comment in line 20, that line is for BSD only. Bad pitfall, that. Should be solved by some automatic makefile creation.". So, somehow it might be because some stuff was written for bsd ?

**Comment by LordReg** [comment]
Just resolved the `fatal error: ft2build.h` issue when attempting to build on Ubuntu.  When building on Linux, you need to ensure that the `pkg-config` calls in the Makefile don't return any errors.

On Ubuntu, try installing these deps:
```
sudo apt-get install -y libx11-dev libx11-xcb-dev libxcursor-dev libxrandr-dev libxt-dev libxtst-dev libxcb1-dev libxcb-icccm4-dev libxcb-keysyms1-dev libxcb-randr0-dev libxcb-util0-dev libxcb-xtest0-dev libxft-dev libxcb-xfixes0-dev libfreetype6-dev libxcb-xinput-dev
```
If for some reason libxcb-xinput-dev is unavailable, you can disable the dependency by patching spectrwm.c and linux/Makefile:
```
sed -i 's/#if defined(__linux__) || defined(__FreeBSD__)/#if 0/' spectrwm.c;
sed -i 's/xcb-xinput //g' linux/Makefile;
```
