### ISSUE TITLE
About grabfix: /usr/include/xcb/xinput.h:4056:5: error: unknown type name ‘xcb_raw_generic_event_t’

### ISSUE THREAD

**Issue by evanescente-ondine** [conformal/spectrwm#232]
Tried to compile last grabfix version.

/usr/include/xcb/xinput.h:4056:5: error: unknown type name ‘xcb_raw_generic_event_t’
     xcb_raw_generic_event_t                      event_header;
     ^~~~~~~~~~~~~~~~~~~~~~~
Then "Makefile:37 : spectrwm.o has failed" (or something, was in French).
I had to install from the testing repositories libxcb-xinput-dev, but it went well. But it says this.

**Comment by LordReg** [comment]
`/usr/include/xcb/xcb.h` should include `xcb_raw_generic_event_t`.  Appears you have a version of libxcb that is older than your libxcb-xinput-dev.
