### ISSUE TITLE
Focus order: last recently focused

### ISSUE THREAD

**Issue by sgelb** [conformal/spectrwm#233]
I often open multiple windows, but do my actual work just in 2 of them, while the others show some documenation or output.

Using `focus_{next, prev}`, I can cycle through all the windows in the order they apperar on the screen. Is it possible to cycle through the windows ordered by last recently focused instead. This way, I could use the same command to switch back and forth between the same two windows regardless their position on the screen.

**Comment by marcopeereboom** [comment]
I wouldn't mind a patch for that with some key binding that makes sens

**Comment by marcopeereboom** [comment]
`M-S-A` comes to mind since it is similar to `M-a`.
