### ISSUE TITLE
Switching focus to window in different workspace loses focus target

### ISSUE THREAD

**Issue by mewa** [conformal/spectrwm#242]
**spectrwm version**
```
$ spectrwm
spectrwm: Welcome to spectrwm V3.2.0 Build: 3.2.0
```

**rofi version**
```
$ rofi -v
Version: 1.5.2
```

**Steps to reproduce:**
1. Open several windows in workspace X
2. Note which window is focused
3. Switch to another workspace
4. Switch to one of the (unfocused) windows inside workspace X by issuing
```
rofi -show window
```
5. Workspace is switched, but focus remains on previously focused window instead of selecting window selected by `rofi`

**Note:** This is most likely a `spectrwm` issue as focus is correctly handled when switching windows within the same workspace (i.e. selected window receives focus)

**Comment by marcopeereboom** [comment]
@LordReg can you look at this?
