### ISSUE TITLE
Incorrect border color

### ISSUE THREAD

**Issue by damage220** [conformal/spectrwm#245]
I would like to thank you for such great software. I was kind of surprise to see no flickering while creating/removing windows (and I have tried a lot of wm) as well as an ability to change number of stack areas in minimalist wm. However, I have found one issue which bother me. When I am setting `color_focus` to "rgb:38/139/210" I see brown instead of blue. Here is what [I have](https://i.imgur.com/yTQiG4E.png), and what it [should be](https://i.redd.it/kmf8k037pci21.png).

Distro: Arch Linux
spectrwm: V3.2.0 Build: 3.2.0
compositor: compton v5 (if it matters)

**Comment by LordReg** [comment]
Color values are hexadecimal, so try `color_focus = rgb:26/8b/d2`.

**Comment by damage220** [comment]
You are right. I saw in the top of the config file that colors are in hex, but then I saw rgb notation. A little bit confusing. I thought there is a bug because unfocus color looked almost the same as it should be, I even did not notice the difference. Sorry, my bad.
