### ISSUE TITLE
use startx, meta-m and iconify (and possibly others, but I don't know/never used them) don't work anymore

### ISSUE THREAD

**Issue by evanescente-ondine** [conformal/spectrwm#246]
Everything's in the title.
I'm pretty new to spectrwm. Iconify worked when starting with lightdm, now it's startx/.xinitrc, but no more iconify and several others maybe. For instance, even before I couldn't know what "raise" is to be used for, it seemed to do nothing, but it might be unrelated/me being an idiot.

spectrwm: Welcome to spectrwm V3.0.2 Build: 3.0.2

**Comment by LordReg** [comment]
Last few commits may fix this.  Try building/running the master branch.

**Comment by evanescente-ondine** [comment]
I don't know how to do this: I go to linux/, run 'make', and it says:
```
cc -std=c99 -Wmissing-prototypes -Wall -Wextra -Wshadow -Wno-uninitialized -g -fPIE  -I. -D_GNU_SOURCE -DSWM_LIB=\"/usr/local/lib/libswmhack.so.0.0\" -DSPECTRWM_BUILDSTR=\"e2c42a9de99788a12e110ec7bda83d151bd0d826\" -I/usr/include/freetype2  -c -o spectrwm.o ../spectrwm.c
In file included from ../spectrwm.c:84:0:
/usr/include/xcb/xinput.h:4056:5: error: unknown type name ‘xcb_raw_generic_event_t’
     xcb_raw_generic_event_t                      event_header;
     ^~~~~~~~~~~~~~~~~~~~~~~
Makefile: 37: the recipe for target "spectrwm.o" failed
make: *** [spectrwm.o] Error 1
```
I am said: libxcb-xinput-dev is already the newest version (1.13.1-2).

**Comment by LordReg** [comment]
`xcb_raw_generic_event_t` was added to `/usr/include/xcb/xcb.h` in libxcb 1.13, so make sure to have that installed/up-to-date too.  Btw, what distro are you using?

**Comment by evanescente-ondine** [comment]
The closest I can find are!
libxcb1/stable,stable,now 1.12-1
libxcb1-dev/stable,stable,now 1.12-1
I guess the numbers doni't fit with 1.13...

Linux debian 4.9.0-8-amd64 #1 SMP Debian 4.9.144-3.1 (2019-02-19) x86_64 GNU/Linux

**Comment by marcopeereboom** [comment]
This is a distro issue.
