### ISSUE TITLE
Example baraction.sh extracts incorrect `iostat -C` parameters

### ISSUE THREAD

**Issue by vext01** [conformal/spectrwm#249]
Hi,

In the example baraction script, we have:
```
_print_cpu() {
	typeset -R4 _1=${1} _2=${2} _3=${3} _4=${4} _5=${5}
	echo -n "CPU:${_1}% User${_2}% Nice${_3}% Sys${_4}% Int${_5}% Idle  "
}
```

But (at least on OpenBSD), the output of `iostat -C` is formatted like this:
```
     cpu
           us      % of CPU time in user mode
           ni      % of CPU time in user mode running niced processes
           sy      % of CPU time in system mode
           sp      % of CPU time spent spinning
           in      % of CPU time processing interrupts
           id      % of CPU time in idle mode
```

So, for example, we actually report the CPU time in interrupts as the idle time.

**Comment by LordReg** [comment]
Looks like `sp      % of CPU time spent spinning` was added in OpenBSD 6.4:
https://man.openbsd.org/OpenBSD-6.3/iostat.8
https://man.openbsd.org/OpenBSD-6.4/iostat.8
The included baraction script is purely an example.  It's left as an exercise for the user to come up with one that works on the target system.  I do think it makes sense to keep the baraction.sh example working on the latest OpenBSD.  @marcopeereboom What do you think?

**Comment by vext01** [comment]
> I do think it makes sense to keep the baraction.sh example working on the latest OpenBSD

Agreed.

**Comment by marcopeereboom** [comment]
Yes, please. @vext01 please send PR
