### ISSUE TITLE
Bar and transparency 

### ISSUE THREAD

**Issue by voidpin** [conformal/spectrwm#253]
Hello people,
Not so much of an issue, rather a couple of questions. Sorry, if this is the wrong place.
I've just moved one of my laptops from awesomewm to spectrwm, and I'm really enjoying the power and simplicity. Great work!
Two questions...
1) Is there a way to define the width of the bar, or is it set to be the same as the with of the screen?

2) How do I set-up alpha transparency? Say, I have bar_color[1] = rgb:74/2B/25 and want to have 60% opacity. I've tried as described here, https://gist.github.com/lopspower/03fb1cc0ac9f32ef38f4
But, it just changes the color. No transparency what so ever.

TIA

**Comment by marcopeereboom** [comment]
1. Width of screen.

2. No opacity support. For all intents and purposes, the screen behind the bar does not exist therefore opacity is moot.

**Comment by LordReg** [comment]
Actually, the bar windows are created to support transparency when the system supports it, but it's not currently possible to specify transparency.  I made an [opacity_hinting](/conformal/spectrwm/tree/opacity_hinting) branch a while ago that adds support for _NET_WM_WINDOW_OPACITY that might do what you want.

**Comment by voidpin** [comment]
Thanks, I'll look into it.

**Comment by marcopeereboom** [comment]
Since @LordReg wants to change this I'll reopen the issue.
