### ISSUE TITLE
open space between terminal window and window border

### ISSUE THREAD

**Issue by thomas3120** [conformal/spectrwm#255]
There is an open space between the terminal and the window border, showing the background or whatever was displayed in that area before the terminal was opened. I think it has to do with the terminal filling only the part that is a multiple of width / highth of a text row / column. I have tested with urxvt, lxterminal and xfce4-terminal on Arch and Raspbian.

**Comment by marcopeereboom** [comment]
This probably is a setting. Do you use `tile_gap` by any chance?

**Comment by thomas3120** [comment]
Yes, I do, but I just tried with tile_gap disabled and the issue is still there. 

See these screenshots:
https://ibb.co/gJQSrYZ
https://ibb.co/Qj6Vw2Y

**Comment by LordReg** [comment]
This appears to be related to applications expecting its window to be resized according to WM_SIZE_HINTS resize increment. spectrwm mostly ignores WM_SIZE_HINTS on tiled windows.

I am using urxvt on Arch and I don't experience the gap in your screenshot. Maybe it is a urxvt/Xdefaults setting?

**Comment by LordReg** [comment]
I still haven't reproduced this issue.  spectrwm merely resizes windows to fit the allocated space when tiling.  It's ultimately up to apps to deal with (re)drawing the contents of windows that don't get sized as they wish.  If it is still an issue, please reopen and we can try adding a quirk to at least resize window frames to fit WM_SIZE_HINTS resize increment... but the trade off would be odd gaps between tiled windows.
