### ISSUE TITLE
FontAwesome support in bar?

### ISSUE THREAD

**Issue by GasparVardanyan** [conformal/spectrwm#257]
The Spectrwm panel does not show FontAwesome glyphs, but i3bar shows.
In spectrwm.conf I have:
bar_font = DejaVu Sans Mono for Powerline, FontAwesome

**Comment by LordReg** [comment]
It is currently not possible to have multiple fonts in Xft mode combined and displayed simultaneously.  #243 makes it possible to specify an icon font and is in the process of being merged.

**Comment by LordReg** [comment]
This is now possible like this:
```
bar_font = DejaVu Sans Mono for Powerline
bar_font_pua = FontAwesome
```

**Comment by GasparVardanyan** [comment]
I have 3.2.0-1 version of spectrwm

I have this in my .spectrwm.conf:
```
bar_font = DejaVu Sans Mono
bar_font_pua = FontAwesome```

And have an exception: unknown option bar_font_pua in my bar.

How to solve it?

**Comment by LordReg** [comment]
bar_font_pua will be included in the next release.  Until then, you need to build spectrwm from git.

**Comment by GasparVardanyan** [comment]
Thank you )
