### ISSUE TITLE
spectrwm resets my browser's scorllbar everytime I switch to another workspace and return.

### ISSUE THREAD

**Issue by GasparVardanyan** [conformal/spectrwm#258]

**Comment by marcopeereboom** [comment]
@LordReg ?

**Comment by GasparVardanyan** [comment]
For example, I open qutebrowser, search for something in google or open some page in githube, scroll down, then switch to another workspace in spectrwm and return, and scroll in qutebrowser is reset.

**Comment by GasparVardanyan** [comment]
Sorry for bad English :)

**Comment by GasparVardanyan** [comment]
Also translates me to 1st desktop.

**Comment by LordReg** [comment]
> Also translates me to 1st desktop when I'm restarting spectrwm.

The resetting nature of *restart* is by design.

**Comment by LordReg** [comment]
It appears that this is the behavior of qutebrowser when it gets iconified/unmapped.  If you scroll using keyboard bindings, it is not an issue.

**Comment by GasparVardanyan** [comment]
I scroll using keyboard shortcuts, and just switch to another workspace and return, without restarting.

**Comment by LordReg** [comment]
I did more testing and was able to reproduce the issue using keyboard shortcuts.  Furthermore, I tested qutebrowser on other WMs and experienced the same behavior.  This appears to be an issue with how qutebrowser handles being minimized/unmapped.
