### ISSUE TITLE
spectrwm: can not open display

### ISSUE THREAD

**Issue by titanlock** [conformal/spectrwm#259]
Hello,

I am trying to install spectrwm on a freshly installed Arch Linux but cannot get it to run either through a DM, startx, or with just the command of spectrwm. I get the error that is in the title for spectrwm command but get no errors from the DM or startx. 

Can anyone please give me any insight on this issue?

Thanks

**Comment by LordReg** [comment]
If you installed the spectrwm or spectrwm-git package, `exec spectrwm` should be sufficient in your *~/.xinitrc* so that you can simply run `startx`.  You should also be able to select and run spectrwm from e.g. GDM without any issue.

`spectrwm: can not open display` would suggest X is not running.

**Comment by marcopeereboom** [comment]
I am going to close this issue. Please reopen if @LordReg diagnosis was incorrect.

**Comment by titanlock** [comment]
Thanks for the response, I at first thought that X was not starting as well but when I downloaded i3 it ran with no issues (I meant to mention this is the original post). If there are any specific logs you want me to post just let me know and I will get them for you.

**Comment by LordReg** [comment]
If you are still having issues, you can try running spectrwm manually from a minimal X session.
First `startx xterm` to run X with a single xterm window running (no WM, etc)..
Then, from xterm, run `spectrwm`.  If it still errors out, please post any errors here.  You can also try rebuilding spectrwm with (stderr) debug output by adding `CFLAGS="-g -O0 -DSWM_DEBUG"` to the PKGBUILD.

**Comment by jmxg** [comment]
I had this issue in Arch Linux and fixed it by setting bar_font in spectrwm.conf like so:
`bar_font = xos4 Terminus:pixelsize=14:antialias=true`
As per the installation page in the wiki.

**Comment by marcopeereboom** [comment]
Sounds like we need a better error. @LordReg we should not fatal when the bar can't be rendered; it should use the same mechanism of reporting in the bar that it is broken (like we do with config errors).

**Comment by LordReg** [comment]
@marcopeereboom If unable to load any fonts, are you suggesting we keep running without a bar and send errors to stdout?

**Comment by marcopeereboom** [comment]
No I am saying put the error in the bar like we do config errors.

**Comment by LordReg** [comment]
@marcopeereboom The reason for going fatal is because we were unable to load at least one font to print an error on the bar.  I think the font fallback mechanism just needs to be improved.

**Comment by marcopeereboom** [comment]
Oh. That makes sense. Is there an "ultimate fallback font" we can use?

**Comment by jerome-diver** [comment]
Just an idea... Maybe the use case scenario can be for spectrwm to:

- search fonts installed at start time
- create a list of these installed font
- then from a priority hard recorded list or hash of font to be acceptable (with priority), compare with and select the one 
- the one to write inside the default config file (~/.spectrwm.conf), 
- and comment the old one concerned line in the same file.

**Comment by marcopeereboom** [comment]
This already happens in the X server
