### ISSUE TITLE
Colors support in bar?

### ISSUE THREAD

**Issue by GasparVardanyan** [conformal/spectrwm#261]

**Comment by LordReg** [comment]
This is now possible on latest master branch.

**Comment by GasparVardanyan** [comment]
How can I print colored (hex) text in bar?
It works for i3: https://imgur.com/a/VWI8J6w

**Comment by LordReg** [comment]
See the man page in the latest commit.
Basically, you need to first define a comma-separated list of colors you want to use in bar_color/bar_font_color and then you can specify the color index in the bar by using `+@bg=n;` and/or `+@fg=n;`
If you want colors in `bar_action` to be parsed, then you must set `bar_action_expand = 1`.

**Comment by GasparVardanyan** [comment]
Thank you)
