### ISSUE TITLE
Small bug with listall workspaces

### ISSUE THREAD

**Issue by vaskark** [conformal/spectrwm#264]
A space is appearing (or, disappearing) after the colon for ws1 when switching workspaces:

[link](https://i.imgur.com/YapPqUS.gif)

spectrwm: V3.2.0 Build: 4aba2b2b6e29f29eb2ff680772d8be95710a5073
os: Ubuntu 19.04

Thanks. Great wm, btw.

**Comment by marcopeereboom** [comment]
guise?

**Comment by vaskark** [comment]
@marcopeereboom guise? I’m sorry I don’t understand.

**Comment by marcopeereboom** [comment]
I meant to get @LordReg on this thread.

**Comment by LordReg** [comment]
@vaskark what *bar_font* and *bar_font_pua* fonts are you using? I tried setting the workspace names as you did and was unable to reproduce the issue with this configuration:
```
bar_font_pua = Material Icons
bar_font = xos4 Terminus:pixelsize=16:antialias=true
```

**Comment by vaskark** [comment]
@LordReg Thanks for responding. I'm currently using this:

```
bar_font = Iosevka Custom:size=8:antialias=true
bar_font_pua = Typicons:size=7
```
But I've had the same result with Nerd Fonts and Icomoon. I'll try with Material Icon font and report back later.

**Comment by LordReg** [comment]
@vaskark I tried using your font configuration but I do not experience the issue in your original gif.
I'm wondering if it is related to the custom Iosevka you are using? I am using the 2.3.2 release from https://github.com/be5invis/Iosevka/releases .
