### ISSUE TITLE
vertical bar

### ISSUE THREAD

**Issue by voidpin** [conformal/spectrwm#265]
Hello once again.
Is it possible to have a vertical bar on the left of the screen instead of horizontal at the top or bottom?
I'd rather "waste" a few horizontal px than vertical ones.
This is all I have, `bar_format		= +3< +I:6 +3< %a %d %b +3< %R`
So, no need to rotate any outputs. `dmenu_run` might need a fix, though.
Anyway, before wasting to much time, I thought I'd ask.
TIA

Spectrwm 3.2.0 on NetBSD-9.0_Beta

**Comment by marcopeereboom** [comment]
The current bar does not do vertical rendering. You can try disabling it and use a stock bar and exclude the vertical area on the left. That way you can use whatever bar you like.

**Comment by voidpin** [comment]
Thanks!
I think I'll keep the default bar anyway, External bars show only on one workspace.

**Comment by marcopeereboom** [comment]
Well write up an issue for "on one workspace only". That should be fixed.
