### ISSUE TITLE
fails to build in cygwin

### ISSUE THREAD

**Issue by rjl6789** [conformal/spectrwm#268]
Hi, 

Pretty sure I've got all the dependancies, but it's failing to build (64bee8acfc875fee19db3ec2ae721635ce2b8ab4).  Is there anything special that needs to be done in addition the steps in the wiki - additional defines, env variable etc?  All help appreciated.  Really liking spectrwm and hoping to be able to use it on my work pc.

Step to reproduce:
- install cygwin , X and build dependancies
- git clone and cd into linux then make (as per wiki)
Errors are:
```
cc -std=c99 -Wmissing-prototypes -Wall -Wextra -Wshadow -Wno-uninitialized -g -fPIE  -I. -D_GNU_SOURCE -DSWM_LIB=\"/usr/local/lib/libswmhack.so.0.0\" -DSPECTRWM_BUILDSTR=\"64bee8acfc875fee19db3ec2ae721635ce2b8ab4\" -I/usr/include/freetype2 -I/usr/include/libpng16 -I/usr/include/uuid   -c -o spectrwm.o ../spectrwm.c
../spectrwm.c:7626:2: error: expected specifier-qualifier-list before ‘SIMPLEQ_ENTRY’
  SIMPLEQ_ENTRY(event) entry;
  ^~~~~~~~~~~~~
../spectrwm.c:7629:1: warning: return type defaults to ‘int’ [-Wimplicit-int]
 SIMPLEQ_HEAD(event_queue, event) events = SIMPLEQ_HEAD_INITIALIZER(events);
 ^~~~~~~~~~~~
../spectrwm.c:7629:1: warning: no previous prototype for ‘SIMPLEQ_HEAD’ [-Wmissing-prototypes]
../spectrwm.c: In function ‘SIMPLEQ_HEAD’:
../spectrwm.c:7629:34: error: expected declaration specifiers before ‘events’
 SIMPLEQ_HEAD(event_queue, event) events = SIMPLEQ_HEAD_INITIALIZER(events);
                                  ^~~~~~
../spectrwm.c:7633:1: error: expected ‘=’, ‘,’, ‘;’, ‘asm’ or ‘__attribute__’ before ‘{’ token
 {
 ^
../spectrwm.c:7652:1: error: expected ‘=’, ‘,’, ‘;’, ‘asm’ or ‘__attribute__’ before ‘{’ token
 {
 ^
../spectrwm.c:7663:1: error: expected ‘=’, ‘,’, ‘;’, ‘asm’ or ‘__attribute__’ before ‘{’ token
 {
 ^
../spectrwm.c:7683:1: error: expected ‘=’, ‘,’, ‘;’, ‘asm’ or ‘__attribute__’ before ‘{’ token
 {
 ^
../spectrwm.c:7695:1: error: expected ‘=’, ‘,’, ‘;’, ‘asm’ or ‘__attribute__’ before ‘{’ token
 {
 ^
../spectrwm.c:7920:1: error: expected ‘=’, ‘,’, ‘;’, ‘asm’ or ‘__attribute__’ before ‘{’ token
 {
 ^
../spectrwm.c:7954:1: error: expected ‘=’, ‘,’, ‘;’, ‘asm’ or ‘__attribute__’ before ‘{’ token
 {
 ^
../spectrwm.c:7984:1: error: expected ‘=’, ‘,’, ‘;’, ‘asm’ or ‘__attribute__’ before ‘{’ token
 {
 ^
../spectrwm.c:8163:1: error: expected ‘=’, ‘,’, ‘;’, ‘asm’ or ‘__attribute__’ before ‘{’ token
 {
 ^
../spectrwm.c:8204:1: error: parameter ‘actions’ is initialized
 } actions[FN_INVALID + 2] = {
```

**Comment by rjl6789** [comment]
I think SIMPLEQ_HEAD, SIMPLEQ_ENTRY are supposed to be part of _sys/queue.h_ - but they're missing on Cygwin.  I've trawled through previous versions and they were first introduced in 2.7.0.  I checked out 2.6.2 and this built fine (and runs ok as well after correcting some odd permissions on _/usr/local/lib/libswmhack.so.0.0_)

I've no idea how Cygwin can be made to play nice with the current version so if someone is able to make it work that would be great

**Comment by marcopeereboom** [comment]
Did you try building it in the `linux` directory?

@LordReg we may have to add queue.h to linux with an #ifdef guard.

**Comment by rjl6789** [comment]
Yes, that’s correct, I built it in the _linux_ directory ( I also hunted around to see if there was a specific Cygwin directory and/or branch - which there is not ) . 2.6.2 does compile but then this was a while back...Unfortunately I don’t have the knowledge or ability to determine whether ongoing Cygwin compatibility is feasible in terms of needed adjustments to the code. Cygwin does have have XFCE and GNOME and Openbox ... but whilst, that’s nice, They’re not now spectrwm.

**Comment by LordReg** [comment]
Fixed on master branch.

**Comment by rjl6789** [comment]
Hi,
Thanks @LordReg that's great.  I'm especially appreciative as:

- that didn't seem like a particularly simple fix (maybe it was for you!) 
- the user base for running spectrwm on Cygwin is probably just me (given no issues were raised since 2.7.0 when it would have broken.

There's an issue with the library when it get's installed to _/usr/local/lib/libswmhack.so.0.0_ needing to be 755 (as opposed to 644) for cygwin to open/run it - shall I open that as a separate issue or leave it here as it's all tied up with making cygwin work?

Thanks once again for your help and this superb wm

**Comment by LordReg** [comment]
@rjl6789 Linux doesn't require .so files to be executable but I see no reason to force libswmhack.so to 644 in the Makefile.  If a packager really wants 644, they can do so.  Fixed on the latest commit.

**Comment by marcopeereboom** [comment]
Yeah, we are not going to mess with the perms of a library. That is a packager's problem.
