### ISSUE TITLE
Can not start, no log file [resolved]

### ISSUE THREAD

**Issue by jerome-diver** [conformal/spectrwm#270]
Hi and thank you for this tiling window manager.
I'm unable to make this start and i don't know why, because i don't find any log file.
Where is the log file or is there any helper test script to test config ?

**Comment by mschilli87** [comment]
@jerome-diver: Can you share your version/OS/config?
My best guess is that you have some command bound (maybe by default) that does not exist.

**Comment by jerome-diver** [comment]
@mschilli87 hi, thank you for your quick answer/questions.
Yes sure, sorry for that:
- Archlinux
- spectrwm-3.2.0-1 (official maintened Archlinux version from repo community)
What is these command bound (maybe by default) who exist on this OS or other ones ? Do you have a tuto or an instructve list ?

**Comment by mschilli87** [comment]
Can you share `/etc/spectwm.conf`? I don't have Arch to test right now.

**Comment by mschilli87** [comment]
I checked [the package specification](https://git.archlinux.org/svntogit/community.git/tree/trunk/PKGBUILD?h=packages/spectrwm) and it seems Arch is using the [default config from github](https://github.com/conformal/spectrwm/blob/0e2ff742077b005a7892bb93226d87397fc9d9b7/spectrwm.conf): So check for `xlock`, `xterm` & `dmenu[_run]` on your system.

**Comment by jerome-diver** [comment]
@mschilli87 yes, [my gist pasted](https://gist.github.com/jerome-diver/d3dd1f6b81f155618336c6552975dd7b)
I usually run dmenu from i3wm, i use termite terminal emulator but can run xterm or urxvt, and yes, xlock can run also.
I think the problem should be other points, but without any log file.... i can't read the magic ball.
I also have two monitors (two screens then).

**Comment by mschilli87** [comment]
Another wild guess would be fonts though I'd be surprised if you wouldn't have termius on Arch.

**Comment by jerome-diver** [comment]
Is there a efficient way to just read an error back from anywhere  instead of turn around to find any luck ?

**Comment by mschilli87** [comment]
You could add `CFLAGS="-g -O0 -DSWM_DEBUG"` to the `PKGBUILD` to get errors printed to `stderr`.

**Comment by jerome-diver** [comment]
ok, thank you, i will try this method then.

**Comment by mschilli87** [comment]
@jerome-diver:
> for Termius, i can have if i install from AUR repo (not official one).

Does that mean you don't have it installed? Because you use it as font for the bar in your config. So you should either install the font or change the config to use one you have installed.

**Comment by jerome-diver** [comment]
wow... i followed the archwiki... i have to change this font and use one i have, sure.

**Comment by jerome-diver** [comment]
@mschilli87 hi, i do build spectrwm with debug cflags, but still have no idea how to fix the problem. Can you tell me more please ?

**Comment by mschilli87** [comment]
Do you get any error messages now?

**Comment by jerome-diver** [comment]
where to catch the message ?

**Comment by mschilli87** [comment]
`stderr` I think...

**Comment by jerome-diver** [comment]
yes, but if i run soectrwm command it doesn't works because i'm running from deepin WM. Error said it can not be run from an other WM open already. So... i was thinking to start from lightdm and read error from journalctl command, but nothing. So what i can do to get error message from lightdm start ?

**Comment by mschilli87** [comment]
Can you boot into runlevel 3 instead of 5, log in and just run `startx`? That would take out most layers in between and you'd get the error message directly on screen.

**Comment by jerome-diver** [comment]
ho yes... sure. So long time i not do that, i've forgot it. Thank you.

**Comment by jerome-diver** [comment]
@mschilli87 Ok, i get error back to startx just after xorg.log message (but on one line). Lucky i am to see the "range screen[2]..." problem origin.
I don't understand what this number mean, but change it to 1 fix the problem.
After that, when inside spectrwm, M-up/down change workspace, but not M-right/left.
I have to learn how to config it nicely and much more with 2 screen monitors plugged.
Thank you for your help.
