### ISSUE TITLE
A real tuto to be free to do things

### ISSUE THREAD

**Issue by jerome-diver** [conformal/spectrwm#271]
Hi, i'm trying spectrwm, usualy use i3wm.
I not find any complete tuto for many things i would like to do.
For example:

- how to change the clock format ?
- how to find any examples for quircks ?
- how to change background color ?
- how to switch tilling window (move inside tilling other windows) ?
- how to use a composit program to get transparency ?
- how to add nm-applet to bar ?
- and much more...

Hope to find any well documented articles about spectrwm (as well as i3wm be).

**Comment by marcopeereboom** [comment]
This is all described in the man page and sample config file

**Comment by jerome-diver** [comment]
No, it is not for:

-  change background color
- switch tilling window
- composit use for transparency
- nm-applet to add to bar
and many more.
