### ISSUE TITLE
Last window stuck on screen

### ISSUE THREAD

**Issue by KaiJan57** [conformal/spectrwm#277]
Closing windows is no problem usually, as others are resized to fill the screen. However, when the last window is closed, the screen is not cleared.

**Comment by LordReg** [comment]
It sounds like X was started without setting a background pixel on the root window and so the background is not being redrawn.  spectrwm does not touch the background so you may need to set it when X starts. For example, you can add this to your `~/.xprofile`:
`xsetroot -solid black`

**Comment by KaiJan57** [comment]
Thank you very much, that worked!
