### ISSUE TITLE
No xlock msg on the status bar

### ISSUE THREAD

**Issue by Franchium** [conformal/spectrwm#279]
Spectrwm v3.3.0 installation from sources

OS: Gentoo linux

There's a msg on the bar
![2019-12-21-164328_1366x768_scrot](https://user-images.githubusercontent.com/41231953/71307093-a76ee100-241b-11ea-8ea1-589046a418ed.png)

I don't want to install the xlock and I don't have any xlock program set in spectrwm config files.

Here is the output of xserver
![IMG_20191221_170402](https://user-images.githubusercontent.com/41231953/71307112-092f4b00-241c-11ea-8036-f982a5f50eb2.jpg)

`which: no xlock in (/usr/lib/llvm/8/bin:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin:/opt/bin)`

**Comment by voidpin** [comment]
Have a look at https://htmlpreview.github.io/?https://github.com/conformal/spectrwm/blob/master/spectrwm.html#PROGRAMS

I don't want `xlock` either, what I did was to replace it with `slock`
```
...
# Default Programs
program[lock]           = slock
program[term]           = xterm
...
```
Hope it helps.

**Comment by mschilli87** [comment]
@voidpin:

@Franchium wrote
> [...] I don't have any xlock program set in spectrwm config files.

**Comment by LordReg** [comment]
By design, `program[lock]` is defined and validated by default.  If the user chooses not to install `xlock`, the setting can be overridden/disabled.

From the man  page:
```
     For example, to override lock:
           program[lock] = xscreensaver-command -lock

     To unbind lock and prevent it from being validated:
           bind[] = MOD+Shift+Delete
```
