### ISSUE TITLE
moving float to different workspace hangs spectrwm

### ISSUE THREAD

**Issue by mvhulten** [conformal/spectrwm#283]
When I move a floating dialog window to another workspace, spectrwm becomes unresponsive.

For instance, start Atril on workspace 1 and press Ctrl+O for the dialog to open a file.  When I move this to workspace 2 (Alt+Shift+2), Atril and the dialog disappear from workspace 1.  spectrwm is now unusable: Alt+1, Alt+Shift+Enter and so on don't have any effect.  Even killing Atril (say, from a virtual console or via ssh) does not help: spectrwm does not in any visual way respond to my key pressing.  I need to kill spectrwm (or X).

Installed spectrwm 3.2.0 on Ubuntu 18.04 as a Guix package.

**Comment by marcopeereboom** [comment]
@LordReg

**Comment by mvhulten** [comment]
For completeness' sake, this also happens when I start spectrwm 3.2.0 without `~/.spectrwm.conf`, and also when I run spectrwm 3.1.0 from the Ubuntu package (same system).  On a different computer with the Guix System, using spectrwm 3.2.0, there are no issues (dialog floats can be moved fine—they take with them the underlying window, but that may be part of the design).
