### ISSUE TITLE
Assign apps to workspace with focus on and switch workspace

### ISSUE THREAD

**Issue by bazeeel** [conformal/spectrwm#287]
Its possible with spectrwm?
I tried with:
quirk[discord]   = WS[3]
discor app is going to workspace 3 but not focusing and not switching wspace.

**Comment by LordReg** [comment]
The `WS[n]` quirk only forces the matching window to workspace *n*.  To have spectrwm switch workspaces when you spawn the app, you can use an EWMH client.  For example, you could use wmctrl in a spawn script like this to switch to ws 3 and run discord:
```
#!/bin/sh
wmctrl -s 2
/usr/bin/discord
```

**Comment by bazeeel** [comment]
> The `WS[n]` quirk only forces the matching window to workspace _n_. To have spectrwm switch workspaces when you spawn the app, you can use an EWMH client. For example, you could use wmctrl in a spawn script like this to switch to ws 3 and run discord:
> 
> ```
> #!/bin/sh
> wmctrl -s 2
> /usr/bin/discord
> ```

Ok i try thanks for helping me again.
