### ISSUE TITLE
wayland support

### ISSUE THREAD

**Issue by bijang** [conformal/spectrwm#288]
any plan for wayland support?

**Comment by vale981** [comment]
This WM is rooted pretty deep in xorg.
I suspect, that a port to wayland would almost be another program in itself (which is why sway exists for i3).

**Comment by orbea** [comment]
Regardless of how its done, it would be nice to have some kind of wayland support before xorg becomes entirely unmaintained.

**Comment by marcopeereboom** [comment]
I am not foreseeing a switch to wayland any day soon. I also don't expect xcb to dissapear. These libraries don't die.

I will, however, take a patch or maybe we can do a full port. I am open to this if someone is willing to do the work.

**Comment by orbea** [comment]
@marcopeereboom I'm more concerned about the xserver, its already largely abandoned by upstream where only the bare minimum amount of work is put in. This is unlike the rest of the graphics stack which gets far more development time from upstream.

I suspect eventually the switch to wayland will be forced by one or more unfixed and ignored bugs and then eventually the complete deprecation of the software regardless if every niche program is ready for it...

**Comment by marcopeereboom** [comment]
We'll cross that bridge when we get there. While I share your concern I cannot see xserver being tossed any day soon. Way too much stuff uses it.

**Comment by bobhenkel** [comment]
I know this is closed, but now that it's almost 2025 and wayland has gained some more traction I'd like to see if the current take is still the same, that xserver still has enough life and isn't going anywhere to consider concrete efforts to get a rebirth of SpectrWM for wayland. I'd hold onto xserver for a long time personally just to keep using SpectrWM, I'd hate to lose SpectrWM when the day comes that the majority of distros move fully off xserver.  My take is it will still be a few years at the earliest, but I'm just guessing.
