### ISSUE TITLE
"region" option don't works

### ISSUE THREAD

**Issue by malyutinegor** [conformal/spectrwm#289]
Hello! I have this config:

```
border_width			= 0
region_padding			= 6
tile_gap				= 6
bar_enabled			= 0

keyboard_mapping 		= null

program[lock]			= slock
program[term]			= urxvt
program[browser]		= chromium

region				= screen[1]:1354x731+0+37

# KEYBINDINGS

modkey 				= Mod4

bind[term]			= MOD+Return

bind[cycle_layout]		= MOD+t
bind[flip_layout]		= MOD+Shift+backslash
bind[float_toggle]		= MOD+space
bind[float_toggle]		= MOD+Shift+space

bind[focus_next]		= MOD+Right
bind[focus_prev]		= MOD+Left
bind[swap_next]		= MOD+Shift+Right
bind[swap_prev]		= MOD+Shift+Left

bind[height_grow]		= MOD+Shift+equal
bind[height_shrink]		= MOD+Shift+minus
bind[width_grow]		= MOD+equal
bind[width_shrink]		= MOD+minus

bind[lock]			= MOD+Shift+Delete
bind[menu]			= MOD+d

bind[master_add]		= MOD+i
bind[master_del]		= MOD+p
bind[master_grow]		= MOD+l
bind[master_shrink]		= MOD+h

bind[maximize_toggle]	= MOD+m

bind[ws_1]			= MOD+1
bind[ws_2]			= MOD+2
bind[ws_3]			= MOD+3
bind[ws_4]			= MOD+4
bind[ws_5]			= MOD+5
bind[ws_6]			= MOD+6
bind[ws_7]			= MOD+7
bind[ws_8]			= MOD+8
bind[ws_9]			= MOD+9
bind[ws_10]			= MOD+0

bind[mvws_1]			= MOD+Shift+1
bind[mvws_2]			= MOD+Shift+2
bind[mvws_3]			= MOD+Shift+3
bind[mvws_4]			= MOD+Shift+4
bind[mvws_5]			= MOD+Shift+5
bind[mvws_6]			= MOD+Shift+6
bind[mvws_7]			= MOD+Shift+7
bind[mvws_8]			= MOD+Shift+8
bind[mvws_9]			= MOD+Shift+9
bind[mvws_10]			= MOD+Shift+0

bind[quit]			= MOD+Shift+e
bind[restart]			= MOD+Shift+r
bind[wind_kill]		= MOD+Shift+q

bind[browser]			= MOD+Shift+b
bind[bg]				= MOD+Shift+c
```

There's this `region` option in my config:
```
region				= screen[1]:1354x731+0+37
```

But it not works (windows still appear 6 pixels below top of screen). Actually, `region` option not even works if I set it, for example, to `100x100+0+0`. Can I fix it?

**Comment by bazeeel** [comment]
your region setting is 6 pixel below :D
1366x768+0+0 is the correct setting but i dont know what are you try to do? Example if i use polybar then i do this:
#reserved space for polybar
#region = screen[1]:1366x748+0+20
but with the default bar dont need the region screen setting

**Comment by malyutinegor** [comment]
@bazeeel, I'm just trying to get 37 pixels (+ 6 pixels) of empty space on top of my monitor. But `region` option isn't working, no matter what to I set it

**Comment by bazeeel** [comment]
[[url=https://ibb.co/19762HY][img]https://i.ibb.co/19762HY/2020-02-16-120458-1680x1050-scrot.png[/img][/url]]

**Comment by malyutinegor** [comment]
@bazeeel Exactly

**Comment by bazeeel** [comment]
> @bazeeel Exactly

Then you see my config for screen region is at bottom on the picture :)

**Comment by malyutinegor** [comment]
@bazeeel It just not works. I appended `region = screen[1]:1366x700+0+37` to the bottom of my config but everything stays the same

**Comment by bazeeel** [comment]
> @bazeeel It just not works. I appended `region = screen[1]:1366x700+0+37` to the bottom of my config but everything stays the same

hmm....weird on my  end works.

**Comment by malyutinegor** [comment]
@bazeeel Spectrwm starts with bar 37 pixels below the top of screen, and after ~1 seconds bar jumps to the top of monitor. It's strange

**Comment by bazeeel** [comment]
ok then bar_bottom = 0

**Comment by malyutinegor** [comment]
@bazeeel Something like `option bar_bottom not exists`

**Comment by bazeeel** [comment]
> @bazeeel Something like `option bar_bottom not exists`

sorry i missed ....bar_at_bottom = 0

**Comment by malyutinegor** [comment]
@bazeeel Basically, nothing changes :D

**Comment by bazeeel** [comment]
> @bazeeel Basically, nothing changes :D

hmm..maybe some option not set in your config.........im new to spectrwm too

**Comment by LordReg** [comment]
> @bazeeel Spectrwm starts with bar 37 pixels below the top of screen, and after ~1 seconds bar jumps to the top of monitor. It's strange
spectrwm uses the `region` option when it starts, but when screen configuration is changed (i.e.  RRScreenChangeNotify event), it will automatically recreate the regions based on the new screen configuration.
Appears RandR screen configuration is being changed after ~1s?  Do you run xrandr at startup?

**Comment by malyutinegor** [comment]
@LordReg 

> Do you run xrandr at startup?

Nope, I'm not doing anything like that at startup :D

**Comment by LordReg** [comment]
@malyutinegor what os/video driver/monitor configuration do you use?  Do you have multiple monitors connected?

**Comment by malyutinegor** [comment]
@LordReg 

> Do you have multiple monitors connected?

No, I have only one monitor

**Comment by LordReg** [comment]
@malyutinegor 
> No, I have only one monitor

Perhaps your gpu/monitor has some delay changing modes during startup and that is triggering a late screenchange event?  I suggest to try adding a `sleep 5` before `exec spectrwm` in your startup script and, if that works, try reducing the sleep value.

**Comment by malyutinegor** [comment]
@LordReg Oh, I tried it and it really worked! Thanks! :)
