### ISSUE TITLE
sxhkd support

### ISSUE THREAD

**Issue by bazeeel** [conformal/spectrwm#290]
Please add correct sxhkd support :
example:
# keybindigs
keyboard_mapping = ~/.spectrwm-keys.conf
can we add?
# keybindigs
keyboard_mapping = ~/.config/sxhkd/sxhkdrc
or can we disable the built in keys?

**Comment by LordReg** [comment]
As stated in the man page, `keyboard_mapping` clears the built in keys and loads the bindings from the specified file.

**Comment by bazeeel** [comment]
> As stated in the man page, `keyboard_mapping` clears the built in keys and loads the bindings from the specified file.

yes correct but it gives  error on the bar .........the lines are line 1 unknown option super

**Comment by LordReg** [comment]
spectrwm will try to open the file you specify for keyboard_mapping.  If you want to clear the default bindings without using a separate file for bindings, then I suggest:
`keyboard_mapping = /dev/null`
