### ISSUE TITLE
Can't start spectrwm under Manjaro xfce

### ISSUE THREAD

**Issue by ratnose** [conformal/spectrwm#298]
How to reproduce, install latest Manjaro using xfce.
Install spectrwm via pamac-manager using spectrwm-git version.
Logut, choose Spectrwm then I cannot login.

**Comment by mschilli87** [comment]
Not a Majaro user, so just a wild guess:

Can you lokk at your `~/.spectrwm.conf` (or `/etc/spectrwm.conf` if you don't have a `~/.spectrwm.conf`) and check if it references any default programs that where not installed as dependecies by your package manager? One potential candidate would be

```
program[lock] = xlock
```

also the `term` or `menu` entries could make `spectrwm` attempt to run into an 'unknow command' error upon startup.

**Comment by ratnose** [comment]
I installed it from the Arch repo logged out and tried to start in, add my password screen goes black and then I get to the login again.

So to there are no suck files, do I need to do some copy those to the right pos first?

**Comment by pnotz17** [comment]
im having the exact same problem but im on vanilla arch i thought it was my xauthority so i deleted it then compared DTs conf with the default one cp it to home hen i logged in once and im still trying to debug it by looking at journalctl errors and x session erros

**Comment by LordReg** [comment]
The default *bar_font* Xlib font set may be failing to load.  Try setting *bar_font* to an Xft font in your spectrwm.conf:
```
bar_font = xos4 Terminus:pixelsize=14:antialias=true
```

**Comment by e3172** [comment]
I get the same issue.
When I try to log in via lightdm there is a black screen then it logs me back into the lightdm screen.

**Comment by Cardoso1994** [comment]
I have exactly the same issue.
try to log with lightdm, got a black screen and then I'm back to lightdm.
My system is Arcolinuxd

**Comment by mschilli87** [comment]
@ratnose, @pnotz17, @e3172, @Cardoso1994: Did you check you config files for missing default tools like I suggested, and veryfied you have set a valid bar font as pointed out by @LordReg? https://github.com/conformal/spectrwm/issues/299 describes another issue that could cause a crash: Naming a non-existent workspace. This was resolved by reading the logs. Did you check your logs? Anything in there?

**Comment by ratnose** [comment]
> @ratnose, @pnotz17, @e3172, @Cardoso1994: Did you check you config files for missing default tools like I suggested, and veryfied you have set a valid bar font as pointed out by @LordReg? #299 describes another issue that could cause a crash: Naming a non-existent workspace. This was resolved by reading the logs. Did you check your logs? Anything in there?
I do copy the config file from etc to .myown, the ones that comes with the installation does only contain keyboards shortcuts nothing else. Where do I get hold of a more complete one?

**Comment by LordReg** [comment]
@ratnose The full example conf should have been installed to `/etc/spectrwm.conf`.  The files installed under `/etc/spectrwm/` are example `keyboard_mapping` files.

**Comment by ratnose** [comment]
@LordReg That was one thing I tried the first time it wasnt working.
In /etc/spectrwm/ I got:
spectrwm_cz.conf
spectrwm_es.conf
spectrwm_fr_ch.conf
spectrwm_fr.conf
spectrwm_us.conf

Those only contains keybindings nothing else, so I tried to use DTs config file with loads more inside it, and with that one it actually starts but I get 19 exceptions but that is totally expected.

**Comment by mschilli87** [comment]
@ratnose: So you don't have any `/etc/spectrwm.conf` file, *i.e.* `ls /etc/spectrwm.conf` returns a file not found error? Note this file is **not** in the `/etc/spectrwm/` directory, but in its parent directory `/etc/` with the file name `spectrwm.conf`. Also note that if you copy it to your `$HOME` directory, you need to rename it to `.spectrwm.conf` (note the leading dot).

**Comment by ratnose** [comment]
@mschilli87 Oh! I missed that! I do have a spectrwm.conf in etc, I have now moved it to my $HOME with the leading dot. Fingers crossed, lets hope it works now. :D

**Comment by mschilli87** [comment]
@ratnose: Did you make sure you have all programs and fonts mentioned in that default config installed on your system as suggested above? If so, do you get any error message in you systems log after your return back to the login screen?

**Comment by ratnose** [comment]
@mschilli87 Just because... I installed Arch and spectrwm and started it there... same thing there. Login - screen black - login. That is after coping the conf files to the right places.
This is were I leace spectrwm.
Thanks for all the help.

**Comment by LordReg** [comment]
spectrwm prints error messages to stderr.  When encountering issues starting from a display manager, try starting spectrwm directly from the console to capture any error output to a log file.
For example:
```
startx spectrwm > ~/spectrwm.log 2>&1
```
