### ISSUE TITLE
how to install on opensuse tumbleweed?

### ISSUE THREAD

**Issue by najamsk** [conformal/spectrwm#300]
i search google and dont want to install from community edition version by some random dude. i have clone repo there are no installation instructions how to install from srouce.

**Comment by mschilli87** [comment]
Check out Gentoo's ebuild (packages are compiled from source in Gentoo):
https://gitweb.gentoo.org/repo/gentoo.git/tree/x11-wm/spectrwm/spectrwm-3.3.0.ebuild
looks like a simple make && make install` does the job.

**Comment by spandanji** [comment]
Since you are running OpenSuse Tumbleweed, why not take a look at OBS? 
https://build.opensuse.org/package/show/home:rmboggs/spectrwm
The builds do pass

**Comment by marcopeereboom** [comment]
Should be:
```
git clone https://github.com/conformal/spectrwm.git
cd spectrwm/linux
make
make install
```
