### ISSUE TITLE
clock_enabled = 0 still shows clock

### ISSUE THREAD

**Issue by desdic** [conformal/spectrwm#301]
Version: spectrwm 3.3.0-1

```sh
# grep clock_enabled .spectrwm.conf
clock_enabled       = 0
```

Shows both the clock set in my bar but also the default clock format

**Comment by mschilli87** [comment]
What is your `bar_format`?

From the `man` page (emphasize mine):

> Set the bar format string, **overriding** clock_format and **all of the enabled options**.  The format is passed through strftime(3) before being used.

So as long as you use `%a %b %d` or something along these lines in there (in addition to  the `+A` for your `baraction.sh` output), I'd say this behaviour is expected (though potentially confusing). :wink:

**Comment by desdic** [comment]
Sorry did not read that part. Thanks for getting back to me so fast .. closing due to error 40
