### ISSUE TITLE
question, it is possible to resize tiled windows ?

### ISSUE THREAD

**Issue by doums** [conformal/spectrwm#302]
Hi,

I just installed spectrwm and starting to play with it. So far I didn't find anything about resizing windows other than floating ones.
For example, in my workflow, I regularly need to resize a tiled window by dragging one of its border (width or height, depending of the current layout), like in i3.

It's possible in spectrwm ?

**Comment by LordReg** [comment]
It is currently not possible to fine-tune the geometry of tiled windows.  You can grow/shrink the size of the master area with `master_grow/master_shrink`, adjust the number of windows in the master area with `master_add/master_del` and adjust the number of columns in the stacking area with `stack_inc/stack_dec`.  Other than that, spectrwm automatically tiles windows to fill the region.

**Comment by doums** [comment]
Ok that was what I expected, thank you. Other question, what is the corresponding string to bind the exclamation mark `!` ?
