### ISSUE TITLE
[feature request] Ability to clear the keymap

### ISSUE THREAD

**Issue by ideasman42** [conformal/spectrwm#303]
Currently if you want to bind all keys from scratch, there is no convenient way to do this.

Would it be acceptable to have a way to clear all keys, eg:

`bind[] = *`

Or, there could be a special command for this.

`bind_none = true`.

This is quite simple to implement, I can submit a patch for either.

**Comment by LordReg** [comment]
The `keyboard_mapping` option already does this.

**Comment by ideasman42** [comment]
The down-side of this is you need to make a blank file.

**Comment by ideasman42** [comment]
The down-side of this is you need to make a blank file.

**Comment by LordReg** [comment]
You could use `keyboard_mapping = /dev/null` if you don't want to have a separate file for your binds.

**Comment by marcopeereboom** [comment]
Maybe we should document this?

**Comment by LordReg** [comment]
> Maybe we should document this?

done
