### ISSUE TITLE
question: Where can I find log from my action bar ?

### ISSUE THREAD

**Issue by doums** [conformal/spectrwm#305]
Hi!

I'm currently coding my action bar in Rust.
The standard output of the binary bar is displayed in the bar. What about the standard error ?
Is there a place where spectrwm puts std error traces from my binary bar ? I tried to search using some grep but without success.

If I'm right, I think spectrwm just simply discard/ignore any standard error output from the action bar binary/script. That is the case ?

(I know that I can implement my own error log system)

**Comment by LordReg** [comment]
spectrwm spawns bar_action and reads stdout from that process.  Any stderr output from bar_action ends up in the stderr output of spectrwm.
For example, one way to log stderr from spectrwm (including bar_action):
```startx spectrwm > ~/spectrwm.log 2>&1```

**Comment by doums** [comment]
Ok thank!
