### ISSUE TITLE
How to refresh bar on request?

### ISSUE THREAD

**Issue by DonPiotr** [conformal/spectrwm#309]
Hi!
I would like to set sleep time of action bar script for something like 1 minute.
And then by command line, other script, key binding ...
1) force action script to restart
or
2) put into bar a new content while waiting for action script auto-refresh.

**Comment by LordReg** [comment]
What you describe can be done with a custom bar_action script.  The bar action output is updated when the bar_action script outputs a new line.

For example, you can make a bar_action script that monitors changes to a file.  When you write to the file with a separate command/script, the bar_action script could print a new line.
