### ISSUE TITLE
Wrong keyboard layout detection at startup

### ISSUE THREAD

**Issue by qlem** [conformal/spectrwm#310]
Hi,

First, I would like to thank for this great window manager, great job. I came from i3 that is a great wm too but I definitely prefer the approach of spectrwm.

I have an issue at the startup. The detection of the layout keyboard is wrong. I have a french keyboard (AZERTY) but spectrwm detect and load QWERTY layout. So, after each startup of spectrwm, I need to restart spectrwm for load the appropriate layout.

```
$> echo $LANG
fr_FR.UTF-8
```
```
$> cat /etc/X11/xorg.conf.d/00-keyboard.conf
Section "InputClass"
	Identifier "system-keyboard"
	MatchIsKeyboard "on"
	Option "XkbLayout" "fr"
	Option "XkbModel" "pc"
EndSection
```
```
$> cat ~/.config/spectrwm/spectrwm.conf
...
keyboard_mapping = /dev/null
bind[term] = MOD+Return
...
```
```
$> cat .xinitrc
...
exec spectrwm
```
Any help is welcome.

**Comment by historical-theology** [comment]
Until a developer or veteran responds, this should at least help. Use the autorun feature in .spectrwm.conf:

`autorun = ws[1]:setxkbmap [your map]` 

e.g.

`autorun = ws[1]:setxkbmap fr`

See https://linux.die.net/man/1/setxkbmap for the setxkbmap man page. It is highly customizable.

**Comment by qlem** [comment]
Sorry, I forgot to say that only key bindings from spectrwm are wrongly mapped at the startup.

**Comment by LordReg** [comment]
spectrwm binds to keycodes resolved from the keymap when it starts.
Try this to see what keymap spectrwm sees when X starts:
```startx /usr/bin/xmodmap -pke > ~/keymap.txt```

**Comment by qlem** [comment]
Ok so, it seems that the keymap is set to QWERTY layout when X starts. I put `xmodmap -pke > ~/keymap.txt` just before `exec spectrwm` in my .xinitrc file.
```
...
$> cat keymap.txt
keycode  24 = q Q q Q
keycode  25 = w W w W
keycode  26 = e E e E
keycode  27 = r R r R
keycode  28 = t T t T
keycode  29 = y Y y Y
keycode  30 = u U u U
keycode  31 = i I i I
keycode  32 = o O o O
keycode  33 = p P p P
...
```

But if I run `xmodmap -pke` once spectrwm is start, the keymap is good !
```
$> xmodmap -pke
...
keycode  24 = a A a A ae AE ae
keycode  25 = z Z z Z guillemotleft less guillemotleft
keycode  26 = e E e E EuroSign cent EuroSign
keycode  27 = r R r R paragraph registered paragraph
keycode  28 = t T t T tslash Tslash tslash
keycode  29 = y Y y Y leftarrow yen leftarrow
keycode  30 = u U u U downarrow uparrow downarrow
keycode  31 = i I i I rightarrow idotless rightarrow
keycode  32 = o O o O oslash Oslash oslash
keycode  33 = p P p P thorn THORN thorn
...
```

That explains why when I restart spectrwm, the keybinds is good. Any idea why while X starts the keymap is not yet set ?

**Comment by qlem** [comment]
After investigation it seems that when spectrwm starts from X, it binds the keys too early. X has not yet had time to configure the keyboard layout that spectrwm has already bind the keys.

**Comment by LordReg** [comment]
It turns out the XkbLayout option itself does not update the *core keyboard mapping* used by *xkb-unaware* X clients at startup.  Since spectrwm is *xkb-unaware*, the *xkb keyboard mapping* -> *core keyboard mapping* translation must be done before spectrwm starts.  One way to do this is to run setxkbmap before starting spectrwm.  For example, in .xinitrc:
```
setxkbmap fr
exec spectrwm
```

**Comment by qlem** [comment]
```
...
setxkbmap fr
exec spectrwm
```
The solution works fine. Thank you.
