### ISSUE TITLE
add Fake Fullscreen if possible

### ISSUE THREAD

**Issue by Danilopereira82** [conformal/spectrwm#313]
i don't know if its possible to use this right now
but if not i ask if you could add this feature to spectrwm

**Comment by mschilli87** [comment]
What is fake fullscreen? Can you give an example?

**Comment by Danilopereira82** [comment]
> Reopen with an explanation.

https://youtu.be/DJg7CtOxhIw
here in 05:50

**Comment by mschilli87** [comment]
direct link: https://youtu.be/DJg7CtOxhIw?t=350
Basically, make an application think the its tile is the screen size, such that 'fullscreening' it makes it use up the whole tile but not the full (actual) screen. Not sure how to do this in spectrwm as I don't have a use case personally (don't use YouTube).

**Comment by Danilopereira82** [comment]
i don't want this for youtube only

**Comment by marcopeereboom** [comment]
I don't see the need but if someone sends a PR it could work.
