### ISSUE TITLE
Does it work on the latest Manjaro?

### ISSUE THREAD

**Issue by alexeygrant** [conformal/spectrwm#314]
I've installed spectrwm in the fresh install of Manjaro using community repo (packager: Kyle Keen keenerd@gmail.com).
When I switch my desktop manager to spectrwm and enter my password my desktop immediately freezes and I only can restart my computer using reset button.

**Comment by LordReg** [comment]
spectrwm may be exiting with an error.  It prints errors to stderr so it should show up in your logs.  Is your system completely frozen where you can't even switch to terminal (ctrl+alt+f1, etc)?
The default bar_font setting uses the X11 core font system which may be failing to load.  You can try configuring spectrwm to use the Xft font system instead.  For example:
~/.spectrwm.conf
```
bar_font = xos4 Terminus:pixelsize=14:antialias=true
```

**Comment by alexeygrant** [comment]
Thanks @LordReg, 
I am able switch to a terminal (ctrl-alt-f2, etc). Where are the spectrwm logs are located?
I've added the bar_font setting and now it at least gives me an error in the bar (from memory wording could be slightly different) : "Exceptions found: 1. Exception 1: xterm cannot be found". 
What does that mean?

**Comment by LordReg** [comment]
spectrwm doesn't write to a log file itself, it outputs to stderr, which should end up in the logs of your DM in this case.

The default bindings require some default spawn program entries (see PROGRAMS in the man page.)  The default terminal for the *term* action is xterm and it appears you don't have it installed.  To eliminate that startup exception, you can set ```program[term]``` to a terminal of your choice in the conf or install the ```xterm``` package.

**Comment by alexeygrant** [comment]
Thanks, @LordReg. Replacing _xterm_ with _konsole_ for _program[term]_ finally fixed the problem.
