### ISSUE TITLE
Markup sequence in baraction.sh output is displayed as text in the bar.

### ISSUE THREAD

**Issue by alexeygrant** [conformal/spectrwm#317]
If I add a markup sequence to the baraction.sh script output, e.g. "+@fg=1;" it is displayed as it is, and bar foreground colour is not affected at all. Why is that?

**Comment by mschilli87** [comment]
From `man spectrwm`:

> `bar_action_expand`
>         Process `bar_format` character sequences in `bar_action` output; default is 0.

**Comment by alexeygrant** [comment]
Thank you @mschilli87, I've missed that bit from the docos.
