### ISSUE TITLE
Where should I put my code to set up background image?

### ISSUE THREAD

**Issue by alexeygrant** [conformal/spectrwm#318]
I use `feh` to set up a background image, but I'm not sure what's the best location to put it.
It works if I add it to the `baraction.sh`, but it doesn't feel right. Thank you in advance.

**Comment by mschilli87** [comment]
I used to do it in `~/.xinitrc` which worked well in combination with startx, and via lightdm when using that. I guess it could also be done within spectrwm via an `autorun` command by I never actually used that method myself.

**Comment by alexeygrant** [comment]
I'm using KDE Plasma Manjaro (Archlinux) where I installed spectrwm.
Adding my code to ~/.xinitrc doesn't seem to have any effect. 
How do I know if `startx` is used? I select a window manager (spectrwm or Plasma) on the GUI login page.

**Comment by alexeygrant** [comment]
Creating ~/.xprofile and adding my code there worked.
