### ISSUE TITLE
Could not find dmenu_run

### ISSUE THREAD

**Issue by sampaio23** [conformal/spectrwm#319]
Hi!
I'm sure I have dmenu installed (as well as dmenu_run), but everytime I execute spectrwm, I see an exception telling me that it could not find dmenu_run. Nevertheless, if I press M+p, it spawns dmenu_run perfectly.

I'm running spectrwm 3.3.0 at Arch Linux, installed via pacman.
Best regards!

**Comment by LordReg** [comment]
spectrwm uses ```which``` to validate spawn programs.  It isn't explicitly listed as a dependency in the spectrwm package on Arch.  If you haven't installed all of the ```core``` repository, perhaps it didn't get installed in the dependency chain.

**Comment by sampaio23** [comment]
Hi!
I installed `which` and now it works fine! Maybe this should be listed as a dependency, because for some reason it did not get installed, I don't know why.
Thanks a lot!

**Comment by marcopeereboom** [comment]
Reopened by accident.
