### ISSUE TITLE
German Keyboard Layout: Keybinding key names for ^ character does not work

### ISSUE THREAD

**Issue by dornbirndevelops** [conformal/spectrwm#320]
Hello all together!

On German (Austrian) keyboard layout the key for the `^` character is located above the tab key. My intention is to use this key to switch back and forth between the last two used workspaces. I've tried the following configurations:

```
bind[ws_prior] = MOD+^
bind[ws_prior] = MOD+asciicircum
bind[ws_prior] = MOD+dead_circumflex
```

The last two key names are identified by the `xev` command suggested by the `man spectrwm`, but none of the combinations work.

Can you guys tell me what I'm doing wrong?
Also, what method can i use to set the keyboard layout for spectrwm properly?

**Comment by LordReg** [comment]
The issue is most likely the same as https://github.com/conformal/spectrwm/issues/310#issuecomment-621158723.

**Comment by LordReg** [comment]
If `setxkbmap de` in .xinitrc didn't fix the issue, please reopen.
