### ISSUE TITLE
A Dual Monitor Setup - how many screens do I have?

### ISSUE THREAD

**Issue by alexeygrant** [conformal/spectrwm#321]
I have a dual-monitor setup. Here is the **xrandr** output:
```
❯ xrandr --listactivemonitors
Monitors: 2
 0: +HDMI-0 2560/597x1440/336+0+0  HDMI-0
 1: +DP-2 3440/800x1440/340+2560+0  DP-2
```
I can switch between different workspaces, but the bar status displays number '1' for both monitors (+N in bar_format): 1:1, 1:2,... 1:10... etc...
Is it expected? What exactly are 'screens' are in spectrwm?

**Comment by LordReg** [comment]
*screen* in spectrwm refers to the X *screen* (which would include all monitors.)  spectrwm automatically creates a separate *region* for each monitor.  If you would like to display the region index your bar, you can use +R in your spectrwm.conf ```bar_format```.
