### ISSUE TITLE
iconify dmenu with option

### ISSUE THREAD

**Issue by kristoferus75** [conformal/spectrwm#322]
Hi !

The uniconified windows are shown with dmenu ! My dmenu ist patched and i want that dmenu ist started with an option -l 20  to see all iconified windows at a glance !

How can i achive this ?

kind regards 

kristoferus75

**Comment by LordReg** [comment]
Hi @kristoferus75,

From the *PROGRAMS* section of the man page, the default *program* entry for *search* is:
```
dmenu $dmenu_bottom -i -fn $bar_font -nb $bar_color -nf $bar_font_color -sb $bar_color_selected -sf $bar_font_color_selected
```
uniconify, search_win and search_workspace all use program[search]

You can override in your spectrwm.conf like this:
```
program[search] = dmenu $dmenu_bottom -i -fn $bar_font -nb $bar_color -nf $bar_font_color -sb $bar_color_selected -sf $bar_font_color_selected -l 20
```

**Comment by kristoferus75** [comment]
Hi !

Thanks it works :-)
Now i see all iconify windows of that one workspace !
Is it also possible to see all iconify windows from all workspaces and jump then to this selected ?

kind regards

kristoiferus75

**Comment by LordReg** [comment]
There is a fix for ```wmctrl -a``` in master branch newer than 3.3.0.  Tested your script and it works.

Also, if you want to list just iconified windows, you could use ```xprop -id <winid> WM_STATE``` in your script to check each window for ```window state: Iconic```.

**Comment by kristoferus75** [comment]
Thanks ! Hmm i see the iconic window with my script but if want uniconfy it (open) idoesnt work !

 pacman -Qi spectrwm 
Name                     : spectrwm
Version                  : 3.3.0-1

**Comment by LordReg** [comment]
The fix is not included in 3.3.0.  You could try [spectrwm-git](https://aur.archlinux.org/packages/spectrwm-git) from AUR or wait for 3.4.0.

**Comment by kristoferus75** [comment]
ok i understand no problem i can wait :-)

Thanks a lot for your help  !!!!!

kind regards

kristoferus75

**Comment by desdic** [comment]
I sort of have an issue that might be the same but not sure. 

```
yay -Qi spectrwm-git
Name            : spectrwm-git
Version         : 20200514-1
Description     : A minimalistic dynamic tiling window manager that tries to stay out of the way.
Architecture    : x86_64
URL             : http://www.spectrwm.org
Licenses        : custom:ISC
Groups          : None
Provides        : scrotwm  spectrwm
Depends On      : dmenu  xcb-util  xcb-util-wm  xcb-util-keysyms  libxrandr  libxft  libxcursor  terminus-font
Optional Deps   : scrot: screenshots [installed]
                  xlockmore: screenlocking
Required By     : None
Optional For    : None
Conflicts With  : scrotwm  spectrwm
Replaces        : scrotwm
Installed Size  : 253,88 KiB
Packager        : Unknown Packager
Build Date      : 2020-05-14T17:52:21 CEST
Install Date    : 2020-05-14T17:52:38 CEST
Install Reason  : Explicitly installed
Install Script  : No
Validated By    : None
```


Keybinding to bind[uniconify] = MOD+Shift+w .. if I iconify a  windows it disappears as expected and I can see in the top bar that its been iconified. But pressing Mod+Shift+w does nothing. I have dmenu and dmenu_run but they are never invoked (Tried to replace them with a dummy to see if they where called but no. 

If I create a term with a sleep 300, iconify it and then gets teh WM_STATE its this:

xprop -id 0x02a00005 WM_STATE
WM_STATE(WM_STATE):
                window state: Iconic
                icon window: 0x0
And for some reason mumble gets auto iconified after a while and then I'm unable to retrieve it.

Is this the same problem or is mine something else ?

**Comment by LordReg** [comment]
@desdic Are you using an alternate keyboard layout? If you run `xev` what is the output for KeyPress event when you press the *w* key?  What about MOD+Shift+w?

**Comment by LordReg** [comment]
@kristoferus75 is your issue with *uniconify* solved with spectrwm-git?

**Comment by desdic** [comment]
> @desdic Are you using an alternate keyboard layout? If you run `xev` what is the output for KeyPress event when you press the _w_ key? What about MOD+Shift+w?

No its a standard US layout

**Comment by desdic** [comment]
> @kristoferus75 is your issue with _uniconify_ solved with spectrwm-git?

No I'm running the spectrwm-git now and I cannot uniconify

**Comment by kristoferus75** [comment]
@desdic 
Yes i have no problems now -> all work as excpected !

**Comment by desdic** [comment]
> @desdic
> Yes i have no problems now -> all work as excpected !

Can I see your config just in case that I did something wrong ?

**Comment by kristoferus75** [comment]
@desdic
bind[iconify]           = MOD+Control+w

**Comment by LordReg** [comment]
@desdic The default `bar_font` setting currently doesn't work on Arch.
At minimum, you need a spectrwm.conf with a `bar_font` setting like:
```
bar_font = xos4 Terminus:pixelsize=14:antialias=true
```

**Comment by kristoferus75** [comment]
@desdic
Perhaps this help you :
`autorun                 = ws[1]:setxkbmap -layout de`

**Comment by desdic** [comment]
Figured out my problem .. when I have 
bar_font            = Mononoki Nerd Font:size=9, JoyPixels:size=9, FontAwesome:size=9, icomoon-feather:size=9, Ubuntu Condensed:size=9, Noto Color Emoji:size=9

spectrwm fails silently and never calls dmenu for the uiconify. With the suggested font 'xos4 Terminus' dmenu presents what looks like a windows ID

**Comment by LordReg** [comment]
@desdic the issue you describe appears to be the same as #223.
Basically, `bar_font` is passed to dmenu via the $bar_font variable.  If dmenu is unable to load `-fn "$bar_font"`, then uniconify will fail.
You can test with
```
echo "Test1 Test2" | dmenu -fn "xos4 Terminus:pixelsize=14:antialias=true"
echo "Test1 Test2" | dmenu -fn "Mononoki Nerd Font:size=9, JoyPixels:size=9, FontAwesome:size=9, icomoon-feather:size=9, Ubuntu Condensed:size=9, Noto Color Emoji:size=9"
```
A workaround (until #233 is solved) is to modify the dmenu spawns to use a specific font rather than the $bar_font variable.
For example:
```
program[menu] = dmenu $dmenu_bottom -fn "xos4 Terminus:pixelsize=14:antialias=true" -nb $bar_color -nf $bar_font_color -sb $bar_color_selected -sf $bar_font_color_selected
program[search] = dmenu $dmenu_bottom -i -fn "xos4 Terminus:pixelsize=14:antialias=true" -nb $bar_color -nf $bar_font_color -sb $bar_color_selected -sf $bar_font_color_selected
program[name_workspace] = dmenu $dmenu_bottom -p -fn "xos4 Terminus:pixelsize=14:antialias=true" -nb $bar_color -nf $bar_font_color -sb $bar_color_selected -sf $bar_font_color_selected
```

Closing this issue now since the original issue is already solved ;)
