### ISSUE TITLE
mousepad issue

### ISSUE THREAD

**Issue by kristoferus75** [conformal/spectrwm#324]
Hi !

I now use  the git version of spectrwm but it doesnt matter ! (it is the same behaviour also on the normal version)

If i open mousepad in ws 1 and then i switch to ws 4 and want also open mousepad -> mousepad will not open in ws 4 it opens a second time on ws 1

If i do this with urxvt or other program  it open in ws 4 as expected 

Thanks !

kind regards

kristoferus

**Comment by LordReg** [comment]
when a process creates multiple windows, spectrwm tries to assign them to the same workspace. ```mousepad``` uses a single process when opening multiple windows.

The solution is to either disable the *daemon* behavior of ```mousepad``` with ```mousepad --disable-server``` or define a quirk in spectrwm.conf to disable the behavior for its windows:
```
quirk[Mousepad] = IGNORESPAWNWS
```

**Comment by kristoferus75** [comment]
Perfect Thanks :-)
