### ISSUE TITLE
dmenu silently changes focused window

### ISSUE THREAD

**Issue by terdimitri** [conformal/spectrwm#327]
If dmenu does not spawn a new window (MOD+p then escape, or other instances of dmenu), the focused window changes silently to a given window. Repeated attempts of launching dmenu consistently change focus to the same window. 
The border signifying the focused window does not change from the recently unfocused window, and the root window's _NET_ACTIVE_WINDOW property does not change. Any subsequent keyboard input will be sent to the new focused widow.

**Comment by marcopeereboom** [comment]
I am not following this. @LordReg?

**Comment by LordReg** [comment]
@marcopeereboom When the pointer is over an unfocused window and `MOD+p` is pressed, and then aborted with an `esc`, the window under the pointer would get input focus.  Fixed now.
