### ISSUE TITLE
tabbed layout

### ISSUE THREAD

**Issue by kristoferus75** [conformal/spectrwm#328]
Hi !

Is a tabbed layout possible or in plan ?

thanks

kristoferus

**Comment by LordReg** [comment]
I'm not exactly sure what you mean by 'tabbed layout'?

**Comment by kristoferus75** [comment]
for example like this:

http://hackage.haskell.org/package/xmonad-contrib-0.7/docs/XMonad-Layout-Tabbed.html

**Comment by LordReg** [comment]
Besides the buttons, doesn't fullscreen layout already do this?

**Comment by kristoferus75** [comment]
Sorry i dont know what you mean with besides the buttons ?

If press a key so  that an window should be fullscreen i see only this windows on the whole screen but with the tabbed layout i see tabs and can easy swiich between the windows and all are in full screen mode

**Comment by LordReg** [comment]
I mean the fullscreen layout you can access with the `cycle_layout` action (default MOD-space).

**Comment by kristoferus75** [comment]
bind[cycle_layout]      = MOD+space

Yes you have right :-) but without the tabbs :-(

**Comment by kristoferus75** [comment]
is it possible to change the sequence of the cycle -> so that fullscreen is on second place ?

**Comment by kristoferus75** [comment]
can i cahnge the

**Comment by kristoferus75** [comment]
if i press this button [cycle_layout]-> is it possible to switch between the maximized windows so the is visable (always the  next windows if i press ths unkonwn button)

**Comment by LordReg** [comment]
> if i press this button [cycle_layout]-> is it possible to switch between the maximized windows so the is visable (always the next windows if i press ths unkonwn button)

Could you explain in more detail? I don't understand.

**Comment by kristoferus75** [comment]
if i press cycle layout so that all windows on this screen are in monocole mode -> i want to press a key combination so that i focus to the next maximize window to the next etc on that screen

**Comment by LordReg** [comment]
You can focus on the next/prev window with: `focus_next` and `focus_prev` as with the other layouts :)

**Comment by kristoferus75** [comment]
Thanks :-)

**Comment by marcopeereboom** [comment]
We are not going to add a clickable widget. I am sure that can be done externally with EWMH.

I am going to close this for now.

**Comment by pinpox** [comment]
> We are not going to add a clickable widget. I am sure that can be done externally with EWMH.
> 
> I am going to close this for now.

Could you expand on this, how? I'm interested in a tabbed layout aswell, similar to what i3 does. It just the fullscreen, but with tabs showing the applications that are "below" the currently focused, something like this:
![image](https://user-images.githubusercontent.com/1719781/86793077-62cf2e00-c06b-11ea-9211-6ba47fb3b6d4.png)

**Comment by marcopeereboom** [comment]
This completely defeats the purpose of saving real estate. In addition, this can be accomplished with fullscreen and with iconifying. I honestly don't see the point of tabs at all.

**Comment by pinpox** [comment]
How would I do this with iconifying?

I don't use the actual "tiling" most of the time, just fullscreen windows. Tabs might take away a few Pixels of real estate but I can instantly see which apps are where.

08.07.2020 19:31:58 Marco Peereboom <notifications@github.com>:
