### ISSUE TITLE
How to address Ctrl and Fn key in .spectrwm.conf?

### ISSUE THREAD

**Issue by sevi-kun** [conformal/spectrwm#332]
Hey
I'm hacking on my .spectrwm.conf right now.
So I want some keybindings with Ctrl and even better with my Fn key.
How do I addres those?
Thanks for help
Béla

**Comment by LordReg** [comment]
If you run `xev` and it displays a KeyPress event when you press the desired key, you can bind the key using the displayed keysym.

For example:
```
KeyPress event, serial 40, synthetic NO, window 0x3600001,
    root 0x6ca, subw 0x0, time 81660483, (384,-199), root:(1652,519),
    state 0x0, keycode 37 (keysym 0xffe3, Control_L), same_screen YES,
    XLookupString gives 0 bytes: 
    XmbLookupString gives 0 bytes: 
    XFilterEvent returns: False
```
bind[program] = Control_L

**Comment by sevi-kun** [comment]
Thanks for your reply. It helped me a lot. Most keybindings do work now. But I still have a problem with my Control_L key:
I don't know why (and where to start search..), but my Control_L doesn't recognize it when I hold the key. So Keybindings like Ctrl+R (or whatever) do not work. (Actually they work, when I press and hold R and then press Ctrl.. but thats bad in most situations)

Thanks for your help again.

Béla

**Comment by sevi-kun** [comment]
> Thanks for your reply. It helped me a lot. Most keybindings do work now. But I still have a problem with my Control_L key:
> I don't know why (and where to start search..), but my Control_L doesn't recognize it when I hold the key. So Keybindings like Ctrl+R (or whatever) do not work. (Actually they work, when I press and hold R and then press Ctrl.. but thats bad in most situations)
> 
> Thanks for your help again.
> 
> Béla
> 
> Ps.: For others that have problems. There is actually a help page I havn't noticed when I started this issue:
> [/wiki/Tutorial](https://github.com/conformal/spectrwm/wiki/Tutorial)

**Comment by sevi-kun** [comment]
> Thanks for your reply. It helped me a lot. Most keybindings do work now. But I still have a problem with my Control_L key:
> I don't know why (and where to start search..), but my Control_L doesn't recognize it when I hold the key. So Keybindings like Ctrl+R (or whatever) do not work. (Actually they work, when I press and hold R and then press Ctrl.. but thats bad in most situations)
> 
> Thanks for your help again.
> 
> Béla
> 
> Ps.: For others that have problems. There is actually a help page I havn't noticed when I started this issue:
> [/wiki/Tutorial](https://github.com/conformal/spectrwm/wiki/Tutorial)

I resolved the Issue myself.. Sometimes its pretty simple..
Thought I still don't know why _Control_L_ doesn't work as expected, Just _Control_ (without __L_) works just fine.

Because all my problems are resolved, I will close the issue now.

Béla
