### ISSUE TITLE
Entire screen flickering when switching layout to fullscreen

### ISSUE THREAD

**Issue by Fraemwerk** [conformal/spectrwm#333]
If I have focus mode set to follow and use mod+space to switch to full screen mode my whole screen starts to flicker between all the open windows. The only way to stop it is to move my mouse to the top of the screen so the follow focus can actually choose a screen, which is incredibly inconvenient. Is there any way to fix this other than changing the focus mode to manual? It's been a bug for a couple of years now

**Comment by marcopeereboom** [comment]
What applications cause this for you?

**Comment by LordReg** [comment]
I confirm this is an issue and I am in the process of a fix.

**Comment by nick-owens-eero** [comment]
i have had this issue even on master with 995db3a73150f0da6d016891160abbe03be7bd09. it is reproducible with two xterms on ubuntu 18.04.4.

**Comment by marcopeereboom** [comment]
@LordReg this going to be done before upcoming release?

**Comment by LordReg** [comment]
Fixed in master.

**Comment by kinderferraz** [comment]
hii, sorry to bother, but I'm experiencing this issue on Ubuntu 18.04. When I checked what version is installed it returns
```
$ spectrwm --version           
spectrwm: Welcome to spectrwm V3.1.0 Build: 3.1.0
spectrwm: another window manager is currently running
```
Unfortunately I cannot upgrade the system as I'm on a company computer, and I've already tried updating the indexes. Is there a ppa with the latest version?
