### ISSUE TITLE
When do you plan to make a new release ?

### ISSUE THREAD

**Issue by doums** [conformal/spectrwm#334]
Hi,

When do you plan to make a new release ?
So that Archlinux/Debian/Ubuntu packages can be updated.

If not, where I can find instruction to install from sources ?

**Comment by jfchevrette** [comment]
For Archlinux, you could build from git using https://aur.archlinux.org/packages/spectrwm-git

I too am keen on seeing a new release to include changes since Dec. 2019. Is there a list of tasks/issues that need to be fixed so a new release can be cut?

**Comment by marcopeereboom** [comment]
We can roll a minor release if that's helpful. @LordReg I'll go through the issues and see what we can add. Let me know what you think as well, please.

**Comment by doums** [comment]
Ok cool, #307

**Comment by orbea** [comment]
@marcopeereboom This probably can be closed? There are some additional fixes on top of master already though.

**Comment by LordReg** [comment]
Just had a new release https://github.com/conformal/spectrwm/releases/tag/SPECTRWM_3_4_0
but master branch is usually the best option.
