### ISSUE TITLE
Automatic formatting.

### ISSUE THREAD

**Issue by vale981** [conformal/spectrwm#337]
Would you be open to using an automated formatter like clang-format to make it easier to contribute?

A configuration, that wouldn't be too disruptive is:
```
---
BasedOnStyle: LLVM
AlignConsecutiveMacros: 'true'
AlignConsecutiveAssignments: 'true'
AlignConsecutiveDeclarations: 'true'
AlwaysBreakAfterReturnType: AllDefinitions
DerivePointerAlignment: 'false'
IndentWidth: '8'
PointerAlignment: Right
SortIncludes: 'false'
SpaceAfterCStyleCast: 'false'
UseTab: Always

...
```

**Comment by marcopeereboom** [comment]
We use this style:
https://man.openbsd.org/style

I love style enforcers but have never found one that does BSD KNF right. If you have one please reopen.

**Comment by vale981** [comment]
https://blog.netbsd.org/tnf/entry/gsoc_2019_report_adding_netbsd1
It seems that there has been some work done to support the knf style.

**Comment by marcopeereboom** [comment]
Doesn't look quite right tbh.
