### ISSUE TITLE
reload does not work; spectrwm exits and X ends

### ISSUE THREAD

**Issue by nick-owens-eero** [conformal/spectrwm#340]
somewhere in 40b4e0d..995db3a config reloading has broken. sending either HUP to spectrwm or mod-shift-q now makes spectrwm exit rather than reload, and my X session ends.

**Comment by LordReg** [comment]
If you are using the default bindings, `restart` is bound to `MOD+q`.  `MOD+Shift+q` is `quit`.

SIGHUP restart fixed on latest commit: 9b734061adb3744863625ec621e2a808eb65f998

**Comment by nick-owens-eero** [comment]
my apologies, i fat fingered the hotkey. i was more concerned about HUP. thanks for the quick fix!
