### ISSUE TITLE
Spectrwm freezes when loading baraction.sh

### ISSUE THREAD

**Issue by luimu64** [conformal/spectrwm#341]
I made very simple baraction.sh which works fine when I run it from terminal but freezes the wm everytime I try to load it. 

Here is my baraction.sh:
#!/bin/fish

function battery
        upower -i /org/freedesktop/UPower/devices/battery_BAT1 | grep "percentage"
end

set SLEEP_SEC 5  # set bar_delay = 5 in /etc/spectrwm.conf

#loops forever outputting a line every SLEEP_SEC secs
while true
        battery
        sleep $SLEEP_SEC
end

I can run the example baraction.sh without problems so its probably because of fish.

**Comment by muemmel** [comment]
Old issue, but in case anyone runs into the same problem. Wrap your fish function call inside a standard shell script, i.e.:

#!/bin/sh
fish -c [name_of_fish_function] &

The ampersand will stop it from freezing.

**Comment by Snazzyham** [comment]
Would this also be an issue if `fish` is my default shell but I use `#!/bin/bash` in my `baraction.sh`? 

I'm having an issue with docker in my baraction, as referenced here #421
