### ISSUE TITLE
Formatting bar_format sequences

### ISSUE THREAD

**Issue by p-kolacz** [conformal/spectrwm#343]
Is it possible to format output of bar format sequences like workspace list indicator (+L) or stacking algorithm (+S)? Or maybe is it possible to access this information from bar action script? I want to change stacking symbol to some unicode icon, change current workspace indicator from asterisk to background color, etc.

If it's not possible, can I access this information from another bar like polybar or lemonbar?

**Comment by ronniedroid** [comment]
I have submitted a PR that makes extreme modifications to the workspace and stacking algorithm indicators. 

https://github.com/conformal/spectrwm/pull/360#issue-437569559
