### ISSUE TITLE
A configuration of ratio for master and stack layouts

### ISSUE THREAD

**Issue by osimplex** [conformal/spectrwm#346]
There isn't a option for define the ratio of area master will use by default on region, nor in pixels or percentage. Also an option for ratio change on `master_grow` and `master_shrink` bindings.

There is the `layout` option, but `master_grow` step cannot be defined.

**Comment by cdelnooz** [comment]
From the man-page:
> layout
>         Select layout to use at start-of-day.  Defined in the format
>         ws[idx]:master_grow:master_add:stack_inc:always_raise:stack_mode, 
>         e.g. ws[2]:-4:0:1:0:horizontal sets  worskspace 2 to the horizontal stack mode,
>         shrinks the master area by 4 ticks and adds one window to the  stack, 
>         while maintaining default floating window behavior.

Whilst this defines it on the region and doesn't let you specify the _size_ of a `master-grow` step, it does allow you to create initial ratios between master and stack per workspace by specifying the _number_ of `master-grow` steps. Below a snip from my personal spectrwm.conf, which gives me a roughly 2:1 ratio between master and stack width on the first two workspaces. 

> \# Customize workspace layout at start
> layout          = ws[1]:4:0:0:0:vertical
> layout          = ws[2]:4:0:0:0:vertical

Key bindings for master-grow and master-shrink are again in the man-page: `M-h` for `master-shrink`, `M-l` for `master_grow`. All works out of the box.

**Comment by osimplex** [comment]
> From the man-page:

I've readed the manual, and this option doesn't fill my requirement: set the dafault ratio for all `ws`. And the default ratio isn't `0.5`. The `layout` directive also doesn't fill my requirements, because: first: no precision; second: `This setting is not retained at restart.`

The correct title for this issue can be `A configuration of ratio for all master and stack layout, by percentage`, because, the current mechanism not provides precision.

**Comment by osimplex** [comment]
Can I open a new issue with `A configuration of ratio for all master and stack layout, by percentage`, because the percentage is much important in the issue.
