### ISSUE TITLE
Polybar is quiting.

### ISSUE THREAD

**Issue by shahid777-py** [conformal/spectrwm#351]
Polybar is quiting as usually I close every window with the close hotkey..it unusual than any other wm I used i3 and bspwm it doesn't happen there but here it's closing and polybar is also recognized as a window because polybar also having the same window border color.

**Comment by ipetepete** [comment]
It sounds like you might need to add this to your polybar config:

`override-redirect = true`

Check the documentation for more deail: https://github.com/polybar/polybar/wiki/Configuration#bar-settings

**Comment by marcopeereboom** [comment]
Please reopen if not fixed with provided suggestion.
