### ISSUE TITLE
Lib32 application (wine) - ERROR: ld.so: object '/usr/lib/libswmhack.so.0.0' from LD_PRELOAD cannot be preloaded  (wrong ELF class: ELFCLASS64): ignored

### ISSUE THREAD

**Issue by lich-tex** [conformal/spectrwm#352]
libswmhack.so.0.0 does not work for multilib/lib32 applications and thus it does not follow quirks.

I have this issue on arch where the main wine binary is only lib32 and I am not aware of the possiblity of making libswmhack both 32bit and 64bit :).

**Comment by marcopeereboom** [comment]
We'll take a PR.

Who still uses x86 though?

**Comment by lich-tex** [comment]
Wine uses it, and generally older applications are usually distributed with x86.

**Comment by mssx86** [comment]
building a 32 bit x86 elf copy of `spectrwm` and preloading the 32 bit `libswmhack.so` from a running 64 bit `spectrwm` instance causes a `wrong ELF class: ELFCLASS32` error instead.

i do believe that it is a problem on the `wine` side of the spectrum.

**Comment by LordReg** [comment]
If you build a 32-bit libswmhack.so, you can use it for specific apps by setting LD_PRELOAD in the env of the application.

You can make a wrapper script or use `sh -c` in the spawn command like this:
```
program[example] = sh -c "LD_PRELOAD=/path/to/32bit/libswmhack.so wine program.exe"
```

**Comment by mssx86** [comment]
> If you build a 32-bit libswmhack.so, you can use it for specific apps by setting LD_PRELOAD in the env of the application.

i have mentioned doing exactly that in the previous message to yours. doing that works with 32 bit `xeyes` and probably most of the other 32 bit binaries but `wine` still produces the error i described up there.

**Comment by LordReg** [comment]
The errors appear to be from wine executing some 64-bit commands with the inherited env.  Despite the errors, it does work.  You can check if libswmhack loaded by running `xprop _SWM_PID` in a terminal and clicking on the app window.  If `_SWM_PID(STRING)` exists, it worked.

**Comment by lich-tex** [comment]
Thanks, @LordReg for real debugging solution :). I checked it and it does work, but for some reason wine in the newer version does not set WM_CLASS to Wine...

There is no reason to use 32 bit libswmhack as I have checked and the PID is set in both cases. The issue was resulting from a change in WM_CLASS for wine.

Nonetheless, completely unrelated issue so I am closing it.
