### ISSUE TITLE
All Jetbrains IDE are almost unusable

### ISSUE THREAD

**Issue by doums** [conformal/spectrwm#353]
Hi,

I use Jetbrains IDE a lot for my all days work. Since I started to use spectrwm I quickly noticed that all Jetbrains IDE (IntelliJ, Clion, Webstorm..) are full glitched and almost unusable, and all share the same problems:
For example, after the IDE started, **inside** the IDE window all resize actions (click on a pan border, maintain and move it), eg: resizing editor splits, resizing the file tree width etc.., are impossible. When I mouse hover a border (I don't talk about the main borders of the "main window" of the IDE) that I can normally move, the mouse cursor normally change to indicate this possible action. In spectrwm it's not. Even when I mouse hover the editor. The default cursor remains the same.
When I click on a button that normaly open a drop-down menu just behind the button itself, the menu spawns elsewhere and away from the button. And as soon I release the mouse button the menu closes.

The only "workaround" I find to fix temporarily these problems, is to press my spectrwm keybinding to move just a little the main window of the IDE (and make it floating in the same time). After that the focus, cursor, menus etc seems to works "normally".  But as soon I toggle off the floating window mode or fullscreen it etc.., the problems come back. So it is not viable.

I have no idea where the problems come from, if it's spectrwm or Jetbrains side. But what I can tell is that I have no problem, on the same machine, under xfce4 session for example.
If it turns out that it comes from Jetbrains I will open an issue on their bug tracker.

But for the moment I would like to have your opinion.

**Comment by marcopeereboom** [comment]
Java is always full of surprises.

**Comment by LordReg** [comment]
The issue is with Java itself not complying with ICCCM 4.1.5/4.2.3 except when it detects the WM is in its special list of WMs.

spectrwm already has a workaround for the issue when it detects a window is java, but JetBrains  windows don't use the typical "sun-awt" in WM_CLASS.  They use "jetbrains-".

Added detection for jetbrains windows on master branch so that they get treated as java.  The commit should resolve the issues you describe.

**Comment by LordReg** [comment]
Please reopen if you still have issues on master branch.

**Comment by doums** [comment]
I just tested a little, and for now the bugs seems fixed. Thank you !
