### ISSUE TITLE
EWMH - window to last ws after both ws_next_move and ws_prev_move 

### ISSUE THREAD

**Issue by osimplex** [conformal/spectrwm#356]
I've opened the issue #350, [fixed](https://github.com/conformal/spectrwm/commit/d508239bf5762148f1e64ca424afc6456f1c965b).

Now there is another problem. When the window goes to another `ws`, somethig is missing: update some kind of current `ws` for EWMH (I'm not an expert). Because when I fire the command `wmctrl -R "Mozilla Firefox"` after `ws_next_move` or `ws_prev_move`, my browser goes to the last `ws` that I was before `ws_next_move` or `ws_prev_move`.

**Comment by LordReg** [comment]
Fixed: 93f80b8f97e80be3deb94b0bcedddf237dc2b3b2
