### ISSUE TITLE
Pop-up windows don't get autofocus

### ISSUE THREAD

**Issue by voidpin** [conformal/spectrwm#358]
Don't know if this was intended or not but, its surely a behavior change/bug.

**OS: NetBSD-9.0_STABLE using pkgsrc-current
WM: spectrwm-3.4.0**
(I've simply bumped the package version, re-built the wm and pushed the changes to the repository)

In spectrwm-3.3.0 the pop-up window in the picture automatically received focus and the keyboard arrows could be used to change the selection.
In spectrwm-3.4.0 this is no longer the case. Not only the pop-up window no longer receives focus but also, and most annoyingly, I can no longer use the arrow keys to shift through the options. This means I need to use the mouse to actually select say "Discard changes".

![2020-06-21-071220_1366x768_scrot](https://user-images.githubusercontent.com/35956139/85217350-34293600-b390-11ea-986c-078434b5d278.png)

**Comment by LordReg** [comment]
Which `focus_mode` are you using and what editor?

**Comment by voidpin** [comment]
@LordReg 
`focus_mode=    default`
The editor is `featherpad`, version 0.14.2. Its a Qt5 editor compiled against `Qt-5.15.0` using `qt5ct`, version 1.0 for theming.

**Comment by LordReg** [comment]
Issue is fixed on master branch and will be included in the upcoming patch release. 3.4.0 included a lot of fixes that were bound to have a few side effects. Thanks for the clear report.

**Comment by voidpin** [comment]
Thanks for the quick response.
Just have to wait for a point release :)
I'll package and push an update for NetBSD as soon as its out.

**Comment by voidpin** [comment]
@LordReg It works perfectly, thanks!
Instead of waiting for the point release, I've created a package for myself that builds directly from the bleeding-edge master branch, https://mail-index.netbsd.org/pkgsrc-wip-changes/2020/06/22/msg016796.html
