### ISSUE TITLE
Focus goes to last window in stack instead of last focused floating window after closing a rofi menu

### ISSUE THREAD

**Issue by osimplex** [conformal/spectrwm#359]
I have some windows tiled and one floating (`_NET_WM_STATE_ABOVE`) that have the focus, then open `rofi`, after closing rofi with `esc`, the focus goes to last window in the list of tiled windows of the `ws`, the last window of stack area, instead of return to the actual last focused window, the floating window.

When I have only tiled windows, independently of the focused window before opening my `rofi` menu, the focus returns to the last focused window after closing rofi.

**Arch Linux**: version 3.4.0

**Comment by LordReg** [comment]
What is your `focus_mode`?

**Comment by osimplex** [comment]
My `focus_mode` is `manual`, and `focus_close` `previous`.
This behavior doesn't occured in version 3.3.0.

**Comment by LordReg** [comment]
I was able to reproduce this issue with the pointer over a window frame.  Fixed on master branch.
