### ISSUE TITLE
bind [layout_max] does not work.

### ISSUE THREAD

**Issue by work000station-git** [conformal/spectrwm#363]
Hey.
After updating spectrwm (archlinux), bind [layout_max] does not work. If you use this, get the exit from spectrwm.

**Comment by LordReg** [comment]
This is an issue with the Arch community/spectrwm 3.4.0-2 package. It attempts to disable max layout which causes the crash you experienced.
I suggest trying the `AUR/spectrwm-git` package to run with the latest fixes/improvements.   If you have issues running the latest, then please report them here or irc.

**Comment by work000station-git** [comment]
Thanks, AUR / spectrwm-git works great.
