### ISSUE TITLE
pcmanfm/spacefm open on wrong workspace

### ISSUE THREAD

**Issue by internet-police** [conformal/spectrwm#365]
heya,
lets say i have pcmanfm open on workspace 1
then go to workspace 2, and open another pcmanfm
it will open a second instance on workspace 1 and not 2
same goes for spacefm
any idea?

**Comment by LordReg** [comment]
Hi, this can happen when a program reuses an existing process to create the new window.  spectrwm tries to keep new windows of of the same process together. The solution is to either disable *daemon mode* in the program or add a quirk to your spectrwm.conf to have windows that match the quirk always open in the current workspace.
For example:
```
quirk[Pcmanfm] = IGNORESPAWNWS
quirk[Spacefm] =  IGNORESPAWNWS
```
see the man page for details on quirks.
