### ISSUE TITLE
Few questions regarding spectrwm.

### ISSUE THREAD

**Issue by Joe23232** [conformal/spectrwm#366]
Hi I am considering to use `spectrwm` however I have a few questions regarding `spectrwm`.

* Does it use the xcb library or the xlib?
* Like `bspwm`, am I able to use any custom scripts written in any language? If so, can I change it in a high level sort of fassion?
* Am I able to customise the windows like this:
![Full window](https://user-images.githubusercontent.com/34926497/85980493-db0f7100-ba25-11ea-9e7e-4e6bdf01c022.png)
* Is this a manual tiling window manager or automatic? If it is manual then is there some script or something available where I can configure it as an automatic tiling window manager?

**Comment by mschilli87** [comment]
@Joe23232: Just out of curiosity: Why are you 'considering to use' a WM you don't seem to know much (if anything) about?

> * Does it use the xcb library or the xlib?

At least in Gentoo `spectrwm` depends on `xcb-util`, maybe that answers your first question.
However, this seems like a question you can probably answer yourself in a few minutes by looking through the code or package definitions of various distros.

> * Like bspwm, am I able to use any custom scripts written in any language? If so, can I change it in a high level sort of fassion?

To do what? I assume most `spectrwm` users don't use `bspwm` at the same time. So you might need to be more specific. Also did you read the documentation before asking for help? If the feature you are looking for exists, it is likely document. If you can't find anything along those lines in the documentation, such a feature probably does not exist.
You can definitely launch a shell and run any script you want as long as you have a matching interpreter but that has nothing to do with your WM. :wink:

In case you are referring to a custom script to populate the bar, yes you can run one and it is documented. It is a shell script but you could make it a simple wrapper for any other language you prefer. Also, you can swap out the default bar for any other bar, maybe even whatever you use(d) in `bspwm`.

* Am I able to customise the windows like this:

'Customizing' means changing the default. I don't know `bspwm` defaults so I don't know what you 'customized'. You can definitely make windows grey, move the bar to the bottom and use frames around windows. I doubt you can make the default bar look just like in the screenshot but you could install *e.g.* polybar (which might be what was used in the screnshot) and use that instead.

* Is this a manual tiling window manager or automatic? If it is manual then is there some script or something available where I can configure it as an automatic tiling window manager?

I'm not familiar with the terminology but I'm sure you can figure this out by going through the available documentation of by reading/watching any review of this WM that you can find online.

Hope I could help at least a little bit.

**Comment by Joe23232** [comment]
> @Joe23232: Just out of curiosity: Why are you 'considering to use' a WM you don't seem to know much (if anything) about?

I mean like with this particular WM, I want to know if it is able to support such features.

> At least in Gentoo spectrwm depends on xcb-util, maybe that answers your first question.
However, this seems like a question you can probably answer yourself in a few minutes by looking through the code or package definitions of various distros.

Ah I see.

> To do what? I assume most spectrwm users don't use bspwm at the same time. So you might need to be more specific. Also did you read the documentation before asking for help? If the feature you are looking for exists, it is likely document. If you can't find anything along those lines in the documentation, such a feature probably does not exist.

So like with `bspwm` it basically allows you to script your WM however you want and whatever language you want it to. Kinda like `awesome`WM.

I will check out the docs then.

> 'Customizing' means changing the default. I don't know bspwm defaults so I don't know what you 'customized'. You can definitely make windows grey, move the bar to the bottom and use frames around windows. I doubt you can make the default bar look just like in the screenshot but you could install e.g. polybar (which might be what was used in the screnshot) and use that instead.

Sorry I don't meant the taskbar at all (forget about the taskbar). I mean like on the window itself, do you see that blue line? Am I able to add this in, this screenshot is from `awesome`?

> I'm not familiar with the terminology but I'm sure you can figure this out by going through the available documentation of by reading/watching any review of this WM that you can find online.

THanks man.

**Comment by mschilli87** [comment]
> it basically allows you to script your WM however you want

What does 'script your WM' mean? I can configure it to open specific programs upon startup on specific workspace. I can tell it to never tile windows of a particular program by default but let them float instead. Is that 'scripting' my WM? In case the feature does not exist in this WM, its users might not understand what you are referring to whithout describing it.

> I mean like on the window itself, do you see that blue line? Am I able to add this in [...] ?

I see the blue line and I am not aware of a `spectrwm` feature that would enable this kind of window decorarion.
That said, me not knowing it doesn't mean it doesn't exist. If it does, however, (you probably guessed it already) `man spectrwm` should have you covered. :wink:

**Comment by Joe23232** [comment]
> What does 'script your WM' mean? I can configure it to open specific programs upon startup on specific workspace. I can tell it to never tile windows of a particular program by default but let them float instead. Is that 'scripting' my WM? In case the feature does not exist in this WM, its users might not understand what you are referring to whithout describing it.

It means instead of using a standard config file, you can use a language to tell it to do things. But yeah that sounds nice that `spectrwm` supports that :)

> I see the blue line and I am not aware of a spectrwm feature that would enable this kind of window decorarion.
That said, me not knowing it doesn't mean it doesn't exist. If it does, however, (you probably guessed it already) man spectrwm should have you covered. wink

Hopefully it has it :)

**Comment by mschilli87** [comment]
> It means instead of using a standard config file, you can use a language to tell it to do things.

OK. I think I got you now. In this case, I don't think `spectrwm` supports this.
Maybe you can hack together something by setting a bar action script shell that wraps whatever language you want to use and from within that script change the config but that's not a road I would go down.

Can you give an example of somethig you can do with a 'scripted' config that you could not do with a 'standard' one?
All use cases I can think of for to use something like conditionals in the config can probably be handled via program-specific quirks. But maybe I'm just blind to what I'm missing out since I have never seen the light. :wink:

**Comment by Joe23232** [comment]
> OK. I think I got you now. In this case, I don't think spectrwm supports this.

Ah I see thanks anyways.

> Maybe you can hack together something by setting a bar action script shell that wraps whatever language you want to use and from within that script change the config but that's not a road I would go down.

I am going to actually use a third party bar, `spectrwm`'s bar is a bit shit to be honest, you can't even customise it that much.

> Can you give an example of somethig you can do with a 'scripted' config that you could not do with a 'standard' one?

Luke Smith did a video on this, he explains it far better than I can ever do, would you like a link?

> All use cases I can think of for to use something like conditionals in the config can probably be handled via program-specific quirks. But maybe I'm just blind to what I'm missing out since I have never seen the light. wink

Not too sure mate :)

**Comment by mschilli87** [comment]
> [...] would you like a link?

Sure, why not? Always happy to learn something new.
If you refer to [this Luke Smith on LBRY](https://lbry.tv/@luke), I'd prefer a link there over YouTube. :wink:

**Comment by Joe23232** [comment]
@mschilli87 

Sure why not https://www.youtube.com/watch?v=B5r47Q1cn_o

Enjoy =D

**Comment by marcopeereboom** [comment]
`wmctr`l works fine with spectrwm. You really need to read the manual. It is pretty thorough.

**Comment by mschilli87** [comment]
> You really need to read the manual. It is pretty thorough.

@Joe23232: If you need additional motivation to do so, ['Luke Smith did a video on this', too](
https://open.lbry.com/@Luke:7/why-are-so-many-linux-noobs-arrogant). :stuck_out_tongue_winking_eye:

**Comment by Joe23232** [comment]
@marcopeereboom While I could find `wmctr` in the man pages, I am not too sure if I can add a blue line thing at the top of the window like this:

![Full window](https://user-images.githubusercontent.com/34926497/86079122-1e73e900-bad3-11ea-9c88-4cdc2b5a8365.png)

**Comment by LordReg** [comment]
@Joe23232 by "blue line thing" do you mean window border customization beyond width and color? That wouldn't be possible with `wmctrl` as it is not in EWMH spec, but perhaps window frame customization could be extended in the future.

**Comment by Joe23232** [comment]
Oh, thanks anyways, hope to see this being extended in.
