### ISSUE TITLE
Android Studio popup window issues!

### ISSUE THREAD

**Issue by shans10** [conformal/spectrwm#367]
**OS:** Arch Linux
**Spectrwm Version:** 3.4.1/3.4.0
**Application:** android-studio-4.0.0.16

Earlier when I used android studio with **spectrwm v3.3.0** the menu options in the menu bar opened at the _centre_ of the screen which was annoying but usable with the keyboard however the mouse caused the window to disappear but after the update to **3.4.0** on the android-studio welcome page whenever I click the settings wheel it causes a glitch at the centre and that area flickers but menu doesn't popup.

Here are the gifs for the two cases, first one shows the behaviour after the update and the second one shows the behavious before the update!

**Spectrwm v3.4.0/3.4.1**
![01-07-2020 11:34:18](https://user-images.githubusercontent.com/28944997/86209147-8c7de600-bb8f-11ea-8a6e-071507ff8ad3.gif)

**Spectrwm v3.3.0**
![01-07-2020 11:36:57](https://user-images.githubusercontent.com/28944997/86209184-9ef81f80-bb8f-11ea-9124-361bef10e492.gif)

**Comment by panlazy** [comment]
I've just tried same thing in IntelliJ which they are very similar there is no issue but with Android Studio this happens in me also. You can use arrow keys to navigate in configure as a workaround.

**Comment by marcopeereboom** [comment]
I think we have several bugs that are the same. We need to send @LordReg some beer to fix it!
