### ISSUE TITLE
Getting WM_CLASS of statusbar

### ISSUE THREAD

**Issue by pryr07** [conformal/spectrwm#371]
Is it possible to get the class or name of the statusbar alone.
I am using picom as compositor and wanted to remove shadows from statusbar but I can't grab `WM_CLASS` or `WM_NAME` of the bar using xprop.

**Comment by marcopeereboom** [comment]
I'd run strings on the binary.

**Comment by pryr07** [comment]
That's a good idea but I can't find anything that may solve the issue. I tried calling ewmh functions with xprop, tried possible strings that might be a `WM_CLASS` or `WM_NAME` with no luck.

**Comment by LordReg** [comment]
Those properties were never added since spectrwm doesn't need them on its own windows. It is, however, technically correct to add them since the bars are top-level windows. Fixed in master.
