### ISSUE TITLE
terminology rendering problem.

### ISSUE THREAD

**Issue by LittleWytch** [conformal/spectrwm#373]
I like to use the terminology terminal for that little extra bit of bling, but it doesn't render in spectr. It will open, i will see a border for it, if I press backspace I will hear terminology's default error sound, I can type "exit" and the border will vanish. But that's all. I can't actually see what I'm typing or the prompt or the terminal, just the a border over whatever background I have set. So far, that's the only issue I have that's not a result of my own noob-nes.

**Comment by LordReg** [comment]
It was unlikely an issue in spectrwm itself. Current version (1.13.0) works.
