### ISSUE TITLE
Cannot use dmenu_run with flag -fn

### ISSUE THREAD

**Issue by axelcalixte** [conformal/spectrwm#375]
Hello,
I'm having trouble with dmenu_run. I can't have it display a custom font in spectrwm. It works fine as a script on its own. But binding the script to something in spectrwm does absolutely nothing. 

Here is my font config 
![image](https://user-images.githubusercontent.com/55485674/89641894-3c86f300-d8a2-11ea-9598-ca325f591120.png)

And here is the command in the terminal or script that works
![image](https://user-images.githubusercontent.com/55485674/89641986-66d8b080-d8a2-11ea-9c89-b9ed010be70c.png)

Thanks in advance :)

**Comment by LordReg** [comment]
Your example works for me.. did you set locale in the env where spectrwm is started?
for example in `~/.xinitrc`
```
export LANG=en_US.UTF-8
exec spectrwm
````

**Comment by axelcalixte** [comment]
I'm currently using lightdm and not xinitrc to log in.
I made sure my LANG setting is set as fr_FR.UTF-8. It is.

Maybe I should try en_US.UTF-8... Oh and I have version 3.3.0-1.4 of spectrwm.

**Comment by LordReg** [comment]
`dmenu_run` is probably exiting with an error.  Try capturing `stderr` to see what it might be, e.g.:
```
#!/bin/sh
/usr/bin/dmenu_run -fn "Iosevka Term:style=Semibold:size=12" -sb "#5e81ac" -sf "#eceff4" -nb "#2e3440" -nf "#e5e9f0" > ~/dmenu.log 2>&1
```

**Comment by axelcalixte** [comment]
Sorry for not answering fast.
Your solution didn't bring anything sadly. Running the script alone works in a terminal. When putting it inside the config while replacing the color values and the font name with the variables, I still can't use dmenu with the -fn flag. I didn't try directlt embedding the script in the spectrwm config though.

Thanks again for your time and suggestions.

**Comment by LordReg** [comment]
Did you check `~/dmenu.log` after adding ` > ~/dmenu.log 2>&1` to your script as in my example?  If dmenu has issues loading a font, it will output errors.

**Comment by marcopeereboom** [comment]
@axelcalixte, has this been fixed?

**Comment by axelcalixte** [comment]
Sorry for not being active around here.
I didn't find a fix for my problem, I'd say we can close this since I no longer really user spectrwm anyway on my machines.
Maybe if I come back to it in the near future the issue won't be there waiting for me

Thanks for spectrwm I think it should be recommended more but I had some gripes with it still. And sorry I don't care that much talking about them
