### ISSUE TITLE
Desktop background flickers through maximized windows with `disable_border` enabled

### ISSUE THREAD

**Issue by kylethebaker** [conformal/spectrwm#376]
With `disable_border` enabled I will see my desktop background flicker through when switching between fullscreen windows  (I think this is called the 'max' layout mode). This also happens when switching between workspaces.

I created a screen recording of it with a bright pink background so its extra noticeable. This is using mod+j to switch between two maximized windows a few times, then I toggle the bar on which adds the fullscreen border back and the flickering goes down: https://www.youtube.com/watch?v=7oxYG7zEYSA

I'm working around this right now by turning off `disable_border` and using `color_focus_maximized` with the same background color of my terminal so it blends in. This works alright, but isn't ideal with certain windows, because the border becomes noticeable.

I've disabled my compositor (picom) to rule that out, and it also occurs regardless of how I set the background the image/color (`feh` vs `xsetroot`)

I'm happy to provided any additional details

**Comment by LordReg** [comment]
What is your OS/distro, video driver and version of spectrwm?

**Comment by kylethebaker** [comment]
I'm running arch linux with intel graphics

Graphics card driver:
```
local/xf86-video-intel 1:2.99.917+908+g7181c5a4-1 (xorg-drivers)
    X.org Intel i810/i830/i915/945G/G965+ video drivers
```

Spectrwm version:
```
spectrwm 3.4.1 Build: 3.4.1
```

This is from `lspci`
```
00:02.0 VGA compatible controller: Intel Corporation Iris Plus Graphics G7 (rev 07)
```

This is the cpu is that's useful
```
Intel(R) Core(TM) i7-1065G7
```

**Comment by LordReg** [comment]
This should be resolved in master.
