### ISSUE TITLE
Focus/stacking regression

### ISSUE THREAD

**Issue by wavexx** [conformal/spectrwm#377]
I identified one case (PrusaSlicer - built from source, using wxWindows 3.x) where there is a stacking issue in spectrwm master.

There is a main window, and two dialogs which are transient-for the main window. When the _second_ dialog is shown modally, it appears above the main window, but under the first dialog (which often covers it completely). It's actually shown focused, so manually using raise (after #372) works.

**Comment by LordReg** [comment]
This should be fixed. New transient-for windows should be stacked above others with the same target window.
