### ISSUE TITLE
`disable_border` for all lone windows, not only tiled

### ISSUE THREAD

**Issue by smhmd** [conformal/spectrwm#379]
With `disable_border` set to `always`, only lone TILED windows lose their border. It would be great to have a more comprehensive option to disable lone borders in the following:

- Maxed workspaces (fullscreen). Currently, to achieve this you have to hide the bar, which I don't understand.
- On `maximize_toggle`.

**Comment by marcopeereboom** [comment]
PR welcome.

**Comment by smhmd** [comment]
Not a C dev, sadly.

**Comment by gitlerat** [comment]
This is not even working for me. I set disable_border = always and if I have only one window open in tiling mode there is still a border... would be glad if there will be a fix :)

**Comment by gitlerat** [comment]
Sorry, my bad. This feature was implemented in one of the updates. I am on debian buster and there is an old version in the package manager.

**Comment by LordReg** [comment]
Fixed
