### ISSUE TITLE
Problems with iconify

### ISSUE THREAD

**Issue by ajP89** [conformal/spectrwm#380]
1. Iconified windows showing up in only their parent workspaces. Eg i cant use in WS1 a terminal window I iconified in WS2. 
2. If a single window is iconified, why do I need to select it in the bar to open it?
3. No option to toggle iconified window with a single key  (MOD+w to iconify, and MOD+shift+w to uniconify. MOD+shift+w should be used to toggle b/w iconify & uniconify, though its a minor issue).

**Comment by marcopeereboom** [comment]
This is working as designed. Iconify is per workspace, not global.
