### ISSUE TITLE
Overlapping borders when not using gaps

### ISSUE THREAD

**Issue by Harjuu** [conformal/spectrwm#381]
With a 0 gaps setup your separate windows' borders are right next to each other, effectively creating a double the thickness border. It would be great if there was an option to have them overlap at those places. Unfortunately I don't know my way around C enough to implement something like this.

**Comment by ronniedroid** [comment]
Set your gaps not to 0, but to the nagative value of the borders. So if you have a border thickness of `2`, your gaps should be `-2`.

**Comment by LordReg** [comment]
Also, the man page states negative `tile_gap` values cause tiled windows to overlap.
