### ISSUE TITLE
Spectrwm is not compliant with system tray

### ISSUE THREAD

**Issue by doums** [conformal/spectrwm#388]
Hi,

Recently I tried to setup a simple 3d party system tray https://github.com/sargon/trayer-srg along spectrwm.

For that I added this to my `spectrwm.conf` file:
```
# start trayer
autorun = ws[1]:trayer  --align left --monitor primary --width 200 --widthtype pixel --height 32 --transparent true --alpha 0 --tint 0x262626 --distance 600 --distancefrom left

# quirk on the trayer's window
quirk[trayer] = FLOAT + ANYWHERE + MINIMALBORDER + NOFOCUSCYCLE + NOFOCUSONMAP
```

Whit this setup (and this is the only thing to do spectrwm allows if I'm not mistaken, sadly) I identified some issues that prevent me to use the system tray:

1. I can still resize, move, fullscreen, toggle floating, delete the trayer's window (in fact all interactions are possible)
2. when I interact whit some menu when I click on an icon in the system tray, and I open the corresponding application window, the whole trayer's window shifts a little bit down

Can you improve this ? I think making a new quirk option like `SYSTEM_TRAY` to ignore all the normally possibles interactions whit the window would be great.

**Comment by th3r00t** [comment]
imho this is likely the only thing preventing spectrwm from being a daily driver.

**Comment by srt0** [comment]
I use SpectrWM as my primary WM. System Tray is really crucial. As soon as these few tweaks and enhancement happens, a lot of people will use it as the main.

**Comment by danrobi11** [comment]
I got systray working here with tint2. Config files and screenshot [here](https://old.reddit.com/r/spectrwm/comments/jubt02/systray_solved/)
