### ISSUE TITLE
wm hangs on drag'n'drop in Intellij IDEA

### ISSUE THREAD

**Issue by kazufukurou** [conformal/spectrwm#39]
Spectrwm 2.5.0, Arch linux:
-select text in Intellij IDEA's text editor
-drag selection with mouse (drag'n'drop functionality must be enabled by default)
-system hangs infinetly
Tried in dwm 6.0 and i3 and it work without the issue.

**Comment by marcopeereboom** [comment]
Please reopen if it still happens with the latest spectrwm.

**Comment by JacobAMason** [comment]
I think this issue reappeared. If I try to drag any selected elements in any of the IntelliJ products (IDEA, Pycharm, Android Studio), everything freezes. I still have mouse movement, but that's it. Audio still plays in the background, but I have to Ctrl+Alt+Backspace to kill the X server. I've tried running the IntelliJ products with their special Java build, but that didn't help.

Arch Linux w/ Spectrwm Version 3.0.2

**Comment by matrixd** [comment]
System doesn't hang. Seems like only idea hangs and capture mouse and keyboard focus without releasing it.
After killing all idea's processes with -9 option spectrwm become working again.

**Comment by JacobAMason** [comment]
@matrixd That actually makes a lot more sense
