### ISSUE TITLE
Picom transparency on bar

### ISSUE THREAD

**Issue by Harjuu** [conformal/spectrwm#390]
I can't figure out how to exclude the bar from picom transparency. I've tried getting the `WM_CLASS` of the bar but xprop returns nothing. #371 says this is fixed on master, but I'm on the latest available version on Void Linux. I've tried `"class_i = 'panel'"` and `"class_g = 'spectrwm'"` but none of them work. I'm not sure how to use `_NET_WM_NAME`.

**Comment by Ramiferous** [comment]
Are you running the Git version of Spectrwm? AFAIK it currently only works with the Git version.

**Comment by LordReg** [comment]
The bar window properties will be included in the next release.  Need to build the git version in the mean time.

**Comment by Harjuu** [comment]
Built from source and now it does work, cheers!
