### ISSUE TITLE
Incorrectly interpreting keypresses in bind

### ISSUE THREAD

**Issue by Harjuu** [conformal/spectrwm#391]
I am using `xcape` to have my Tab key act as Hyper_L when held down and as a Tab key on fast release to allow for using Tab as my modifier key. I have bound `rg_move_next` to `Mod1+Tab`, and this has worked without any issues on my previous install. 

Now on a fresh install spectrwm detects a Tab keypress immediately when I press Tab, which triggers `rg_move_next`. I have checked with `xev` and it registers a Hyper_L keypress if I press and hold, and a Tab keypress if I press and quickly release, just like it should.

**Comment by LordReg** [comment]
How do you have `xcape` configured? Do you also set an Xkb keyboard layout?
Since `xcape` uses Xkb extension, it may be related to this issue: https://github.com/conformal/spectrwm/issues/310#issuecomment-621158723

**Comment by Harjuu** [comment]
This issue resolved itself somehow so I forgot about this posted issue, sorry about that. Closing as I wouldn't be able to reproduce it unfortunately.
