### ISSUE TITLE
Blocked keyboard input until SIGHUP

### ISSUE THREAD

**Issue by hngt** [conformal/spectrwm#392]
Occasionally (and therefore, making this issue difficult to reproduce), on versions 3.4.1 and higher (including upstream), all keyboard input is blocked until SIGHUP signal is received by spectrwm as to restart it.

I cannot point to any cause of the issue, but if asked I can do some logging if needed.

**Comment by marcopeereboom** [comment]
Logging always helps.

**Comment by hngt** [comment]
How could I do it, should I use gdb or what?

**Comment by LordReg** [comment]
Which `focus_mode` are you using?  Any particular app(s) open when it happens? What layout mode? Did you try clicking?

**Comment by hngt** [comment]
I am using `focus_mode = default`. Layout is usually vertical, and it happened most often when I had Firefox opened (as it is the program I use the most), but that also happened with other programs (i.e. Brave, mpv). Mouse input works fine, but then I can only do it within that screen as I am unable to change the workspace.

**Comment by LordReg** [comment]
Do you have any daemons running that might grab keyboard input? I run the same apps and don't experience this issue.
What OS?

**Comment by hngt** [comment]
```
compton -b &
xbanish &
xrdb ~/.config/Xresources &
xset s off &
xset -dpms &
sleep 0.1 &&
startplumb &
toggletouchpad &
a &
udiskie -a -n &
dunst &
```
These are all things I run before `spectrwm`. Arch Linux is the OS I use now.

**Comment by LordReg** [comment]
The issue may be related to dunst as it grabs key/button input when it shows a notification.  I haven't reproduced the issue but try running without dunst to see if the issue disappears.

**Comment by LordReg** [comment]
This was likely related to an input focus fallback issue which has since been resolved.
