### ISSUE TITLE
[Multihead] Focused window on one region lost focus if the "focused" window in another region closes

### ISSUE THREAD

**Issue by osimplex** [conformal/spectrwm#394]
spectrwm 3.4.1-1 - Arch Linux

Steps to reproduce:
0. `bar_format` config with `+W`.
1. Have a window that closes while focus is on another region, eg. `mpv`.
2. Have a window in this "another", actualy current, region with focus, eg. a terminal that opens the video on `mpv` that will stay in the other region.
3. Wait the `mpv` window close.

Current behavior: current window loses focus.
Expected behavior: current window stay with focus.

Current behavior: Window title of "next" window on bar of first region.
Expected behavior: No window title on bar, as there isn't any window.

**Comment by osimplex** [comment]
Ignore:
```
Current behavior: Window title of "next" window on bar of first region.
Expected behavior: No window title on bar, as there isn't any window.
```

I cannot edit the text.

**Comment by wavexx** [comment]
I can confirm this behavior on the current master

**Comment by hashsum0** [comment]
Hello. Two applications are open in the workspace, "URXVT" and "GEANY", if I open a file from "GEANY", then after closing the file selection dialog box, the focus goes to "URXVT".
Linux archlinux 5.10.42-1-lts 
spectrwm V3.4.1 Build: 63b9ae4eafa11c4ef17afe42aeba3fb2c393717e
