### ISSUE TITLE
Default floating window position and size

### ISSUE THREAD

**Issue by anton-rs** [conformal/spectrwm#395]
I like spectrwm because It can resize or move floating window using keyboard,
but if I can make a specific configuration for a specific app, that will save me a lot of keystrokes.

Is spectrwm capable of doing that?
I already try script using xdotool, but it's not working.

**Comment by anton-rs** [comment]
I found an alternative using wmctrl.
wmctrl -r "MPlayer" -e 0,1400,775,500,285
will move mpv to pixel x 1400, y 775
and window size width 500, height 285


Then I will keybind this on specific keybind, but it's great if this can be configured from spectrwm

**Comment by marcopeereboom** [comment]
Do checkout `layout` in man page as well: http://manpages.ubuntu.com/manpages/trusty/man1/spectrwm.1.html

**Comment by anton-rs** [comment]
I found an example from closed issues #346 
layout = ws[1]:4:0:0:0:vertical
layout = ws[2]:4:0:0:0:vertical
this is not working, is this because I test it using restart?
The spectrwm(1) man page states that layout sets the layout at start-of-day and is not retained at restart.

Is there a way to disable that option? So I can test the layout just by restarting
(I have a bug that will freeze my laptop on 2nd startx, so If I want to kill spectrwm and launch it again, I need to restart my laptop)

But this is not working, and what I want is not layout default ratio,
but specific pixel position to a newly launched app window

**Comment by LordReg** [comment]
It's possible to fully apply the config by restarting with the `restart_of_day` action.

The default behavior is to center floating windows.  The `ANYWHERE` quirk uses the app's requested position instead.

With the `FLOAT + ANYWHERE` quirks, it's possible to position mpv with the `--geometry` flag:
spectrwm.conf:
`quirk[mpv] = FLOAT + ANYWHERE`

`mpv --geometry=100%:20 <file>`
will set the initial position of the mpv window to the top-right of the screen, 20 pixels from the top.

**Comment by anton-rs** [comment]
> It's possible to fully apply the config by restarting with the `restart_of_day` action.
> 
> The default behavior is to center floating windows. The `ANYWHERE` quirk uses the app's requested position instead.
> 
> With the `FLOAT + ANYWHERE` quirks, it's possible to position mpv with the `--geometry` flag:
> spectrwm.conf:
> `quirk[mpv] = FLOAT + ANYWHERE`
> 
> `mpv --geometry=100%:20 <file>`
> will set the initial position of the mpv window to the top-right of the screen, 20 pixels from the top.

This is working great for MPV,

is there a way to do this for other apps too?
I would like to use this for android studio emulator.

For now, my temporary solution is to bind this function with Mod1+F8
wmctrl -a PIXEL_2 -e 0,1400,75,443,785


So each time I launch android studio, I do
1. Select android emulator window using mouse (there is a weird bug I can't select it with MOD+h / MOD +j)
2. Press keybind to toggle emulator window
3. Alt+F8 to move emulator to my desired position

**Comment by anton-rs** [comment]
I don't really need this feature anymore.

The fact that I can set MPV default position when launched is good enough for me. thanks all.
