### ISSUE TITLE
kitty --single-instance

### ISSUE THREAD

**Issue by nunzioc** [conformal/spectrwm#396]
I use the terminal kitty which has an option to launch with a single instance that gets reused for each new window.
In spectrwm, new kitty windows always open in the same workspace even if I have navigated to a different workspace. I thought this might be an issue with kitty but I have been unable to duplicate this problem other window managers that I tried (i3, bspwm).

I'm running spectrwm 3.2.0 on Ubuntu 20.04

**Comment by LordReg** [comment]
By default, spectrwm tries to keep new windows on the workspace where the process was spawned. The solution is to either run kitty as separate instances or add a quirk to your spectrwm.conf. e.g. `quirk[kitty] = IGNORESPAWNWS`.
