### ISSUE TITLE
Crash on fullscreen layout

### ISSUE THREAD

**Issue by gr523** [conformal/spectrwm#398]
Steps to produce the error
1. Be in any layout that is not this [ ],lets say [1|1]
2.Add two windows into a workspace,lets say I open two terminals
3.Now switch to fullscreen layout( [ ] ).
system becomes non-responsive.normally the only way to get out is to shut down with power button,for me I use the sysrq to kill init and restart  
sometimes the error doesnt occur in this manner but,

so now we are in the full screen mode
1. close the two windows open them again.
2. cycle layout ,from [ ] to [1|1] to [1:1] to [ ],now the problem is back

**Comment by marcopeereboom** [comment]
What version are you on? I can not reproduce this on latest.

And what terminal do you use when this happens? Any other non-standard settings?

**Comment by gr523** [comment]
when i first found the error i was on version 3.2 but then i tested version 3.4.1 on a vm(kvm) the error persisted.
 I use terminator but it doesnt have be a terminal,just any kind of windows

**Comment by LordReg** [comment]
Which `focus_mode` do you use? max layout has been known to act up with `focus_mode = follow` due to a race condition.

**Comment by gr523** [comment]
Yes `focus_mode=follow` seems to be the problem,no problem on other modes
