### ISSUE TITLE
bind keys not mapped correctly after wm start

### ISSUE THREAD

**Issue by kazufukurou** [conformal/spectrwm#40]
Spectrwm 2.5.0, Arch linux:
$localectl
System Locale: LANG=en_US.UTF-8
VC Keymap: dvorak
X11 Layout: us,ru
X11 Model: pc104
X11 Variant: dvp,

In spectrwm.conf I have:
bind[menu] = MOD+dollar
bind[term] = MOD+Return
bind[ws_prev] = MOD+semicolon

After wm start MOD+dollar not works but MOD+l (p in qwerty) works.
When I press MOD+semicolon (q in qwerty) it looks like original restart command starts. After this all my custom keybindings works fine.
Also MOD+return works as well as MOD+Shift+Return, while I only have MOD+Return.
My config https://raw.githubusercontent.com/kazufukurou/dotfiles/master/.spectrwm.conf

**Comment by marcopeereboom** [comment]
Pretty sure that means that one of the keys is invalid and spectrwm stops parsing the config file.  The bar should emit an error if this happens.  Please reopen if this still happens with the latest version.

**Comment by jul16ares** [comment]
Same problem here,azerty keyboard version 2.6.0-1 amd64

**Comment by loicreynier** [comment]
Same here with version 3.3.0 with a French azerty layout. No error error emitted by the bar and more importantly it also happens without using a config file.

**Comment by LordReg** [comment]
It turns out this is expected behavior and the solution is to run setxkbmap before starting spectrwm. 
See https://github.com/conformal/spectrwm/issues/310#issuecomment-621158723 for a detailed explanation.
