### ISSUE TITLE
[Feature request] SCRATCHPAD quirk

### ISSUE THREAD

**Issue by osimplex** [conformal/spectrwm#400]
I've written #345 previously for a "A way to get a ws stack independent window for scratchpad".

I've made a [implementation](https://debxp.org/artigos/controle_remoto_e_janelas_transientes#implementacao) for WM independent scratchpad, but there is a problem that appears in at least two situations.

Situation 1:
1. Have a ws with some windows in default layout, vertical tile.
2. Fire the `scratchpad` script to create or place and focus a spd (scratchpad) window in current ws.
3. Fire again `scratchpad` to hide the spd window.
4. The last window of ws will always receive the focus, even if was not there before the spd cicle.

Situation 2:
1. Have a ws with some windows in default layout, vertical tile.
2. Fire the `[maximize_toggle]` action to have current focused window maximized.
3. Do the spd cicle, steps 2 and 3 of situation 1.
4. No maximized window and, as step 4 of situation 1, focus on last window always.
  - With `FLOAT` quirk defined for a spd window, if I fire `scratchpad` on a ws with max layout the window will be maximized for some reason, but this is for another issue (#399).

The problem is: spectrwm doesn't have a machanism to handle a ws independent window, then the spd window will mess with the ws last focused window, then the focused window after spd window gets iconified or goes to another ws will be always the last, and this is the current expected behavior.

What I name here `SCRATCHPAD quirk` is, indeed, a machanism to just decouple the spd window, handled by an external tool like my script, from ws window list, just to not lose the "truly" last focused window.

**Comment by c0dev0id** [comment]
I'd also wish for some kind of scratchpad I can use to fire up an application (terminal) with set dimensions as a float on top in pretty much any situation. Like a thing that's in front of the window managers usual behavior.

I also fiddled with a scratchpad script with tabbed and wmctrl. It works, but it's far from optimal.

```sh
#!/bin/sh
WID="$(cat /tmp/scratchpad | sed 's/0x//g')"
if wmctrl -l | fgrep -q "${WID}";
then
    wmctrl -i -r 0x${WID} -b toggle,hidden
    wmctrl -i -r 0x${WID} -b add,above
else
    WID=$(tabbed -c -d -n scratchpad -g 1280x768+300+120 -r 2 st -w '')
    wmctrl -i -r 0x${WID} -b add,above
    echo ${WID} > /tmp/scratchpad
fi
```

**Comment by c0dev0id** [comment]
I stumbled over this issue and wanted to show the next iteration of my scratchpad script, which moves it to the current WS as well:
```sh
#!/bin/sh
# set the following quirk in .config/spectrwm/spectrwm.conf
# quirk[scratchpad] = FLOAT + ANYWHERE

# get scratchpad window id
WID=$(wmctrl -x -l scratchpad | fgrep '.scratchpad' | cut -d" " -f1)

if [ -z "$WID" ]
then
   st -c scratchpad -g 128x38+250+150 &
else
    # check if window is iconfified or on another WS (or both)
    if xwininfo -id $WID | fgrep -q IsUnMapped
    then
        # get current workspace ID
        CWID=$(wmctrl -d | awk '{ if ($2 == "*") print $1 }')
        # remove hidden flag
        wmctrl -i -r $WID -b remove,hidden
        # move window to current workspace
        wmctrl -i -r $WID -t $CWID
        # activate (give focus)
        wmctrl -i -R $WID
    else
        # window is visible => hide
        wmctrl -i -r $WID -b add,hidden
    fi
fi
```

It has one minor issue. When hidden again, the focus is properly set to the previous frame, but somehow the border color does not changed to active. (demo: https://codevoid.de/h/spectrwm_ehwm_prev_focus.mp4)

**Comment by LordReg** [comment]
Possible since 3.5.0
