### ISSUE TITLE
Virtualbox full screen mode results results in black screen

### ISSUE THREAD

**Issue by afhpayne** [conformal/spectrwm#404]
Steps:
Run spectrwm in host
Start VirtualBox, start VM guest
Use ctl-F to switch guest to full screen mode

Result: black screen. Can be recovered by pressing ctl-F again to return to windowed mode in VM

Expected: present guest vm in full screen

Tried:
mod-b in spectrwm to remove status bar
mod-t in spectrwm to test VM guest in windowed or tiled mode
alternate environment on same device (works in XFCE4 on same device)

**Comment by ronniedroid** [comment]
While in full screen, try hitting `Ctrl` then close the window with your spectrwm krybinding. It will kill a frame around the VM, but will keep the VM itself running.  At least this worked for me.

**Comment by afhpayne** [comment]
Will try, but what do you mean by close the the window? Killing the frame with mod-x aborts the VM. 

Also to clarify, spectrwm commands behave strangely after entering full screen. For example pressing ctl (to excape the VM) then mod-b does not hide the status bar. It's 'frozen' to the guest's workspace. But then hitting 'ctl' and mod-5 (switching to workplace 5) the status bar is hidden as expected.

**Comment by LordReg** [comment]
The glitchy fullscreen behavior can be fixed by disabling the "Mini ToolBar" under `Settings->User Interface` on the VM.
