### ISSUE TITLE
Cursor always starts at center of screen

### ISSUE THREAD

**Issue by krzkrzkrz** [conformal/spectrwm#409]
Hi,

Im running on Arch Linux.

When switching workspace. The mouse cursor always starts at the center of the screen

Would be good if each workspace remembered where the cursor was on last position. Or even better, just remembered where it was last.

Not sure if this is a issue/setting on the OS level or something within Spectrwm

**Comment by LordReg** [comment]
spectrwm only changes the mouse cursor position when `warp_pointer` is enabled.  It is disabled by default, so make sure it isn't enabled in your spectrwm.conf.
