### ISSUE TITLE
Workspace switching does not work correctly on dual monitor setup with the latest version

### ISSUE THREAD

**Issue by ImpSpy2** [conformal/spectrwm#410]
I'm currently on version 3.3.0 and I have ws_next_all = MOD+Up and ws_prev_all = MOD+Down so that I can move up and down workspaces using the MOD + arrow keys. On this version pressing MOD+Up moves from workspace 1 to 3 skipping workspace 2 which is on the second monitor which the the behaviour I want as I only want to use workspace 2 (second monitor) when I switch to that region. However on version 3.4.1 the same action results in workspace 1 switching with 2 (moving the content to the second monitor) instead of skipping to 3. Enabling the workspace_clamp feature (which appears to do nothing on 3.3.0) results in the correct behaviour of locking workspace 2 to the second monitor however you cannot press MOD+Up to skip past it to workspace 3 instead you have to press MOD+Down to move down from the top to the bottom.

**Comment by LordReg** [comment]
`ws_next`, `ws_prev`, `ws_next_all`, `ws_prev_all`, `ws_next_move`, and `ws_prev_move` should all skip mapped workspaces unless `cycle_visible` is enabled. Fixed in master.
