### ISSUE TITLE
If text in the bar is changed to larger text, alignment it will crash

### ISSUE THREAD

**Issue by ayoubkafi** [conformal/spectrwm#411]
### before muting
![before](https://user-images.githubusercontent.com/71545968/100909537-280fdb80-34cd-11eb-8de5-c426c665927c.png)
### After muting
![after](https://user-images.githubusercontent.com/71545968/100909516-234b2780-34cd-11eb-8422-02944809412d.png)

my bar format
bar_format  = +N:+I +S <+D> +|R+A

**Comment by LordReg** [comment]
The text is being cut off in your "After muting" example because the bar sections have 50/50 width and the text is overflowing.
You can change the mode of the left section to fit its text so maximum space is available for +A:
```
bar_format = +|T+N:+I +S <+D>+|R+A
```

**Comment by ayoubkafi** [comment]
#LordReg thank you
