### ISSUE TITLE
could not find dmenu_run

### ISSUE THREAD

**Issue by ZvikaZ** [conformal/spectrwm#416]
I'm working at a CentOS7, without root permissions.

I've compiled spectrwm myself. It works OK so far. However, there's a `total exceptions: 2, first exception: could not find dmenu_run` message at the top. Therefore, I've compiled it as well, and added it to path.
Then refreshed with meta+q - but it's still there.

I've seen other similar reports, but this one is different:
- It doesn't open even with meta+p
- I have `which`, and it's able to find `dmenu_run`

Thanks

**Comment by LordReg** [comment]
It appears `which` and/or `dmenu_run` may not be in the `PATH` of *spectrwm's* environment. Keep in mind that spectrwm itself will not read `PATH` from `~/.bashrc`, etc.  You need to set `PATH` in the environment where spectrwm is started. (e.g. `~/.xinitrc`, `~/.xprofile`, etc)

For example, if starting via `~/.xinitrc`:
```
export PATH="/home/user/bin:$PATH"
exec spectrwm
```

**Comment by ZvikaZ** [comment]
Thanks, it indeed helped.
It's worth mentioning in the `Install` section, when there will be one ;-)
