### ISSUE TITLE
Miniwindows are locking focus

### ISSUE THREAD

**Issue by levaidaniel** [conformal/spectrwm#42]
Somewhere along the road spectrwm stopped working sanely with eg. LibreOffice when opening an inside "small window" for a toolbar or the likes. When I press eg. F11 (styles), it gets the focus, but I can't get the focus back to the main libreoffice window to type something after selecting a style. I'm absolutely sure this has worked before, but I don't know which commit introduced this regression.
This is of course wrong with other applications also, for example easytag when opening the Scanner window.

**Comment by marcopeereboom** [comment]
Is this still an issue?

**Comment by levaidaniel** [comment]
Yes.

**Comment by marcopeereboom** [comment]
I clicked the wrong button.
