### ISSUE TITLE
Jetbrains IDE unusable in spectrwm

### ISSUE THREAD

**Issue by doums** [conformal/spectrwm#422]
Hi,

Since recently, in the Jetbrains IDEs when you want to create a file / folder from the file browser, in the window that opens containing an input to write the name of the file, the pressed keys are not received.
This is a big problem because it makes the IDEs almost unusable.
Here is the output of xprop on the input window:
```
WM_STATE(WM_STATE):
		window state: Normal
		icon window: 0x0
_NET_WM_ALLOWED_ACTIONS(ATOM) = _NET_WM_ACTION_CLOSE
_NET_WM_DESKTOP(CARDINAL) = 2
_NET_WM_USER_TIME(CARDINAL) = 55618584
_NET_WM_WINDOW_TYPE(ATOM) = _NET_WM_WINDOW_TYPE_DIALOG
_MOTIF_DRAG_RECEIVER_INFO(_MOTIF_DRAG_RECEIVER_INFO) = 0x6c, 0x0, 0x5, 0x0, 0xc0, 0x3, 0x40, 0x1, 0x0, 0x0, 0x0, 0x0, 0x10, 0x0, 0x0, 0x0
XdndAware(ATOM) = BITMAP
_NET_WM_STATE(ATOM) = _NET_WM_STATE_SKIP_TASKBAR, _NET_WM_STATE_ABOVE
WM_HINTS(WM_HINTS):
		Client accepts input or input focus: False
		window id # of group leader: 0x140004c
WM_TRANSIENT_FOR(WINDOW): window id # 0x140004c
_NET_WM_PID(CARDINAL) = 88409
WM_CLIENT_MACHINE(STRING) = "mitx"
WM_PROTOCOLS(ATOM): protocols
_MOTIF_WM_HINTS(_MOTIF_WM_HINTS) = 0x3, 0x0, 0x0, 0x0, 0x0
WM_NORMAL_HINTS(WM_SIZE_HINTS):
		program specified location: 366, 625
		program specified size: 544 by 181
		window gravity: NorthWest
WM_CLASS(STRING) = "jetbrains-webstorm", "jetbrains-webstorm"
WM_CLIENT_LEADER(WINDOW): window id # 0x1400008
_NET_WM_NAME(UTF8_STRING) = "win18"
WM_NAME(STRING) = "win18"
_SWM_PID(STRING) = "88359"
```

NOTE: the problem does not exist in dwm.

**Comment by n3oney** [comment]
Same thing happens in BSPWM - what they advise you to do is run `wmname LG3D` [Source](https://wiki.archlinux.org/index.php/Java#Gray_window,_applications_not_resizing_with_WM,_menus_immediately_closing)

**Comment by LamprosPitsillos** [comment]
`export _JAVA_AWT_WM_NONREPARENTING=1`
Try adding this to your shell rc file

**Comment by doums** [comment]
Already the case for me, does not fix the problem.

**Comment by lemnos** [comment]
+1. I'm also having issues with jetbrains in general. Menus don't work properly.

**Comment by ferrao** [comment]
I am trying to get away from `bspwm` exactly because of these issues, but It seems `spectrwm` suffers from them too.

**Comment by n3oney** [comment]
> I am trying to get away from `bspwm` exactly because of these issues, but It seems `spectrwm` suffers from them too.

https://wiki.archlinux.org/title/Java#Gray_window,_applications_not_resizing_with_WM,_menus_immediately_closing

**Comment by ferrao** [comment]
Have tried all of those @n3oney, never manage to get all my complex Java apps to run flawlessly on bspwm, fixing one breaks others, I have lost countless hours on this.

`dwm` seems to get it right, but the pain to solve all the conflicts I get when trying to apply all the patches needed to make it usable for me also puts me off... Will stick to `bspwm` for now, but will keep watching `spectrwm` ;)
