### ISSUE TITLE
keyboard non-finctional

### ISSUE THREAD

**Issue by roof98** [conformal/spectrwm#427]
this is on first installation.

PopOs 20.01 

logging into spectrwm none of the default keyboard shortcuts work. I cannot tell if the keyboard alltogether is non-functional or just shortcuts as I am unable to launch anything to begin typing.

Device: Lenovo thinkpad

**Comment by LordReg** [comment]
Do you use a non-us/non-default keyboard layout?  If configuring your layout via the xorg.conf `XkbLayout` option, for example, the bindings may be different than expected.

Also, you could use the `autorun` option to start a terminal when spectrwm starts:
`autorun = ws[1]:xterm`

**Comment by roof98** [comment]
I feel like a total idiot. It had nothing to do with spectrwm afaik. It was the MOD key being set to something not kosher with my keyboard layout so I couldn't launch anything.
