### ISSUE TITLE
Bug Report: Spectrwm crash sequence

### ISSUE THREAD

**Issue by chaibronz** [conformal/spectrwm#435]
I can make my Spectrwm crash every time with this simple 4-step sequence, can you?: 

1. open any two windows in vertical stack mode (two terminals will do)
2. toggle layout to monocle/max stack mode
3. restart Spectrwm  
4. toggle layout back to monocle/max stack mode

Note: I can repeat this crash sequence under all conditions I've tried, which include: with spectr bar disabled (thought crash might have been related to a font Spectrwm didnt like), without any auto-start programs (thought an auto-run program or command may have been causing some interference), and with default focus/spawn settings (thought maybe a focus mode I had may have been messing with something).  All in all, if this is a legit bug (and not just me), should be pretty simple to repeat under most conditions.

EDIT: **** This below sequence seems to be a workaround and probabaly worth calling out ***

Non-crash sequence:

1. open any two windows in vertical stack mode (two terminals will do)
2. toggle layout to monocle/max stack mode
3. restart Spectrwm  
4. toggle window focus **(crash avoider step)** 
5. toggle layout back to monocle/max stack mode

  

Specs:
Spectrwm Version: 3.4.1
Fedora 33 [Kernel 5.10.17]

**Comment by LordReg** [comment]
Fixed in 3.5.0.
