### ISSUE TITLE
Windows/Screen not beeing shared properly when not rendered in a monitor

### ISSUE THREAD

**Issue by impresionista** [conformal/spectrwm#437]
Well, this is kind of strange and i don't know if its common behavior for spectrwm. I read that i3 doesn't render workspaces that are not being focused, so it could be that spectrwm behaves similarly.

The thing is that if a window is running in a workspace (ws), lets say ws_1, and I'm working in another ws and want to share/capture that window it doesn't get listed in OBS/Firefox/Discord/Chromium/etc. If I use two monitors and have the shared window in one monitor, I can share it without issues; BUT if I change the ws that is being shown in the monitor (i.e. I send the ws with shared windows to "background"), the shared windows becomes black.

Does anyone experience the same issues? If so, have you found a solution or did you learned to live with that?

I've found a comment in Spectrewm's Gitlab [(397)](https://github.com/conformal/spectrwm/issues/397#issuecomment-716960859) that might confirm my suspicions that hidden workspaces are not being rendered. If that's the case, I suppose there is no solution.

**Comment by abelbabel** [comment]
I can confirm issues with "screen sharing" with Firefox during video conferences (Big Blue Button, Jitsi could be as well). My problem is that sharing freezes or sharing remains black/blank.

Had issues with Ubuntu 18.04 as well as FreeBSD 12.2-RELEASE and latest Firefox available for those systems via normal package repos. When switching to the default desktop in Ubuntu 18.04 (is it Unity?), sharing works. Otherwise got around it by sharing the file I wanted to show or let other conference members share their screen ...

**Comment by abelbabel** [comment]
Casually gave i3 a try - there screen-sharing during video conferences works.

**Comment by abelbabel** [comment]
My problem seems to be magically solved!

May be a Firefox problem or something that was changed in whatever x-library ... I will still observe this.

**Comment by impresionista** [comment]
Actually the problem in my case is that windows are not listed to be shared if they are not showed in one of my monitors. And if I manage to share that window while it's being shown on a monitor, as soon as I switch to a different desktop (i.e. the window is not being shown on any monitor at all) the shared screen becomes black. When the windows it's showed again on a monitor, the shared "stream" becomes visible again.

**Comment by LordReg** [comment]
Is this still an issue? Running a compositor might help.

This shouldn't be an issue on spectrwm's end since windows are simply mapped/unmapped depending on workspace visibility.

**Comment by impresionista** [comment]
Hi there! Yes, it's still an issue. I thought a compositor might help so I'm using picom as compositor but it didn't help. I'll try again with the compositor, maybe I've something misconfigured. 

I'll post here if I find a solution.
