### ISSUE TITLE
Statusbar markup does not work

### ISSUE THREAD

**Issue by qsmodo** [conformal/spectrwm#439]
I cannot get `+@fg;` and other markup to work. This is my configuration file:
```
bar_font[1]              =  -*-terminus-medium-*-*-*-14-*-*-*-*-*-iso10646-*
bar_color[1]             =  midnightblue
bar_color[2]             =  red
bar_font_color[1]        =  green
bar_font_color[2]        =  red
bar_format               =  +@fg=2;+S+@bg=2;+I+@stp;
bar_action_expand        =  1
bar_delay                =  1
```
And this is how the statusbar looks like:

![21-19:46:38](https://user-images.githubusercontent.com/75080827/111923495-6ee30a80-8a97-11eb-9065-da9176dbf1ee.png)

As you can see. the markup sequences are not interpreted.

The same outcome is the same both in Debian and Artix on the 3.4.1 version.
```
$ spectrwm -v
spectrwm 3.4.1 Build: 3.4.1
```

**Comment by LordReg** [comment]
The selector parameter in `bar_color[]`, `bar_font_color[]` and `bar_font[]` is the X screen index.  It should be '1' unless there are multiple X screens (i.e. running multi-head without Xinerama/RandR.)
Multiple colors are specified with a comma-separated list and markup sequence indexes begin with 0.

So, your example should be:
```
bar_font[1]              =  -*-terminus-medium-*-*-*-14-*-*-*-*-*-iso10646-*
bar_color[1]             =  midnightblue,red
bar_font_color[1]        =  green,red
bar_format               =  +@fg=1;+S+@bg=1;+I+@stp;
bar_action_expand        =  1
```

**Comment by qsmodo** [comment]
Thank you for your guidance, LordReg, I confirm it works that way.
