### ISSUE TITLE
Can't De-iconify?

### ISSUE THREAD

**Issue by DrakoDom** [conformal/spectrwm#441]
I've gotten pretty far along with my configuration so far, I just have a little more configuration to go. Including figuring out how to deiconify windows that I've iconified. There's no keybind for it, so I'm not sure how I should go about doing this.

**Comment by qsmodo** [comment]
You should have missed something in the manual:
```
M-w                 iconify
M-S-w               uniconify
```

**Comment by DrakoDom** [comment]
> You should have missed something in the manual:
> 
> ```
> M-w                 iconify
> M-S-w               uniconify
> ```

Well, I should have been more specific. I did try this keybinding, and I even made sure to set it in my `.spectrwm.conf` file. It did not work though. Not a single program will uniconfify.

**Comment by chaibronz** [comment]
> > You should have missed something in the manual:
> > ```
> > M-w                 iconify
> > M-S-w               uniconify
> > ```
> 
> Well, I should have been more specific. I did try this keybinding, and I even made sure to set it in my `.spectrwm.conf` file. It did not work though. Not a single program will uniconfify.

This is prob a stupid question but have to rule it out.. are you using dmenu, and did you remove or comment out the 'program[search' line under 'Validated default programs'? I had same issue when i first tried spectrwm and used rofi instead of dmenu. Turned out that uniconify uses dmenu to show a list of your iconified windows via the 'program[search]' dmenu command (at least as far as I can tell).

**Comment by DrakoDom** [comment]
> > > You should have missed something in the manual:
> > > ```
> > > M-w                 iconify
> > > M-S-w               uniconify
> > > ```
> > 
> > 
> > Well, I should have been more specific. I did try this keybinding, and I even made sure to set it in my `.spectrwm.conf` file. It did not work though. Not a single program will uniconfify.
> 
> This is prob a stupid question but have to rule it out.. are you using dmenu, and did you remove or comment out the 'program[search' line under 'Validated default programs'? I had same issue when i first tried spectrwm and used rofi instead of dmenu. Turned out that uniconify uses dmenu to show a list of your iconified windows via the 'program[search]' dmenu command (at least as far as I can tell).

I added it back, but when I run it, nothing shows up in dmenu

**Comment by fiesh** [comment]
@chaibronz you really helped me out there -- didn't have `dmenu` installed.
