### ISSUE TITLE
Manpage does not include CONTROL Modifier.

### ISSUE THREAD

**Issue by pspiagicw** [conformal/spectrwm#442]
I searched through the manpage there is no mention of using CONTROL Modifier as keybinding.
The only way of knowing about this is through the source code.
Manpage includes MOD , ANYMOD , REPLAY.
But there is no mention of CONTROL.

**Comment by LordReg** [comment]
The man page doesn't explicitly list all modifier keys, but it makes sense to at least mention Control once, as your PR does.
