### ISSUE TITLE
How to vertical resize?

### ISSUE THREAD

**Issue by Mirocif** [conformal/spectrwm#449]
How can I resize in vertical the windows with keybinds? Because I can resize horizontally but not vertically

**Comment by jpnance** [comment]
Just hold the shift key. By default, `Mod +` expands a window horizontally and `Mod Shift +` expands it vertically. `Mod -` and `Mod Shift -` contract the window horizontally and vertically, respectively. The actions involved are `width_grow`, `width_shrink`, `height_grow`, and `height_shrink`, so you can reconfigure them if you like.

**Comment by Mirocif** [comment]
Nope, it still doesn't work, I tried to change the keys but it doesn't want to work

**Comment by chaibronz** [comment]
Those commands only work on floating windows. For tiled windows you can only re-size the stack horizontally. I've seen a few requests for vertical re-size in tiling mode but don't think it is something that's within the scope of this project (though I hope to be proven otherwise!).

**Comment by Mirocif** [comment]
ah ok, i hope so, thank you very much for the reply
