### ISSUE TITLE
Feature Request: Ignore Window

### ISSUE THREAD

**Issue by Cadair** [conformal/spectrwm#45]
In xmonad there is an option to tell the WM to completely ignore a window, this is useful for tray bars etc. It means that it is not in the Mod + tab sequence, or resizeable or moveable at all, it goes where it wants and stays there.

Would such a feature be implementable?

**Comment by marcopeereboom** [comment]
You can specify regions and stuff.  There is a bunch of talk on forums etc on how to do this.
