### ISSUE TITLE
Baraction glyphs not rendering correctly

### ISSUE THREAD

**Issue by meiuwa** [conformal/spectrwm#450]
As the title says, glyphs in baraction.sh are not rendered correctly. Usually, I could use the `+@fn=n` markup directly in the `bar_format` field to select the corresponding font for the glyphs, but I'm handling the glyphs dynamically using scripts so they're not rendered correctly in the bar, even if `bar_font_pua` is defined in the config file.

### Current status

Glyphs are rendered as blank rectangles in the bar.

### Expected result

Should be rendered correctly if fonts are properly defined in the config file.

## Steps to reproduce

O.S: Arch Linux
Spectrwm: latest git version

1. Install [Material Design Icons](https://github.com/Templarian/MaterialDesign-Webfont) font:

```bash
curl -L https://github.com/Templarian/MaterialDesign-Webfont/raw/master/fonts/materialdesignicons-webfont.ttf -o ~/.fonts/MDI.ttf --create-dirs
```

2. Clone spectrwm repo:

```bash
git clone https://github.com/conformal/spectrwm
```

3. Build using `makepkg`:

<details><summary>PKGBUILD (custom recipe)</summary>

```bash
pkgname='spectrwm'
pkgver=3.4.1.r16.g92589af
pkgrel=1
pkgdesc='Dynamic tiling window manager for X'
arch=('x86_64')
url='https://github.com/conformal/spectrwm'
license=('ISC')
makedepends=('git')
depends=('xcb-util' 'xcb-util-wm' 'xcb-util-keysyms' 'libxrandr' 'libxft' 'libxt' 'libxcursor')
optdepends=('terminus-font: Default bar font')

pkgver() {
	cd "$startdir"
	git describe --long | sed -E 's/SPECTRWM_//;s/([^-]*-g)/r\1/;s/_|-/./g'
}

build() {
	cd "$startdir/linux"
	make PREFIX=/usr
}

package() {
	cd "$startdir/linux"
	make PREFIX=/usr DESTDIR="$pkgdir" install
	install -Dm0644 ../LICENSE.md "$pkgdir/usr/share/licenses/$pkgname/LICENSE"
}
```

</details>

4. Test the example configurations:

<details><summary>spectrwm.conf (bar settings)</summary>

```
...

# Bar Settings
bar_enabled			= 1
bar_font			= Terminus:pixelsize=16:antialias=true
bar_font_pua			= Material Design Icons:pixelsize=16:antialias=true
bar_action			= ~/baraction.sh
bar_action_expand		= 1
bar_format			= +|L+L +|C+A +|R
clock_enabled			= 0

...
```

</details>

<details><summary>baraction.sh (example)</summary>

```bash
#!/bin/bash
while :; do
	case $(date +'%I') in
		00) clock="󱑊";;
		01) clock="󱐿";;
		02) clock="󱑀";;
		03) clock="󱑁";;
		04) clock="󱑂";;
		05) clock="󱑃";;
		06) clock="󱑄";;
		07) clock="󱑅";;
		08) clock="󱑆";;
		09) clock="󱑇";;
		10) clock="󱑈";;
		11) clock="󱑉";;
		12) clock="󱑊";;
	esac
	date +"$clock %I:%M %p"
	sleep 60
done
```

</details>

**Comment by LordReg** [comment]
`bar_font_pua` currently only applies to the code point range U+E000 to U+F8FF.
The clock glyphs in your script have code points U+F143F to U+F144A, so `bar_font_pua` doesn't apply.
Perhaps ```bar_font_pua``` should be extended to cover the Supplementary Private Use Areas as well, but for now you can use markup directly in your script output to select the font. e.g.:
spectrwm.conf:
```
...
bar_font = Terminus:pixelsize=16:antialias=true,Material Design Icons:pixelsize=16:antialias=true
...
```
baraction.sh:
```sh
...
date +"+@fn=1;$clock+@fn=0; %I:%M %p"
...
```

**Comment by meiuwa** [comment]
@LordReg Thank you. That solved the issue. However, the current solution won't be portable for scripts if you're using multiple WMs with the same bar behavior like dwm or a custom bar like Polybar.

About the code point range, it has to be extended to support all kinds of glyphs. In dwm, one could just specify the font list in the config and it'll just work (a fallback font mechanism which is the expected behavior). `bar_font_pua` should do the same thing, else it'll be unnecessary to define it in the config.
