### ISSUE TITLE
[Question] Keybind to refresh the bar

### ISSUE THREAD

**Issue by Nidrop** [conformal/spectrwm#452]
Is it possible to update the bar on keybind?
I have a poor perfomance netbook and battery life is important too. Also i rarely keep the bar opened.

**Comment by LordReg** [comment]
It's not currently possible and the impact on battery/performance of such a feature would be negligible as the bar isn't constantly updated.
Also, having the bar disabled (toggled off) does stop it from being updated, so enabling the bar only when you want to see it has a similar effect.

**Comment by Nidrop** [comment]
But `top` shows that the script continues to execute when the bar is hidden. Is this considered as a bug? It would be enough for me if script didn't do that

**Comment by Nidrop** [comment]
The question is answered. 
But again the baraction.sh is executed when the bar is hidden. Tested with `stress -t 3` every 10 seconds in baraction.sh.
IDK how it implemented in sway but there `stress` executed only when the bar is shown at configuration `mode hide` and `hidden_state hide` (bar displays when a key is pressed)
