### ISSUE TITLE
FontAwesome Unicode Characters Not Rendering in Bar

### ISSUE THREAD

**Issue by SwayamShree123** [conformal/spectrwm#457]
While rendering unicode characters in the bar only some characters render successfully while others do not. 

OS: Ubuntu 21.04
Spectrwm Version: 3.4.1-1
fonts used: UbuntuMono and FontAwesome 
[spectrwm config file](https://github.com/SwayamShree123/Linux_Files/blob/master/.spectrwm.conf) 

[baraction.sh](https://github.com/SwayamShree123/Linux_Files/blob/master/baraction.sh) 

![2021-05-28-181318_1366x768_scrot](https://user-images.githubusercontent.com/55718345/120080365-90a7d180-c086-11eb-8239-3958a1d954d9.png)

**Comment by LordReg** [comment]
The fonts might be listed differently on your system. Try checking the output of `fc-list` to verify the naming.
For me, FontAwesome is listed as "Font Awesome 5 Free" and UbuntuMono as "Ubuntu Mono".

**Comment by SwayamShree123** [comment]
I changed my font to ubuntu mono nerd font and that solved the issue
