### ISSUE TITLE
Window order gets modified after fullscreen toggle

### ISSUE THREAD

**Issue by levaidaniel** [conformal/spectrwm#46]
I start an application that can go into fullscreen, eg.: mplayer or mpv, or whatever.
First eg. mpv starts in its floating window, plays its stuff... and then, I start another floating  window application, lets say a volume mixer. So now the new window will be on top of mpv, and that is correct, because the new mixer window got created later than the mpv window.
But, after I toggle mpv's fullscreen on and off (or, as a matter of fact, toggle maximize on/off), the order gets modified, and now mpv is on top, and the mixer is hidden behind the mpv window. I think the window order should stay the same, no matter how one fiddles around with the windows.

**Comment by marcopeereboom** [comment]
We need proper floating support.

**Comment by Mariappan** [comment]
hi @marcopeereboom Is there a plan to implement floating support ??

**Comment by marcopeereboom** [comment]
Yes there is a plan for that.  However there is no timeline for it.
