### ISSUE TITLE
xfreerdp window click and drag doesn't work in spectrwm

### ISSUE THREAD

**Issue by gitbxf4** [conformal/spectrwm#462]
I am having the problem described here:

https://github.com/FreeRDP/FreeRDP/issues/6948

and I just found that if I use bspwm, instead of spectrwm, the problem doesn't happen. So perhaps it is in how spectrwm is sending mouse activity?

**Comment by LordReg** [comment]
Unable to reproduce on 5b7298872e00aa23ba9fe7eb9a219296a98760ac with FreeRDP 2.4.1 or 2.3.2. Reopen if its still an issue.
