### ISSUE TITLE
Changing regions without restarting the wm (polybar)

### ISSUE THREAD

**Issue by oroszadam12** [conformal/spectrwm#468]
I'm using polybar with spectrwm, and I love this setup, except that I had to set my regions to 1920x1045 instead of 1920x1080 for the panel, and if I make a game or browser fullscreen, I can't hide the bar. If someone knows another workaround for this, that's fine for me too.

**Comment by ZaxonXP** [comment]
Looks like this [hack](https://dev.to/psiho/how-to-toggle-polybar-on-spectrwm-tiling-wm-3o3d) can work.

**Comment by oroszadam12** [comment]
Thanks! I am no longer using polybar, but this seems like a good solution if I ever want to go back.
