### ISSUE TITLE
Unable to change default key binding

### ISSUE THREAD

**Issue by plus9a** [conformal/spectrwm#469]
**I changed the Post topic**

**Comment by kazi-sifat-plus9a** [comment]
Ah ... after changing kernel it started working ... But it isn't it a strange problem ?

**Comment by kazi-sifat-plus9a** [comment]
But i got another strange problem it is a bug..
My mouse continuously pressing middle point of monitor

**Comment by kazi-sifat-plus9a** [comment]
Uploading VID_20210821_221155.mp4…

**Comment by kazi-sifat-plus9a** [comment]
https://drive.google.com/file/d/1M_U3keKxyEE7yvAG5bnwZpzyN5WRlTH9/view?usp=drivesdk

**Comment by joelchrono12** [comment]
> But i got another strange problem it is a bug..
> My mouse continuously pressing middle point of monitor

Thats not a bug perse, just go to you configuration file and change `focus_mode` to `

**Comment by kazi-sifat-plus9a** [comment]
Yes.. i fixed that. 
www.paste.rs/Zzp
Now there is a problem there is no key binding such as MOD + 1, i replaced with mod + a. But still 1 is working why?!?.

What i tried to fix that problem is,
I noticed there is a file on /etc/spectrwm/spectrum_us.conf 

I removed that folder rm /etc/spectrwm/*

Still all of that key binding is working.

Is it a Bug?

**Comment by joelchrono12** [comment]
> Yes.. i fixed that.
> [www.paste.rs/Zzp](http://www.paste.rs/Zzp)
> Now there is a problem there is no key binding such as MOD + 1, i replaced with mod + a. But still 1 is working why?!?.
> 
> What i tried to fix that problem is,
> I noticed there is a file on /etc/spectrwm/spectrum_us.conf
> 
> I removed that folder rm /etc/spectrwm/*
> 
> Still all of that key binding is working.
> 
> No such dir like /etc/xdg/spectrwm/spectrwm
> Is it a Bug?
Its not a bug, to unbind keys, you have to creste an empty binding

```conf
bind[] = MOD+1
```
