### ISSUE TITLE
How can i set a dropdown terminal inside spectrwm?

### ISSUE THREAD

**Issue by plus9a** [conformal/spectrwm#470]
I am using tilda dropdown terminal. I didn't did anything to my config but by default it start in floating mode.
But the Problem is it pop up middle of the screen i want to set it down side of my monitor ,i can't control Tilda Y position (or you can say hight) from it preference.

How can i config it from my spectrum config?

**Comment by bazeeel** [comment]
Hi  i use tdrop for dropdown terminal

**Comment by kazi-sifat-plus9a** [comment]
Did you found any solution?¿

**Comment by bazeeel** [comment]
no,i use tdrop like that  tdrop -ma -w 940 -h 540 -x 400 -y 400 urxvt
and its working perfectly
