### ISSUE TITLE
Quirks based on which desktop they are on, also forcing programs and children to load on a specific desktop

### ISSUE THREAD

**Issue by roof98** [conformal/spectrwm#471]
Howdy. 

This is not so much an issue as it is something that I am pretty sure should be doable, but I am cannot see how from documentation. 

The situation: I do a bit of gaming and such. For some reason, some launchers really hate being tiled and will outright break. 

My fix: I would like to make it so that certain offending programs (such as lutris and steam) and the child programs they spawn are forced to only exist on, say, desktop 2 for steam and child programs and desktop 3  for Lutris and its children. Programs open on desktops 2 and 3 get the Everywhere and Float quirks. This would replace having to manually set quirks for each launcher and trying to find their name since they will outright crash if they are tiled. When a title is launched in Lutris or Steam it will typically launch a developer specific launcher which then starts the game so having a 1-shot solution would be pretty minty. 

Any ideas on how to make that happen?

**Comment by c0dev0id** [comment]
Steam/Luitris is not running on my OS, but you can try this to force them to start on a certain workspace.
```
_SWM_WS=2 steam
_SWM_WS=3 lutris
```

**Comment by LordReg** [comment]
floating layout can help with programs that don't like to be tiled.
