### ISSUE TITLE
"xdotool windowmove" can't move a floating window

### ISSUE THREAD

**Issue by wavexx** [conformal/spectrwm#472]
I can resize an existing window with xdotool, however just using "windowmove" doesn't work.

On the other hand, wmctrl -e works as intended, the difference wmctrl is a move+resize operation.

The gravity hint given with wmctrl -e is also ignored, which makes positioning harder than it needs to be (I need to fetch the region coordinates myself)

**Comment by 0ion9** [comment]
Same problem for me, except wmctrl *doesn't* work, the move component always fails whether done by xdotool or wmctrl.

**Comment by 0ion9** [comment]
This still doesn't work. I don't know if it did at some point, but using the `wmctrl` command listed in the man page : `wmctrl -i -r $xid -e 0,100,50,640,480` doesn't do anything (I can change the x,y,w,h values or gravity value, still does nothing). `xdotool windowmove` is similarly non-responsive. (moving the window by click+drag works fine, so I conclude this is still an EXMH-specific issue)

**Comment by LordReg** [comment]
If a window has been manually positioned/resized via mouse/key bindings, EWMH `_NET_MOVERESIZE_WINDOW` requests are ignored unless the `ANYWHERE` quirk is set, the workspace is in floating layout, or the window is workspace-free.

**Comment by 0ion9** [comment]
@LordReg Having dragged the window previously was indeed the issue. Just spawning it and immediately moving it works. I'll have to experiment with those possibilities (which you laid out very clearly, thanks!)
