### ISSUE TITLE
closing an instance of a program closes all instances

### ISSUE THREAD

**Issue by roof98** [conformal/spectrwm#473]
When I have multiple instances of a program (such as Qutebrowser or thunar) open and go to close one with MOD+q all instances close. If there a way to fix that or do a quirk so that each instance is a new PID or something? I have no idea why that would happen.

**Comment by joelchrono12** [comment]
Check out the bindings. There are two different ways to close a window.

`wind_del` will only close the window instace
`wind_kill` is more extreme, so it might close all windows of the same program. 

Just change your keybinding to use `wind_del` and you should be fine.

**Comment by LordReg** [comment]
`wind_del` (default: MOD+x) sends a request for the application to close the focused window. `wind_kill` sends a request for the X server to force a close-down of the client that created the focused window.
