### ISSUE TITLE
Autorun wrong workspace app spawn.

### ISSUE THREAD

**Issue by scynthero** [conformal/spectrwm#475]
So i have this part part of the config:

autorun     = ws[1]:firefox
autorun     = ws[2]:alacritty
autorun     = ws[3]:discord
autorun     = ws[3]:obsidian
autorun     = ws[4]:signal-desktop
autorun     = ws[9]:spotify

And for some reason all apps are starting in workspace 1 is this a known bug or something?
It is happening no matter when and if i set LD_PRELOAD.
It looks a bit like if it was spawning apps where the mouse is.

**Comment by bket** [comment]
@scynthero, have a look at the man page, more precise

```
It is advised to check the man page of ld.so as LD_PRELOAD is
sometimes ignored by some operating systems.  A workaround is
available, e.g. launch an xterm(1) in workspace 2:

  autorun = ws[2]:xterm -name ws2
  quirk[XTerm:ws2] = WS[2]
```

**Comment by poul1x** [comment]
This worked for me

> @scynthero, have a look at the man page, more precise
> 
> ```
> It is advised to check the man page of ld.so as LD_PRELOAD is
> sometimes ignored by some operating systems.  A workaround is
> available, e.g. launch an xterm(1) in workspace 2:
> 
>   autorun = ws[2]:xterm -name ws2
>   quirk[XTerm:ws2] = WS[2]
This worked for me

**Comment by LordReg** [comment]
See the `SWMHACK` section of the manual added in spectrwm 3.5.1 for more details.
