### ISSUE TITLE
Alt key not recognized as a keybinding on german keyboard

### ISSUE THREAD

**Issue by Schweber** [conformal/spectrwm#476]
I am using a german keyboard and am not able to use the Alt key as a key binding for spectrwm.

According to xev my Alt key is named "Alt_L". Neither that, nor Mod1, Mod2 or Mod3 is recognized by spectrwm when i press the Alt key on my keyboard. 

If i define e.g. "Alt+x" as a keybinding, then spectrwm shows an error because Alt is not an allowed key. When i define e.g. "Alt_L+x" instead, then no error is shown, however it still doesn't work.

MOD is set to Mod4 and works, so my Windows/Super key is recognized as Mod4 and all keybindings with MOD work.

I am using spectrwm 3.4.1-1 on Manjaro 5.14.10-1 kernel.

What can i do to fix this issue?

**Comment by LordReg** [comment]
@mschilli87 spectrwm binds keycodes based on the keymap at the time it starts. If you set multiple layouts via `setxkbmap`, spectrwm will search each layout in the specified order to determine which keycodes to grab for each bind.  If you switch layouts after spectrwm starts, the physical key combinations do not change.

**Comment by Schweber** [comment]
Thank you for your help





13. Okt. 2021, 23:28 von ***@***.***:
