### ISSUE TITLE
Swap between current and previous workspace when hitting META+number

### ISSUE THREAD

**Issue by minenwerfer** [conformal/spectrwm#482]
If, let's say, I'm working on workspace 9, and then I have to go back to workspace 1 for look for something constantly, it would be far easier to just press META+9 again than specifying the workspace number every time.

**Comment by panchoh** [comment]
META-a is your friend.

**Comment by c0dev0id** [comment]
This can probably be closed. OP can just  `bind[ws_prior]` to something.

**Comment by minenwerfer** [comment]
> This can probably be closed. OP can just `bind[ws_prior]` to something.

Yes, I ended up using META+a as @panchoh suggested.
Thanks for the reminder and thanks for maintaning this amazing software, gonna close the issue now.
