### ISSUE TITLE
Incorrect workspace ordering in PolyBar

### ISSUE THREAD

**Issue by MaciekChudek** [conformal/spectrwm#484]
[See discussion with a PolyBar developer here](https://www.reddit.com/r/Polybar/comments/qmf0va/weird_workspace_ordering_internalxworkspaces/) for additional context.

Polybar groups workspaces by viewport. Spectrwm reports viewports with the _NET_DESKTOP_VIEWPORT hint as:

* for each active/visible workspace the left corner of the monitor it's on
* for each inactive workspace, 0 (i.e., the left-most monitor)

This results in:

* the left monitor's workspace being grouped with all the inactive workspaces
* the other active workspaces being ordered weirdly and inconsistently, depending on the left-to-right arrangement of users' monitors

Also, this doesn't update when monitors change, but that's another issue (#483). 

I like to have a `workspace_indicator = listall` style of status bar, where all workspaces are visible in numerical order and the active and non-empty ones are highlighted somehow. This is currently not possible with multiple monitors connected, unless they are positioned left-to-right in a very specific way. I suspect the current behaviour is desired by people who prefer to see just the active in the status bar.

Not sure the right way to solve this, but one possibility might be a spectrwm setting that causes all workspaces to be reported as 0 in _NET_DESKTOP_VIEWPORT, for people who prefer it my way?

**Comment by LordReg** [comment]
Is this still an issue since 3.5.1?
