### ISSUE TITLE
spectrwm crash, erractic activity and UI distortion

### ISSUE THREAD

**Issue by andbenn** [conformal/spectrwm#486]
Using arch, mostly up to date, kernel is 5.15.6-arch2-1.

Relatively new spectrwm convert.  Enjoying it.  But getting UI garbage, loops of activity, and essentially a crash/hang.

I use Alt as my mod key.  Four days ago I hit the right Alt and J to move windows, and a vicious loop started which I could not cleanly escape.  Had to ctrl-alt-F2, log in, kill -s HUP didn't work, so had to kill -9.

Yesterday was doing some config tweaks and reloads, and tag flips which also got in a vicious loop and a lot of UI garbage.  My .xsession-errors from that period looks like:

`
(xfce4-terminal:1588248): Gdk-CRITICAL **: 01:13:24.449: gdk_event_set_source_device: assertion 'GDK_IS_DEVICE (device)
' failed
XIO:  fatal IO error 104 (Connection reset by peer) on X server ":0"
      after 93037 requests (93036 known processed) with 0 events remaining.
[1589942:1209/011324.484785:ERROR:connection.cc(66)] X connection error received.
[1589880:1209/011324.485263:ERROR:connection.cc(66)] X connection error received.
[1589942:1209/011324.484711:ERROR:connection.cc(66)] X connection error received.
Exiting due to channel error.
Exiting due to channel error.
`

"Exiting due to channel error" repeats for about 25 times.  I'm not sure this was the time of the glitch, but was the end of that .xsession-errors file.

Hope this helps in some way.  Happy to help debug with some tips and ideas.

**Comment by LordReg** [comment]
Are you running the latest spectrwm git?
Do you have any programs running that might grab keyboard input such as notify?
The 'X connection' errors are from apps that lost their connection to the X server when it shut down after you killed spectrwm.
Also, if you experience the hang again, you should be able to recover by killing the app instead of spectrwm.

**Comment by andbenn** [comment]
I'm using the binary from arch.  It's 3.4.1.

Can we hold this open for a week or so?  I'll close it if it doesn't repeat.

I believe I had migrated to using Spectrwm just as my SSD began to fail.  With a dozen or so file system issues/hangs/crashes, I have to think my spectrwm issues were related.  I put a new drive in yesterday and rebuilt a system at this point.

**Comment by andbenn** [comment]
Resolving.  No issues seen since I replaced my SSD.  How fortunate that I moved to Spectrwm when the issues became more noticeable.  I'll close this.

I'm enjoying Spectrwm.  I've been looking at other WMs but keep coming back.  The simple and minimalist approach, plus hideable status bar, is fantastic.
