### ISSUE TITLE
autostart not respecting workspace

### ISSUE THREAD

**Issue by eko234** [conformal/spectrwm#488]
Hi, I wanted to know if there is a way to give a name to a window so I can define a quirk to make it go to a specific workspace

```
autorun = ws[1]:alacritty
autorun = ws[4]:firefox
autorun = ws[8]:alacritty
autorun = ws[9]:/home/jujo/.config/autom/music.sh
quirk[Alacritty:Alacritty:ws9] = WS[9]
autorun = ws[10]:/home/jujo/.config/autom/wiki.sh
quirk[Alacritty:Alacritty:ws10] = WS[10]

```

I'm trying to do this but it wont work, I need those specific instances of alacritty to go to their respective workspaces, how can I do this?

**Comment by LordReg** [comment]
Applications set the name/title of their own windows. Alacritty allows you to override the window title via the `-t` flag.

Try this:
```
quirk[Alacritty:Alacritty:ws2] = WS[9]
autorun = ws[9]:alacritty -t ws9
```

**Comment by eko234** [comment]
oh, thanks, didn't know that. :)
