### ISSUE TITLE
Purpuse of window_{name, instance,class} settings

### ISSUE THREAD

**Issue by hackedWifi** [conformal/spectrwm#489]
I really don't understand the need for those settings. If you have them already in the bar_format as +C +W +P, setting window_{name, instance, class} = 0. The bar still show them. I will think that those settings will restrict the output of an already +C, +P or +W. But it does not. Like to avoid a modification of them manually in the bar_format. Is this a bug?

`spectrwm 3.4.1 Build: 5b7298872e00aa23ba9fe7eb9a219296a98760ac
Linux xps-gentoo 5.10.76-gentoo-r1 #3 SMP 
Thu Dec 23 17:12:20 PST 2021 x86_64 
Intel(R) Core(TM) i7-6700HQ CPU @ 2.60GHz GenuineIntel GNU/Linux
`

**Comment by LordReg** [comment]
Those settings affect the defaults and only apply when not using `bar_format`. They existed before `bar_format` and remain for convenience/backwards compatibility.
