### ISSUE TITLE
Feature Request: Application in all workspaces

### ISSUE THREAD

**Issue by developer1105** [conformal/spectrwm#491]
The dzen2 bar appears in all workspaces when it is not in dock mode. But when it is in dock mode, it appears only on the first workspace. 

Maybe if spectrwm had a way to put an application in all workspaces, maybe dzen2 in dock mode could appear in all workspaces. 

In dock mode, dzen2 disappears when fullscreen applications are running. In the normal mode, dzen2 appears over the fullscreen applications.

This could be implemented as a quirk.
# the application is in all workspaces
quirk[dzen:dzen2]=ALLWORKSPACES
#or 
# will always appear in the active workspace
quirk[dzen:dzen2]=APPEARINACTIVEWS 

With this feature, the application would move into the new workspace as the user enters it.

**Comment by c0dev0id** [comment]
That would probably be fulfilled by https://github.com/conformal/spectrwm/issues/330
