### ISSUE TITLE
Update the man pages on configuration files

### ISSUE THREAD

**Issue by RayZ0rr** [conformal/spectrwm#493]
The [configuration files](https://htmlpreview.github.io/?https://github.com/conformal/spectrwm/blob/master/spectrwm.html#CONFIGURATION_FILES) of the [manpages](https://htmlpreview.github.io/?https://github.com/conformal/spectrwm/blob/master/spectrwm.html) need to be updated after this PR https://github.com/conformal/spectrwm/pull/260

**Comment by LordReg** [comment]
The HTML manual has been updated.
