### ISSUE TITLE
Spectrwm doesn't run, no errors in xorg logs and no .xsession-errors.

### ISSUE THREAD

**Issue by Maybegus** [conformal/spectrwm#494]
Trying to launcher spectrwm from either xinit or lightdm does not work, X server shuts down with no errors. There are also no errors in xorg logs and there is no .xsession-errors generated.

**Comment by c0dev0id** [comment]
.xsession-errors does not capture everything. Try to start spectrwm with "spectrwm > ~/spectrwm.log 2>&1" and then examine this log file.

**Comment by Maybegus** [comment]
Issue was caused by unavailable fonts for the status bar, fixed by changing font in config file.
