### ISSUE TITLE
on login/spectr-load: tiling mode switch unavail. (MOD+SPC); FIXED after MOD+q

### ISSUE THREAD

**Issue by rene-tobner** [conformal/spectrwm#497]
Version: 3.2.0-1 on Debian Buster

**Comment by rene-tobner** [comment]
mod space not working, help:
.xsession:
```bash
# [...]
sleep 1
exec spectrwm
```
But, to sleep one second to get this setting done... my bad?! How to get to the bottom of this?

**Comment by LordReg** [comment]
The issue is the same as #498
