### ISSUE TITLE
on login/spectr-load: /etc/default/keyboard option ctrl:swapcaps not honored

### ISSUE THREAD

**Issue by rene-tobner** [conformal/spectrwm#498]
FIX with setxkbmap -option ... with xterm bash
strange thing: before I set that option setxkbmap -query reports the option to be set. :(

I really love spectr as lean xmonad alternative, but such things really drive me nuts. :(

Package: spectrwm
Version: 3.2.0-1
Debian Buster

**Comment by LordReg** [comment]
This appears to be the same issue as #497 and https://github.com/conformal/spectrwm/issues/310#issuecomment-621158723
spectrwm uses the core X protocol for keyboard support. When X starts, Xkb options may not propagate to the core keyboard mapping until triggered by input activity, running Xkb applications, etc.

One way to ensure the core mapping is updated is to run `setxkbmap` before spectrwm in your .xinitrc/.xprofile.

**Comment by rene-tobner** [comment]
I finally got it working:
display/login manager: default session
.xsession:
```bash
setxkbmap -option "ctrl:swapcaps"
sleep 1
exec spectrwm
```
First, well the default session to pick up .xsession...
But, to sleep one second to get this setting done... my bad?! It also solved my other ticket, workaround... to get to the bottom of this?

**Comment by LordReg** [comment]
Did you try setting *all* Xkb options with `setxkbmap` before `exec spectrwm`?
You can verify what keymap spectrwm sees when it starts by doing something like this in your `.xsession`:
```
setxkbmap -option "ctrl:swapcaps"
xmodmap -pke > ~/xmodmap.txt
exec spectrwm
```

**Comment by rene-tobner** [comment]
I checked the setting before with setxkbmap -q, was alright.
Now, with xmodmap -pke:
```sh
keycode  66 = Control_L NoSymbol Control_L
```
alright, too.
But when my xterm is ready, without adding something to bashrc, no desired effect.
The default /etc/keyboard has ctrl:swapcaps, I always want this effect. I don't know where else it might be changed.
Clueless for quite a while...

**Comment by LordReg** [comment]
Is that the output *before* `exec spectrwm`?

**Comment by rene-tobner** [comment]
Sorry for the noise. Please close issue.
I had to configure lightdm the right way:
https://wiki.archlinux.org/title/LightDM#X_session_wrapper
subheading keymap ...
