### ISSUE TITLE
Hide underlying windows when one window is max

### ISSUE THREAD

**Issue by rene-tobner** [conformal/spectrwm#499]
I use compton only for xterm opacity. Having 2 xterms: making one "fullscreen" or better maximal size (mod+space until one xterm occupies the whole screen), THEN written stuff in the underlying xterm shines through, opacity adding to adding blur to my wallpaper. Mostly about the written stuff: Distracting!

Could it be easy to implement to hide underlying windows? A possible default? I think it is like so in Xmonad.

**Comment by LordReg** [comment]
Did you try running the latest spectrwm?
Max layout has done that since since 3.4.0.

**Comment by rene-tobner** [comment]
I compiled from source 3.4.x,
but when I run it:
- my autorun xterm does not start
- exception: cannot find xlock

spectrwm in /usr/local/bin
libswmhack.so.0.0 in /usr/local/lib

**Comment by LordReg** [comment]
What is your autorun command? If `autorun = ws[1]:xterm` doesn't work, then xterm might not be in spectrwm's PATH. spectrwm inherits the PATH of `exec spectrwm` and executes spawn programs directly, not via a shell.

Also, as stated in the PROGRAMS section of the man page, spectrwm validates the default programs: `xterm`, `xlock`, `dmenu`, and `dmenu_run`. Validation is done using `which`, so make sure it's installed and in spectrwm's PATH. If you don't want to use xlock, you can change `program[lock]` to a different program or unbind the `lock` binding to disable the `lock` action its validation.

**Comment by LordReg** [comment]
Solved with `maximize_hide_other` and `fullscreen_hide_other` in spectrwm 3.5.0.
