### ISSUE TITLE
Spectrwm switching to wrong window in maximized layout.

### ISSUE THREAD

**Issue by ZaxonXP** [conformal/spectrwm#504]
When I have some application already opened (let say web browser) and I open PCManFM file manager to change the name of the file, then the pop up window is opened allowing the file name change. After changing the file name and closing the pop-up window I would expect to see the PCManFM window. Instead spectrwm switches to web browser.

Is there any quirk to be set up in order to make this work correctly (switching to PCManFM)?

Kind regards,
Piotr

**Comment by levaidaniel** [comment]
@ZaxonXP Would you mind checking if #510 describes your problem as well?

**Comment by ZaxonXP** [comment]
@levaidaniel: Indeed. What you described in #510 is exactly what my issue was. O I guess I will close this as a duplicate.
