### ISSUE TITLE
focus_close=previous should return to *previous* window

### ISSUE THREAD

**Issue by levaidaniel** [conformal/spectrwm#510]
So I've been playing around with focus_close, because I wanted to make spectrwm switch back to the _parent_ window after e.g. a modal window is closed. For instance, in a file manager I'm creating a new directory, it opens a tiny modal window to enter the directory's name, while leaving the _main_ file manager window open in the background.

If there are already multiple windows open on the workspace (not just the file manager), after closing the popup/modal window the focus doesn't switch back to the original (let's say _source_) window, instead it's switched to the **previous** window **relative** to the originating/main file manager window (e.g. the browser window right next the file manager).
Confusing as the window that's been closed was the popup/modal window, and relative to that the **previous** window was the originating one, the _parent_ file manager window.

Imagine another scenario with a file manager where I open a PDF document, so it opens a document viewer next to the file manager window. When I focus the document viewer and try to print the file, it opens the printing dialog and when I click print (i.e. close the printing dialog) the focus doesn't switch back to the document viewer where it should, instead the focus goes back to the file manager window -- because it's the "previous" (as in "next to") window, relative to the document viewer.

So I guess I understand the point of `focus_close`, and its settings (next/last/previous/first) work fine with single window applications, while it's handling child/popup windows it's rather counterintuitive.

p.s.: I _guess_ #504 kind of wants to allude to the same culprit, however I'm not so sure.

-- 
Dani

**Comment by LordReg** [comment]
This looks the same as #504 and #384, which are fixed. `focus_close` doesn't apply to transient windows. When closing transient windows, focus should go to the main/parent window, unless `focus_mode = follow` and the pointer window has priority.
