### ISSUE TITLE
Color the current workspace

### ISSUE THREAD

**Issue by cloudhead** [conformal/spectrwm#515]
`dwm` supports coloring the current workspace by default in addition or instead of setting a mark:
<img width="286" alt="image" src="https://user-images.githubusercontent.com/40774/209587254-df90df99-a78b-4ef6-b634-b42579307657.png">

Is this possible with spectrwm? I've looked through the entire manual but can't find anything that would let me set fg/bg colors based on the workspace status.

**Comment by LordReg** [comment]
It is possible. Markup sequences can be added in the `workspace_mark_` options. Since there is no termination, marks should be enabled and styled for each workspace status that is included in the list. Also, style should be set following `+L` in `bar_format`.
For example:
```
bar_font_color[1] = rgb:a0/a0/a0, rgb:ff/ff/ff
workspace_indicator = listcurrent,listactive,markcurrent,markactive,printnames
workspace_mark_current = '+@fg=1;*'
workspace_mark_active = '+@fg=0; '
bar_format = +|T+V+S+L+@fg=0; {+M}[+F] +W+|R+A | %a %y-%m-%d %R
```

**Comment by cloudhead** [comment]
Ahh, interesting, thanks. I suppose the `workspace_mark` feature hasn't been released yet right? I will try from master.

**Comment by cloudhead** [comment]
Thanks, managed to recreate my old setup!

<img width="1920" alt="image" src="https://user-images.githubusercontent.com/40774/209840346-11f8e8e6-dfb8-44ad-9770-4a6ca7e6a3cd.png">

**Comment by wavexx** [comment]
@cloudhead could you share the config? I'm curious

**Comment by cloudhead** [comment]
Sure, it's essentially:
* spectrwm.conf: https://github.com/cloudhead/dotfiles/blob/master/.spectrwm.conf
* .conkyrc: https://github.com/cloudhead/dotfiles/blob/master/.conkyrc
