### ISSUE TITLE
Opening Onlyoffice causes its crash

### ISSUE THREAD

**Issue by ZaxonXP** [conformal/spectrwm#516]
Did any one of you managed to use [Onlyoffice](https://www.onlyoffice.com/)?

When I try to open it from terminal under spectrwm I get segmentation foult:
```
onlyoffice-desktopeditors
QLayout: Attempting to add QLayout "" to CTabBarWrapper "tabWrapper", which already has a layout
Segmentation fault
```

Kind regards,
Piotr

**Comment by mschilli87** [comment]
I downloaded [their latest Appimage](https://github.com/ONLYOFFICE/appimage-desktopeditors/releases/download/v7.2.1/DesktopEditors-x86_64.AppImage) and can confirm the segfault:

```
QLayout: Attempting to add QLayout "" to CTabBarWrapper "tabWrapper", which already has a layout
zsh: segmentation fault  ./downloads/DesktopEditors-x86_64.AppImage
/tmp/.mount_DesktoR6QbJW/usr/bin/editors_helper: error while loading shared libraries: libgraphics.so: cannot open shared object file: No such file or directory
```

Not sure if this is a bug on their end or in spectrwm though or why you seem to think the latter is the case.

I'm on Gentoo Linux using spectrwm 3.4.1.

**Comment by ZaxonXP** [comment]
I am not sure either. I tried from other tiling manager (bspwm) and over there there is no crash, but proper app opening. 
So that is why I posted my finding here as it could be that `spectrwm` has some issue with that app.
Also I wanted to know if it is only on my setup or someone else also cannot run the onlyoffice.

**Comment by LordReg** [comment]
On latest Arch Linux, it segfaults on every other WM I tried (dwm, xfce4, i3, twm, awesome, bspwm) and also on KDE and Gnome on Wayland. The window sometimes shows some buttons before it segfaults.
The same thing happens when run on a bare X session, without a WM.
I think it is safe to say it isn't a WM issue.
