### ISSUE TITLE
dmenu sometimes opening on the wrong region with multiple screens

### ISSUE THREAD

**Issue by wavexx** [conformal/spectrwm#517]
Noticed the following on 67e16a136e505832bcd6322c02de28a8adc0af93:

- Have at least two screens
- Say you're in screen 1, then ...
- Close all windows on all screens
- Move to screen 2
- Start dmenu-run: it still opens on screen 1

Noting that: the status bar is correctly updated, and opening a new regular window will start on screen 2 as expected).

It's only a problem when there are no windows to focus (I guess the current focused screen is not updated in such case).

**Comment by LordReg** [comment]
dmenu checks the input focus window to determine the current monitor. When the focused region is empty, input focus should go to a window in the region. Fixed.
