### ISSUE TITLE
Request: Sticky workspaces

### ISSUE THREAD

**Issue by pablokbs** [conformal/spectrwm#52]
Already posted on the forums (https://opensource.conformal.com/fluxbb/viewtopic.php?id=910)

Using 2 monitors

When I'm on screen 1, if I hit Mod+2, instead of getting the second ws of screen 1, the screens just swap.

It would be nice if I we can have an option to get static workspaces, as most WM do.

This is the only reason I'm not using spectrwm right now.

**Comment by marcopeereboom** [comment]
I get the need and will accept a well written PR for this.
