### ISSUE TITLE
Firefox 110 video buttons overlay no more working

### ISSUE THREAD

**Issue by cspadacini** [conformal/spectrwm#521]
With Firefox 110 clicking on the "picture-in-picture" overlay button the video is stopped. On Youtube, clicking on "watch later" or "add to queue" buttons will immediately start the video,  while other buttons on a running video bottom line seem to have no problem.

This doesn't happen when running a different window manager or a previous version of Firefox.

Nothing is logged to the xorg log.

Anybody else experiencing this?

Running spectrwm 3.4.1.

**Comment by LordReg** [comment]
This is actually an ICCCM compliance issue in some applications. A compatibility workaround has been added since 3.4.1, so
I suggest building/running the latest git master. Firefox/Youtube should work fine.

**Comment by cspadacini** [comment]
Thanks. I've built the latest source code, and now Firefox is working fine.
