### ISSUE TITLE
Roll release

### ISSUE THREAD

**Issue by marcopeereboom** [conformal/spectrwm#523]
@LordReg since I can't find you on irc I am trying this :-)

Are we ready to roll a release?

It is time...

**Comment by LordReg** [comment]
@marcopeereboom yo, can't find me on irc? I'm always on irc ;)

Yeah, been ready to roll a release. Just have a couple features to merge first along with the changelog.

You may have noticed I got a bunch of huge fixes/improvements in around Christmas. Thought maybe that would get you to show up in irc :P..  actually, been wanting to confirm whether you are cool with me adding features/rolling releases. Would have released but didn't want to go that far without checking with you first.

If you are cool, i'll get some features in and prepare the release.
Btw, got some neat things for after release. :)

**Comment by forscht** [comment]
Where are we on release yet?

**Comment by forscht** [comment]
Hello?

**Comment by 0323pin** [comment]
It has been 3 years now.
Soon??

**Comment by mschilli87** [comment]
@marcopeereboom said it will happen. If it's not fast enough for you, consider stopping to pay for spectrwm. If you didn't pay anything so far, then please let people working for you for free in their spare time to do so on their own pace.

**Comment by 0323pin** [comment]
> @marcopeereboom said it will happen. If it's not fast enough for you, consider stopping to pay for spectrwm. If you didn't pay anything so far, then please let people working for you for free in their spare time to do so on their own pace.

Now, that was a rather unpolite answer. I didn't mean it that way but, sometimes written messages loose context.
I do open-source work myself and it was not my intention to put any pressure, just curious.

**Comment by mschilli87** [comment]
@0323pin: Sorry if I came across rude. It was not my intention. By itself I don't find your comment inappropriate but in the context if the previous messages I do not think it adds anything. Still, if my reply offended you I owe you an apology. I'll hide my off-topic posts because they don't add anything to the discussion and I encourage everyone else to do the same.

**Comment by marcopeereboom** [comment]
Tracked in #527

**Comment by LordReg** [comment]
https://github.com/conformal/spectrwm/releases/tag/SPECTRWM_3_5_0
