### ISSUE TITLE
Document _SWM_WS

### ISSUE THREAD

**Issue by 0ion9** [conformal/spectrwm#525]
AFAICS, `_SWM_WS=N $program $args` is the only way currently to launch a program on desktop N, without either:
* occurring at Spectrwm startup (`autorun`)
* or fixed application for all instances of $windowname (`quirk[...]`)

Using this makes it much easier to launch programs on other desktops dynamically, but it isn't documented in the manpage or wiki as far as I can see.

**Comment by c0dev0id** [comment]
I learned something from this issue. It's nice that I can start a video player on the new "free" desktop, by prepending the command with `_SWM_WS=-1`. That's quite handy.
