### ISSUE TITLE
[Feature request] Next window will float

### ISSUE THREAD

**Issue by vuokko** [conformal/spectrwm#526]
As much I love spctrwm, it makes designing GUIs little bit hard as it stretches them. After all it is a tiling WM

What I would like to do is give some shortcut which would tell spectrwm to float next showed window and then start my program and when it is run, it would be floating and in size it asked.

**Comment by View-my-Git-Lab-krafi** [comment]
you mean i can change X,Y position ?

**Comment by LordReg** [comment]
This can now be done by switching to the new floating layout.
