### ISSUE TITLE
Gap when increasing bar border's width while placing it at the bottom

### ISSUE THREAD

**Issue by boormanthechauffeur** [conformal/spectrwm#536]
Hi,

in previous versions I used the `bar_border_width` to vertically (and horizontally) pad the text in the bar so I could create some space between it and the bar's borders. But when I updated spectrwm's version from the previous to the current one (3.5.0), I noticed that, when I increased the value in `bar_border_width` to `4`, while enabling the `bar_at_bottom` option, it left a gap between the border and the bottom of the screen. Like so:

![2023-10-29_10-46](https://github.com/conformal/spectrwm/assets/149300526/6571ad35-633b-4159-b1a9-5b327cbdba50)

However, this doesn't happen when I disable the `bar_at_bottom` option:

![2023-10-29_10-49-top](https://github.com/conformal/spectrwm/assets/149300526/8b9d00ba-cee1-4362-b2bb-c0b0911be9c8)

Is it something on my end? I don't remember changing anything outside of spectrwm.conf, to be honest.

If it helps, here's some possibly relevant information about my system:
- Display server: X
- Terminal: Kitty
- Distro: Arch Linux
- I only have one monitor

Not sure if there's anything more I should mention.

Thanks in advance.

**Comment by LordReg** [comment]
This is fixed in master 080defda39c25a398c2e8220715c6e9165b139f8 and will be included in 3.5.1.
