### ISSUE TITLE
Maybe a `bar_font_color_free` option is missing?

### ISSUE THREAD

**Issue by levaidaniel** [conformal/spectrwm#550]
While using multiple regions (two displays) I set this up for my `bar_[font_]color` options, to have a kind of inverse effect on a text in the bar:
```
bar_font_color          = rgb:999/999/999,rgb:000/000/000
bar_font_color_unfocus  = rgb:999/999/999,rgb:999/999/999
bar_color               = rgb:000/000/000,rgb:999/999/999
bar_color_unfocus       = rgb:000/000/000,rgb:000/000/000

bar_format              = +@fn=1;+@bg=1;+@fg=1;hostname
```

This sets things up so when I have a region focused, it shows:
![focused](https://github.com/conformal/spectrwm/assets/1006712/270e0b2d-245b-4734-8f8a-c917f4cd4426)

...and when one region is not in focus:
![unfocused](https://github.com/conformal/spectrwm/assets/1006712/14ca7acf-0813-4af1-a4db-4e58162c67bc)

However, when I focus a **free** window, this text is _invisible_ in a sense that it has the same font/bg color, seemingly (all other `*color` and `*free` parameters are on their default values):
![focused_free](https://github.com/conformal/spectrwm/assets/1006712/69bbda11-a5ed-42e7-80bb-8cffae3154f6)

I can set the color-fill for this text - when a **free** window is focused - with `bar_color_free`, and the color changes (e.g. `rgb:999/000/000` makes it completely red), but another parameter seems to be missing to set up the _font_ color separately, when dealing with **free** windows.

**Comment by c0dev0id** [comment]
`bar_font_color_free` and `bar_color_free` do exist.

However, `fg=X` always refers to `bar_font_color` and `bg=X` always refers to `bar_color`.

I don't think the additional lines on `*_unfocus` are having an effect.

**Comment by levaidaniel** [comment]
Yes, `bar_color_free` does exist, I mentioned I tried using it. There's no mention of `bar_font_color_free` in `spectrwm(1)`, grepping for it in the source does seem to yield some things, though.

But having `_free_unfocused` wouldn't make much sense, as there's no _unfocused_ bar for _free mode_, per se. It just switches back to the "regular" bar colors when you unfocus a free window while focusing on another region.
 
Anyway, having tried `bar_font_color_free`, it works perfectly fine when defining a second item in the list.

This is just something that's missing from the man page.
