### ISSUE TITLE
[FEATURE REQUEST] Vertical re-size in tiling mode

### ISSUE THREAD

**Issue by xplshn** [conformal/spectrwm#551]
That's it, could we get vertical re-size in tiling mode? It'd be a pretty nifty feature to have. To be on par with other WMs like I3 and Sway.

**Comment by Randoragon** [comment]
I'm just a random passerby, not a maintainer, but sounds like you're confusing manual tiling WMs with dynamic tiling WMs. i3 and sway are manual, spectrwm is dynamic. In dynamic tilers, windows follow layout rules and you shouldn't be able to tweak their size individually. I think what you're describing would be an anti-feature, and possibly a nightmare to program.

**Comment by xplshn** [comment]
I am not sure. But I am closing this issue anyways, as it is a duplicate of: https://github.com/conformal/spectrwm/issues/551

**Comment by Randoragon** [comment]
Uhm, I believe the "duplicate" you point to is exactly this issue. You might want to reopen.
