### ISSUE TITLE
`LD_PRELOAD` of `libswmhack` breaks Zephyr RTOS `west build`

### ISSUE THREAD

**Issue by Randoragon** [conformal/spectrwm#559]
This issue was found while developing for Zephyr, a free and open-source RTOS.

Steps to reproduce:
1. [Install `west`](https://docs.zephyrproject.org/latest/develop/west/install.html), Zephyr's utility command.
2. Create a new empty directory, `cd` to it, run `west init`.
3. Run `west update`.
4. `cd` to the newly created `zephyr` subdirectory.
5. Run `west build -b nucleo_l496zg samples/hello_world` (an arbitrary demo sample for an arbitrary platform).

Under spectrwm, this fails with:
```
/opt/zephyr-sdk/sysroots/x86_64-pokysdk-linux/usr/bin/dtc: error while loading shared libraries: libX11.so.6: cannot open shared object file: No such file or directory
CMake Error at /home/user/west/zephyr/cmake/modules/dts.cmake:355 (message):
  command failed with return code: 127
Call Stack (most recent call first):
  /home/user/west/zephyr/cmake/modules/zephyr_default.cmake:129 (include)
  /home/user/west/zephyr/share/zephyr-package/cmake/ZephyrConfig.cmake:66 (include)
  /home/user/west/zephyr/share/zephyr-package/cmake/ZephyrConfig.cmake:92 (include_boilerplate)
  CMakeLists.txt:5 (find_package)


-- Configuring incomplete, errors occurred!
FATAL ERROR: command exited with status 1: /usr/bin/cmake -DWEST_PYTHON=/usr/bin/python -B/home/user/west/zephyr/build -GNinja -DBOARD=nucleo_l496zg -S/home/user/west/zephyr/samples/hello_world
```

---

Long story short, the `LD_PRELOAD` somehow messes up detecting which shared libraries need to be dynamically linked with a binary.
If you take a look at the `dtc` program reported in the first line of the error and run `ldd` on it:
```
$ ldd /opt/zephyr-sdk/sysroots/x86_64-pokysdk-linux/usr/bin/dtc
	linux-vdso.so.1 (0x00007ffd445e7000)
	/usr/lib/libswmhack.so.0.0 (0x0000717f55157000)
	libc.so.6 => /usr/lib/libc.so.6 (0x0000717f54f55000)
	libX11.so.6 => /usr/lib/libX11.so.6 (0x0000717f54e12000)
	/opt/zephyr-sdk/sysroots/x86_64-pokysdk-linux/lib/ld-linux-x86-64.so.2 => /usr/lib64/ld-linux-x86-64.so.2 (0x0000717f5517e000)
	libxcb.so.1 => /usr/lib/libxcb.so.1 (0x0000717f54de7000)
	libXau.so.6 => /usr/lib/libXau.so.6 (0x0000717f54de2000)
	libXdmcp.so.6 => /usr/lib/libXdmcp.so.6 (0x0000717f54dda000)
```
Now, without `LD_PRELOAD`:
```
$ LD_PRELOAD= ldd /opt/zephyr-sdk/sysroots/x86_64-pokysdk-linux/usr/bin/dtc
	linux-vdso.so.1 (0x00007ffdbd2e5000)
	libc.so.6 => /usr/lib/libc.so.6 (0x00007fe5e1183000)
	/opt/zephyr-sdk/sysroots/x86_64-pokysdk-linux/lib/ld-linux-x86-64.so.2 => /usr/lib64/ld-linux-x86-64.so.2 (0x00007fe5e13a7000)
```
The latter output containing less libraries is correct. Running `LD_PRELOAD= west build -b nucleo_l496zg samples/hello_world` finishes without any issues using Zephyr SDK 0.16.1.

I don't know how this is possible, but it makes me want to globally disable `libswmhack.so` -- how do I know it's not messing up other programs' shared libraries as well?

This was observed on Arch Linux 6.7.0 running spectrwm 3.5.1.

**Comment by Randoragon** [comment]
I found #209 which looks like was dealing with the same problem, but affecting MATLAB.

**Comment by LordReg** [comment]
The Zephyr SDK toolchain uses its own dynamic-linker:
```
$ readelf -l /opt/zephyr-sdk/sysroots/x86_64-pokysdk-linux/usr/bin/dtc | grep interpreter
      [Requesting program interpreter: /opt/zephyr-sdk/sysroots/x86_64-pokysdk-linux/lib/ld-linux-x86-64.so.2]
```

Running `strace(1)` on `/opt/zephyr-sdk/sysroots/x86_64-pokysdk-linux/usr/bin/dtc` shows it only searches for `libX11.so.6` under `/opt/zephyr-sdk/sysroots/x86_64-pokysdk-linux`, which doesn't exist.

When running a program with a different dynamic linker that doesn't use the system libraries, the environment may need adjusting.

In this case, the inherited `LD_PRELOAD` should be unset.

e.g. in ~/.zephyrrc:
```
unset LD_PRELOAD
```
So that it is run when [setting up the build environment](https://docs.zephyrproject.org/latest/develop/env_vars.html#zephyr-environment-scripts) via `source zephyr-env.sh`.

Also, the other issue you referenced was a build issue and is resolved.

**Comment by Randoragon** [comment]
> When running a program with a different dynamic linker that doesn't use the system libraries, the environment may need adjusting.

Makes sense. I've never had to use `LD_PRELOAD` globally, so I wasn't expecting an issue to come from there.

> Also, the other issue you referenced was a build issue and is resolved.

Ok, sorry for misunderstanding, and thanks.
