### ISSUE TITLE
spectrwm segfaults first time it is ran

### ISSUE THREAD

**Issue by MatthewMateusz** [conformal/spectrwm#561]
Sorry if that is not probably formatted or is missing information. Please tell what information is needed and I will do my best to gather it.

After starting spectrwm for the first time after reboot the program core dumps after a few seconds (~20). If I run spectrwm again no segfault occurs. I'm not sure what is the causing this but I did manage to capture a log from syslog. Hope this is helpful:

```
Process 946 (spectrwm) of user 1000 dumped core.
   Stack trace of thread 946:
   #0  0x000075a8f92f583c n/a (libc.so.6 + 0x8e83c)
   #1  0x000075a8f92a5668 raise (libc.so.6 + 0x3e668)
   #2  0x000075a8f928d4b8 abort (libc.so.6 + 0x264b8)
   #3  0x000075a8f928e390 n/a (libc.so.6 + 0x27390)
   #4  0x000075a8f92ff7b7 n/a (libc.so.6 + 0x987b7)
   #5  0x000075a8f9301ad4 n/a (libc.so.6 + 0x9aad4)
   #6  0x000075a8f9304353 free (libc.so.6 + 0x9d353)
   #7  0x00006150c9522ab7 n/a (spectrwm + 0x18ab7)
   #8  0x00006150c953c06a n/a (spectrwm + 0x3206a)
   #9  0x00006150c95137db n/a (spectrwm + 0x97db)
   #10 0x000075a8f928ecd0 n/a (libc.so.6 + 0x27cd0)
   #11 0x000075a8f928ed8a __libc_start_main (libc.so.6 + 0x27d
   #12 0x00006150c9513925 n/a (spectrwm + 0x9925)
   ELF object binary architecture: AMD x86-64
```

**Comment by LordReg** [comment]
What version and OS?

**Comment by MatthewMateusz** [comment]
Archlinux
Version: 3.5.1 Build: a3614d12151f44a1d8472bf33a0d5d01c9a079c

**Comment by LordReg** [comment]
That build commit doesn't exist in this repo. Did you try the latest 2c776dfa3a712a326120cbd790ef552ebc2f42e6?

**Comment by MatthewMateusz** [comment]
I will try that and return to you about. The issue is occurring less after I updated Firefox. It now happens around once a month.

**Comment by MatthewMateusz** [comment]
It seems updating librewolf browser fixed my issue. No more crashes are happening. This issue can be closed.
