### ISSUE TITLE
What is the purpose of the search default program?

### ISSUE THREAD

**Issue by ZaxonXP** [conformal/spectrwm#566]
In the default configuration there is `program[search]` defined like this:
```
program[search]	        = dmenu -l 10 -p Search $dmenu_bottom -i -fn $bar_font -nb $bar_color -nf $bar_font_color -sb $bar_color_selected -sf $bar_font_color_selected
   bind[search]         = MOD+s
```
What is the purpose of it? What it supposed to search and return?

When I try to search for something then nothing happen. Can someone please explain the purpose and how to use?
Documentation does tell a bit.

Kind regards,
Piotr

**Comment by LordReg** [comment]
`program[search]` is used by the `search_win` and `search_workspace` actions. It is not meant to be bound. 
It can be overridden to use a different command/options (e.g. rofi). Will add a note.
