### ISSUE TITLE
warp_pointer behavior inconsistent across focus_modes

### ISSUE THREAD

**Issue by kalivtrope** [conformal/spectrwm#577]
The option `warp_pointer=1` along with `focus_mode=default` leads to the pointer automatically being centered *upon opening/closing a window*.

However, the pointer doesn't get properly centered in this situation when using `warp_pointer=true` with `focus_mode=follow`.

Quoting the docs:
```
warp_pointer
  Centers the pointer on the focused window when using bindings to change focus,  switch workspaces, change regions, etc
```
```
focus_mode
  default:  Set window focus on border crossings caused by cursor motion and window interaction.
  follow:   Set  window focus on all cursor border crossings, including workspace switches and changes to layout.
```
This would seem as if `follow` was actually just changing focus in more situations than `default` did. So why did the pointer centering logic change?

There is no mention of window opening/closing in either of those sections, and I'm curious whether this really is intended behavior.

**Comment by LordReg** [comment]
When windows map/unmap in `follow` focus mode, the focus depends on the pointer location. `warp_pointer` doesn't override focus behavior, it just enables pointer centering.

Are you just looking to have the same `warp_pointer` behavior as `default` mode in `follow` mode when opening/closing windows?

**Comment by kalivtrope** [comment]
Yes, I find it strange for the pointer to no longer center in `follow` focus mode when opening/closing windows.
