### ISSUE TITLE
Looks like i pulled the trigger too soon

### ISSUE THREAD

**Issue by marcopeereboom** [conformal/spectrwm#581]
I didn't see you had not pushed the CHANGELOG.

Sorry about that, was doing three things at the same time. @LordReg can you push that and update the release please?

**Comment by LordReg** [comment]
Fixed and released! https://github.com/conformal/spectrwm/releases/tag/SPECTRWM_3_6_0 :confetti_ball:

**Comment by marcopeereboom** [comment]
Sorry about that and W()()()()T!
