### ISSUE TITLE
Quit with confirmation

### ISSUE THREAD

**Issue by ZaxonXP** [conformal/spectrwm#583]
Currently there is a `bind[quit]` which, when accidently triggered, exits `spectrwm` without asking. Not the ideal condition.
I could make some script with `dmenu` asking for quit confirmation, then kill spectrwm. Is killing spectrwm the same as quiting it by binded shortcut?

I looked into the code and I see that on befiore quiting some clean up is done, so I guess the answer for my above question would be "No".

In that case, can I call quit spectrwm command from the external script?

**Comment by LordReg** [comment]
Yes, you can quit normally by sending `SIGTERM`, `SIGQUIT` or `SIGINT`. So a regular  `killall spectrwm` or `kill <pid>` will do the trick.

**Comment by ZaxonXP** [comment]
OK. Thanks for clarification.
