### ISSUE TITLE
Regions Reset on Screen Refresh due to Suspend, TTY Switching

### ISSUE THREAD

**Issue by egan** [conformal/spectrwm#62]
On Arch Linux with systemd, my regions are reset upon waking from suspend or switching TTYs. Is this behavior unavoidable due to the display architecture or would a fix be possible? As it is, a quick restart of the window manager repairs it but windows may be garbled due to their change in size.

**Comment by marcopeereboom** [comment]
I am very confused by this.  Resume should have absolutely no effect on the WM.  If this still occurs please reopen with detailed information.
