### ISSUE TITLE
Lone Window on WS Sometimes Loses Focus

### ISSUE THREAD

**Issue by egan** [conformal/spectrwm#82]
When there is a lone window on a workspace, that window sometimes loses focus when switching back to its workspace. I.e., I leave that window focused, work on another workspace, and when I return the window is not focused anymore. I think switching back out and into the workspace gives it focus again.

Unfortunately I haven't been able to tease out reproducible conditions for this to occur yet, but I'll post this here so you're aware of it. If anyone has any hunches on what to try, or I determine the cause or other factors, I'll update it here.

Below are some perhaps relevant configuration options I'm using:

```
focus_mode               = default
focus_close              = next
focus_close_wrap         = 1
focus_default            = last
warp_pointer             = 1
disable_border           = 1
```

**Comment by marcopeereboom** [comment]
If this still happens with the latest version please reopen with accurate and adequate information.  As it stands now I have no idea what version you used, what os, etc.
