### ISSUE TITLE
swap_main doesn't work in a specific case

### ISSUE THREAD

**Issue by levaidaniel** [conformal/spectrwm#84]
Let's say you have two windows on WS1. Put you mouse cursor away from over any window (eg. over to the spectrwm bar), so it won't interfere with focus (btw, **please** fix #51).
Change the active window focus to the master area (`focus_{next,prev}` with a hotkey), then start eg. a terminal with a hotkey. Now you have three windows on WS1, the latest (terminal) having the focus at the top of the stacking space.
Cycle through (this is also important) the three windows with `focus_{next,prev}`, then arrive at the (latest) top window in the stacking area (eg. the terminal you just started).
Now close that window (after this, the window in the master area gets the focus), and try to use `swap_main`; it won't work, only after you cycle through the remaining two active windows with `focus_{next,prev}`.
## 

Daniel

**Comment by marcopeereboom** [comment]
Any updates on this?

**Comment by levaidaniel** [comment]
Latest spectrwm still has this issue.
