### ISSUE TITLE
System tray

### ISSUE THREAD

**Issue by vext01** [conformal/spectrwm#89]
I would like the spectrwm bar to have a system tray.

I may look into this one day -- it's the only thing that prevents me from using spectrwm at the moment.

We may be able to steal code from i3 for example.

**Comment by marcopeereboom** [comment]
Please submit PR when ready.

**Comment by zakariakov** [comment]
I have tried several programs like trayer standaonetray
But it did not work
for example
quirk[stalonetray:stalonetray]			= FLOAT + ANYWHERE + NOFOCUSCYCLE + NOFOCUSONMAP + OBEYAPPFOCUSREQ
Doesn't work on all desktops

**Comment by Eccomi21** [comment]
> I have tried several programs like trayer standaonetray But it did not work for example quirk[stalonetray:stalonetray] = FLOAT + ANYWHERE + NOFOCUSCYCLE + NOFOCUSONMAP + OBEYAPPFOCUSREQ Doesn't work on all desktops

while i can get stalonetray to work by itself and make a screenshotting program like flameshot appear inside the system tray, i can't get it to be displayed properly on startup. i have to drag it around first like a floating window. did you find any solution yet?
