### ISSUE TITLE
buildver.sh tail(1) usage

### ISSUE THREAD

**Issue by levaidaniel** [conformal/spectrwm#95]
At least with this version of tail(1):
```
$ tail --version
tail (GNU coreutils) 8.23
```
buildver.sh can't output the revision, because `tail` thinks the `-c 9` option means that *9* is a file. The working usage is `tail -c9`, or `tail --bytes=9`

Before:
```
$ sh buildver.sh 
tail: cannot open ‘9’ for reading: No such file or directory
SPECTRWM_2_6_2-
```
After:
```
$ sh buildver.sh 
SPECTRWM_2_6_2-1e725018
```

**Comment by LordReg** [comment]
No issue here with the same version of tail:
```
$ tail --version
tail (GNU coreutils) 8.23
$ sh buildver.sh
SPECTRWM_2_6_2-1e725018
```
Maybe the shell?  I'm using zsh.

**Comment by levaidaniel** [comment]
Actually, this a Slackware specific issue, because the *coreutils* package gets compiled with `DEFAULT_POSIX2_VERSION=199209`, and that causes this (I presume legacy) operation.
Any chance you could change it to `--bytes=9`; that seems universal.

**Comment by LordReg** [comment]
That parameter isn't available on the POSIX.1-compliant OpenBSD tail(1).  http://www.openbsd.org/cgi-bin/man.cgi/OpenBSD-current/man1/tail.1?query=tail

**Comment by levaidaniel** [comment]
Oh, crap. Okay, I'll just work this around in the slackbuild.

Thanks!
