### ISSUE TITLE
request for bar_format to allow for both MIN and MAX width in a definition

### ISSUE THREAD

**Issue by notbenh** [conformal/spectrwm#99]
Currently +W takes the name of the window, because this is not fixed the bar contents changes location. You can define a max width via +100W to make sure that anything over 100 characters gets clipped. Though there is no way to define a minimum width so that +W will _always_ take 100 characters and pad with space (or a defined string) such that the bar content will remain static. 

Proposed syntax: +{PAD_STRING}:{MIN}:{MAX}{DEF}

Where PAD_STRING would default to a (space) such that +100:100W is the same as +' ':100:100W though it would allow for something like +0:2:2I would output 01 in the case of the first work-space. 
MIN and MAX should always be the absolute output length, as to include the length of PAD_STRING. For example if I was to say +'123':10:20I then I should see '1231231299' as my output for work-space 99 as '99' is two characters long thus MIN-2 is 8 thus fill up with as many repeating '123's till 8 is exceeded then trim to 8, cat both and then output.

**Comment by notbenh** [comment]
Forgot to mention, this is semi-related to #29

**Comment by masumhabib** [comment]
Hi,

I have implemented a less generic solution and it seems to work. My implementation uses '_' character to specify the padding. For example: +_100W will enable padding (using space) before window name in case the length is less than 100. Similarly, +100_W will enable padding after window name and +_100_W will enable padding both before and after the window name. This also kind of solves #29 on single monitor systems. 

If you are interested, checkout my [fork](https://github.com/masumhabib/spectrwm). If there is enough interest and the original authors agree with the implementation, I'll send a pull request.

**Comment by LordReg** [comment]
#179 was merged.  You can reopen this issue if you still want control of min-width/pad-string.
